valkey-io/valkey-glide

- node/src/BaseClient.ts
- node/tests/SharedTests.ts
- python/python/glide/async_commands/core.py
- python/python/tests/test_async_client.py
> When recieving LPOP/RPOP with count, convert result to Array

- node/DEVELOPER.md
- node/README.md
- python/DEVELOPER.md
- python/README.md
Package managers show the READMEs as the main text describes the package. Thus, the README should contain the header explaining what the project is. Additionally, removed the developer-oriented build explanation, and moved it to the DEVELOPER section, with a matching link.
> Make Node & Python's READMEs better for package managers.

- python/python/glide/__init__.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
> Python: add ZADD command

- node/src/BaseClient.ts
- node/src/Commands.ts
- node/tests/SharedTests.ts
> Added zadd and zaddIncr in node.

- glide-core/src/client/reconnecting_connection.rs
successfully has two `s`'s before the `f`
> reconnecting_connection.rs: Fix spelling succesfully -> successfully

- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds ZREM command and ZADD for transaction

- .github/workflows/pypi-cd.yml
Fixes #839. Wheels for 0.1.1 macos py38 and py39 were published to PyPi:
[glide_for_redis-0.1.1-cp38-cp38-macosx_11_0_arm64.whl ](https://files.pythonhosted.org/packages/a2/a2/aea18072fda218423ac6b298eeb54edb8f9faf5b3ea9eb7e92077a334336/glide_for_redis-0.1.1-cp38-cp38-macosx_11_0_arm64.whl)(1.8 MB [view hashes](https://pypi.org/project/glide-for-redis/#copy-hash-modal-fe8622b5-8084-4766-9a6b-419666eb5285))
[glide_for_redis-0.1.1-cp38-cp38-macosx_10_7_x86_64.whl ](https://files.pythonhosted.org/packages/04/dd/77c385222735f5ac254dfc8be889fc5e07d3c68d17d59595b87cd3b802ab/glide_for_redis-0.1.1-cp38-cp38-macosx_10_7_x86_64.whl)(1.9 MB [view hashes](https://pypi.org/project/glide-for-redis/#copy-hash-modal-55d9cab8-3862-4b90-bb87-6bd8e4c98589))
Action run: …
> Fix PyPi CD to publish python 3.8 3.9 wheels for macOS

- .vscode/settings.json
It's no longer a boolean, but an enum.
https://code.visualstudio.com/docs/typescript/typescript-refactoring#_code-actions-on-save
> Update the value of organizeImports.

- .github/workflows/java-benchmark.yml
- .github/workflows/java.yml
- java/benchmarks/build.gradle
- java/build.gradle
Update CI to match CI for node and python clients:
1. Test on different redis versions
2. Re-use redis installation script
3. Update benchmarking invocation
4. Add `macos` to CI
5. Add `amazonlinux` to CI (can't be tested outside of upstream)
Fixes https://github.com/aws/babushka/issues/7
Next step:
Split client test gradle tasks to UT and IT. Run UT once, but repeat IT on every platform/OS.
> Update CI for java client

- glide-core/src/client/standalone_client.rs
1. Add explicit error if primary node wasn't found.
2. Change the error message format, depending on how many internal errors it contains.
https://github.com/aws/glide-for-redis/issues/852
> Standalone client: Improve connection errors.

- benchmarks/rust/Cargo.toml
- benchmarks/rust/src/main.rs
- node/rust-client/Cargo.toml
- node/rust-client/src/lib.rs
This brings a significant perf improvement in Rust & Node. This replaces the allocator only for GLIDE in the Node library, and replaces the allocator for the whole Rust benchmarking application.
[jemalloc.xlsx](https://github.com/aws/glide-for-redis/files/14011810/jemalloc.xlsx)
Python jemalloc results are for code that isn't added here, where I used jemalloc in a similar way to the Node system. Since there wasn't an improvement, that change isn't a part of this PR.
> Use jemalloc as default allocator.

- benchmarks/node/node_benchmark.ts
- benchmarks/node/package.json
ioredis is currently the leading Node client, and so we should benchmark ourselves in comparison to it. Also kept the node-redis benchmark, since it's usually faster than ioredis.
> Node benchmark: benchmark the ioredis client.

- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/connectors/handlers/ChannelHandler.java
N/A
Without this fix `ConnectionManager` sends a connection request before the channel established and this request get lost/ignored by netty.
`syncUninterruptibly` is actually `await` which throws no exceptions.
> Java client: Fix how UDS connection established

- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Added zrem command in node and added zadd and zaddIncr to transactions.

- python/DEVELOPER.md
- python/python/glide/async_commands/core.py
- python/python/tests/conftest.py
Rebased over #866 
Fixes this python issue:
```
[Container] 2024/01/25 09:58:11.348983 Running command python3 -m pytest ${TESTS_TO_RUN} --asyncio-mode=auto --client Glide --timeout=3600 --capture=tee-sys -n 10 --dist loadscope --html=report.html --self-contained-html --junitxml=report.xml -m "not serverless and not memdb"
--
586 | ConftestImportFailure: TypeError: Descriptors cannot be created directly.
587 | If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
588 | If you cannot immediately regenerate your protos, some other possible workarounds are:
589 | 1. Downgrade the protobuf package to 3.20.x or lower.
590 | 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be …
```
> Update Python's protobuf compiler prerequisite to >= 3.20.0

- glide-core/src/socket_listener.rs
During node failures connection refused error can be raised. This error shouldn't result in closing the client, as the host might be under replacement / redis crashed or some temp reason for the connection to get refused. Removing this "if" fixes experienced downtime during failovers.
> Core: Connection refused error shouldn't close the client

- node/src/Transaction.ts
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_transaction.py
> Fix transaction doc to fit RESP3

- .github/workflows/java.yml
- java/client/build.gradle
- java/integTest/build.gradle
- java/integTest/src/test/java/glide/CommandTests.java
- java/integTest/src/test/java/glide/ConnectionTests.java
- java/integTest/src/test/java/glide/TestConfiguration.java
- java/integTest/src/test/resources/junit-platform.properties
- utils/cluster_manager.py
This PR adds IT test framework, some related script changes and sample tests.
IT test job starts redis in standalone mode on port 6380 in CI and a cluster on ports 7000-7006.
To connect to standalone use:
```java
var client =
RedisClient.CreateClient(
RedisClientConfiguration.builder()
.address(
NodeAddress.builder()
.port(TestConfiguration.STANDALONE_PORTS[0])
.build())
.build())
.get(10, TimeUnit.SECONDS);
```
To connect to cluster use:
```java
var clusterClient =
ClusterClient.CreateClient(
RedisClusterClientConfiguration.builder()
.address(
NodeAddress.builder()
.port(TestConfiguration.CLUSTER_PORTS[0])
.build())
.requestTimeout(3000)
.build())
.get(10, TimeUnit.SECONDS);
```
Test can be started by
```
./gradlew :integTest:test
```
The test report is written to 
``` …
```
> Java: Add IT framework

- java/client/src/test/java/glide/api/RedisClientCreateTest.java
- java/client/src/test/java/glide/managers/CommandManagerTest.java
- java/client/src/test/java/glide/managers/ConnectionManagerTest.java
Minor non-functional changed (code grooming).
Test cases are renamed because this thing replaces underscores by spaces, which makes test report more readable
https://github.com/aws/glide-for-redis/blob/e39f4ae12d1583a1d62d6cbce4aba5966ff270b8/java/client/src/test/resources/junit-platform.properties#L2
> Update unit tests for java client

- glide-core/tests/test_client.rs
- glide-core/tests/test_socket_listener.rs
- node/tests/RedisClientInternals.test.ts
- node/tests/SharedTests.ts
- python/python/tests/test_async_client.py
The word "handle" usually hides what the test really checks, and should be made explicit.
> Use more informative test names

- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Added zcard command in node.

- csharp/lib/src/lib.rs
- glide-core/src/client/standalone_client.rs
- glide-core/src/client/value_conversion.rs
- glide-core/tests/test_client.rs
- glide-core/tests/test_cluster_client.rs
- glide-core/tests/test_standalone_client.rs
- node/rust-client/src/lib.rs
from_owned_redis_value allows for some optimizations which aren't available when using a value reference.
> Replace from_redis_value with from_owned_redis_value

- benchmarks/csharp/Program.cs
- benchmarks/python/python_benchmark.py
- benchmarks/rust/src/main.rs
- benchmarks/utilities/utils.ts
This will make it easier to run the benchmarks directly, instead of through the script. As https://github.com/aws/glide-for-redis/pull/890 shows, new contributors need help with running the benchmarks.
> Make all arguments to benchmarks optional.

- python/python/glide/__init__.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds ZCOUNT command

- .github/workflows/csharp.yml
- .vscode/launch.json
- benchmarks/csharp/Program.cs
- benchmarks/csharp/csharp_benchmark.csproj
- benchmarks/install_and_test.sh
- csharp/DEVELOPER.md
- csharp/README.md
- csharp/csharp.sln
- csharp/lib/glide.csproj
- csharp/tests/tests.csproj
Adding instuction and runnable launch.json for csharp. Also updating frameworks list to match current version. 
In the process corrected version selector (to detect correct library base on OS)
> add instruction to run c# and current .net target

- java/integTest/src/test/java/glide/cluster/CommandTests.java
N/A
as requested in https://github.com/aws/glide-for-redis/pull/864#discussion_r1473899153,
adding an IT for cluster client with `ping` command.
> Add IT with ping for java cluster client.

- node/src/RedisClusterClient.ts
- node/src/Transaction.ts
- node/tests/TestUtilities.ts
This allows a builder-like pattern of calls, which is a bit more readable.
> Node: Allow chaining function calls on transaction.

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
- java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java
- java/client/src/main/java/glide/api/commands/ConnectionManagementCommands.java
- java/client/src/main/java/glide/managers/CommandManager.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/RedisClusterClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
This PR is dependent to: https://github.com/aws/glide-for-redis/pull/917
This PR adds get/set/ping/info calls to the standalone, and cluster-mode:
* standalone
* ping
* ping with message
* cluster
* ping
* ping with message
* ping with route
* ping with message and route
```java
// Single commands
RedisClient client = RedisClient.createClient(config).get();
String pingResult = client.ping().get();
String pingResult2 = client.ping("message").get();
// Cluster-mode single commands
RedisClusterClient clusterClient = RedisClusterClient.createClient(config).get();
String pingResult3 = clusterClient.ping(ALL_NODES).get();
String pingResult4 = clusterClient.ping("message", ALL_NODES).get();
```
By submitting this pull request, I confirm that you …
> Java: Add PING command

- .github/workflows/ort.yml
- .github/workflows/run-ort-tools/action.yml
Added an [OSS Review Tool (ORT)](https://github.com/oss-review-toolkit/ort) workflow as a github action. The ORT will analyze all package dependencies across the different languages and will create a NOTICE report to be used as the attribution files for each language.
The workflow is triggered by:
1. Scheduled event - the tool will run against the `main` branch once a day at 00:00. Any changes in the attribution files that will be found will be pushed to branch `scheduled-ort`, and a PR will be created to `main`.
2. Manual trigger: Use the [manually-running-a-workflow](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow) guide to run the ORT workflow. The workflow requires two inputs: the branch to run the ort tool from, for example, if it's for v0.2.1 release …
> Added ORT workflow

- .github/workflows/ort.yml
- utils/get_licenses_from_ort.py
The PR that will be created by the workflow will contain more informative list of the packages with unkown / not pre-approved licenses. For example:
Package_name: Crate::ring:0.17.7, Language: Python, License: NOASSERTION 
Package_name: PyPI::certifi:2024.2.2, Language: Python, License: MPL-2.0 
Package_name: PyPI::pathspec:0.12.1, Language: Python, License: MPL-2.0 
Package_name: Crate::ring:0.17.7, Language: Node, License: NOASSERTION 
Package_name: Crate::ring:0.17.7, Language: Rust, License: NOASSERTION
> CI: improving ORT script to log unkown / not pre-approved licenses

- .github/workflows/npm-cd.yml
If some of the NPM workflow succeeded (e.g., arm64Xubuntu), but other failed, we might need to rerun the workflows with the same version. This change allows us to rerun failed NPM CD workflows.
> NPM CD: No longer fails on an already published package.

- glide-core/src/client/mod.rs
- glide-core/src/client/value_conversion.rs
> Rust: modify sorted set command types to RESP3

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds HLEN command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Added zscore command in node.

- python/README.md
await can only be used in python inside async functions, therefore, the examples are misleading.
> Fixed Python example to properly work with python cli

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Added zcount command in node.

- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
Adds the `@NonNull` annotation to Java client constructors. 
Adds the `@NonNull` annotation to customCommand methods. 
The `@NonNull` annotation provide a runtime checker for null arguments, and throws a NullPointerException. 
> Java: Add @NonNull annotation to constructors and generic functions

- .github/workflows/java.yml
- java/integTest/src/test/java/glide/cluster/CommandTests.java
N/A
A comment in `info_with_routing_and_options` was confusing spotless and it was ignoring this file entirely.
Some technical details:
```
Skipping '/mnt/c/GitHub/babushka/java/integTest/src/test/java/glide/cluster/CommandTests.java' because it does not converge.  Run {@code spotlessDiagnose} to understand why
```
```
> Task :spotlessJavaDiagnose
integTest/src/test/java/glide/cluster/CommandTests.java diverges after 10 steps
```
https://github.com/diffplug/spotless/blob/main/PADDEDCELL.md
There is a spotless rule conflict, it goes to patch the file infinitely, but luckily it has a protection and breaks on 10th iteration.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> Fix java IT for linter

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/SetCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/ClusterTransactionTests.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TestUtilities.java
Adds set commands: `sadd`, `srem`, `smembers`, and `scard`.
Examples:
```java
Long saddResult = client.sadd("key", "member1", "member2", "member3", "member4").get();
assert saddResult == 4;
Long sremResult = client.srem("key", "member3").get();
assert sremResult == 1;
Set<String> smembersResult = client.smembers("key").get();
assert smembersResult.equals(Set.of("member1", "member2", "member4"));
Long scardResult = client.scard("key").get();
assert scardResult == 3;
```
> Java: Add SADD, SREM, SMEMBERS, and SCARD commands (Set Commands)

- node/tests/TestUtilities.ts
- python/python/tests/test_transaction.py
> Improve readability of transaction test

- node/src/RedisClusterClient.ts
- python/python/glide/async_commands/cluster_commands.py
N/A
As of https://github.com/amazon-contributing/redis-rs/pull/28 `CONFIG GET` behavior changed on cluster client if no routing provided.
> Update documentation for `CONFIG GET` command.

- CHANGELOG.md
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_transaction.py
> Python: Allow chaining function calls on transaction

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds ECHO command

- python/python/tests/test_async_client.py
```bash
python/tests/test_async_client.py::TestCommands::test_expireat_pexpireat_ttl_with_positive_timeout[ProtocolVersion.RESP2-True]
python/tests/test_async_client.py::TestCommands::test_expireat_pexpireat_ttl_with_positive_timeout[ProtocolVersion.RESP2-False]
python/tests/test_async_client.py::TestCommands::test_expireat_pexpireat_ttl_with_positive_timeout[ProtocolVersion.RESP3-True]
python/tests/test_async_client.py::TestCommands::test_expireat_pexpireat_ttl_with_positive_timeout[ProtocolVersion.RESP3-False]
/home/ubuntu/repositories/glide/python/python/tests/test_async_client.py:984: RuntimeWarning: coroutine 'check_if_server_version_lt' was never awaited
if not check_if_server_version_lt(redis_client, "7.0.0"):
Enable tracemalloc to get traceback where the object was allocated.
See …
```
> Fix test warning.

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds ZPOPMIN command

- .github/workflows/go.yml
- .github/workflows/java.yml
This PR stops the cancellation of workflows for Java and Golang when updates are pushed to a branch. It seems that there may be a race condition where the latest updates to a branch should win the race and not cause the workflow to be cancelled, but doesn't (a similar issue is posted at the bottom of this thread https://github.com/orgs/community/discussions/13496).
> Stop workflow cancellation when new commits are detected for Go and Java CI workflows

- .github/workflows/semgrep.yml
https://github.com/aws/glide-for-redis/issues/995
> Disable semgrep on push and pull_request untill we have creds for the entire team - currently SEMGREP_APP_TOKEN works only for ikolomi account

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> added Lindex command to node

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds ZPOPMAX command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: added zpopmin command.

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: added zpopmax command.

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
> Add initial stream commands to protobuf.

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
Adding the UNLINK() command (Generic command).  Note, unlink() and del() are very similar commands. 
Example: 
```
// assuming key1 and key2 exist, while key "invalid" does not. 
Integer result = client.unlink(new String[] {"key1", "key2", "invalid"}).get();
assert result == 2;
```
> Java: Add `UNLINK()` command

- glide-core/tests/test_socket_listener.rs
The tests are made simpler by 
1. moving repeated logic to side functions, thus reducing the focusing the tests on their intention, rather than implementation details.
2. replacing booleans with enums, in order to make the test configuration more readable. `setup_basics(true, false, true)` is hard to decipher, and requires reading the function's signature in order to understand.
> Make socket listener tests more readable.

- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
- .github/workflows/update-glide-version/action.yml
- benchmarks/rust/.cargo/config.toml
- csharp/lib/.cargo/config.toml
- glide-core/.cargo/config.toml
- java/.cargo/config.toml
- node/rust-client/.cargo/config.toml
- node/tests/SharedTests.ts
- python/.cargo/config.toml
- python/python/tests/test_async_client.py
- utils/get_licenses_from_ort.py
> Fixed updating the library version in the CD workflow

- CHANGELOG.md
- node/src/RedisClusterClient.ts
- node/tests/RedisClusterClient.test.ts
> Node: enable routing by node address.

- python/python/glide/redis_client.py
- python/python/tests/test_async_client.py
found with `flake8 . --count --exit-zero --max-complexity=12 --max-line-length=127 --statistics --exclude=python/glide/protobuf,.env/* --extend-ignore=E230`
1     E203 whitespace before ':'
4     E711 comparison to None should be 'if cond is None:'
5     E712 comparison to True should be 'if cond is True:' or 'if cond:'
1     F401 'typing.Set' imported but unused
1     F841 local variable 'e' is assigned to but never used
> Fix lint warnings

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
- java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java
- java/client/src/main/java/glide/api/commands/ConnectionManagementCommands.java
- java/client/src/test/java/glide/api/RedisClusterClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
Move `ping()` commands on the java side to be consistent with other clients.  
> Java: Move ping() commands out of baseclient

- java/benchmarks/src/main/java/glide/benchmarks/clients/jedis/JedisClient.java
Before: 
```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe
at glide.benchmarks.utils.Benchmarking.testClientSetGet(Benchmarking.java:163)
at glide.benchmarks.BenchmarkingApp.main(BenchmarkingApp.java:51)
Caused by: java.util.concurrent.ExecutionException: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe
```
Fixed: 
```
> ./install_and_test.sh -$CLIENT -tasks 1 10 100 1000 -data $DATASIZE -clients 1 -host $HOST -tls -is-cluster;
...
=====> Jedis <===== 1 clients 1000 concurrent 100 data size 
Runtime s: 273.788191
Iterations: 10000000
TPS: 36524.584858 …
```
> Update jedis sync client with thread pooling

- java/client/src/main/java/glide/connectors/handlers/ChannelHandler.java
- java/client/src/main/java/glide/connectors/handlers/ReadHandler.java
- java/client/src/test/java/glide/connection/ConnectionWithGlideMockTests.java
- java/client/src/test/java/glide/utils/RustCoreLibMockTestBase.java
- java/client/src/test/java/glide/utils/RustCoreMock.java
Features:
1. Error handling on UDS write
2. Error handling on UDS read
3. Glide core mock
4. Test superclass with glide core mock
5. Tests for error handling
Missing:
1. Error handling on channel creation. Left TODO there. Requires significant rework of `ChannelHandler`.
2. IT - can't be reproduced in IT unfortunately.
> Java: Add UDS read/write error handling and tests with glide core mock

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds SISMEMBER command

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/ExpireOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
> Java: Add `expire`, `expireAt`, `pexpire`, `pexpireAt` and `ttl` commands.

- go/DEVELOPER.md
- Add DEVELOPER.md for Go with instructions for installing, building, linting, and testing the client
> Add DEVELOPER.md for Go

- java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
- java/client/src/main/java/glide/api/commands/GenericClusterCommands.java
- java/client/src/main/java/glide/api/commands/GenericCommands.java
> Java: Add examples to missing commands and minor fixes Generic Commands. (#125)

- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: added echo command.

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: added hvals command.

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
> Python: adds PTTL command

- .github/workflows/npm-cd.yml
- node/package.json
Changed npm-cd workflow to fit the changes from https://github.com/aws/glide-for-redis/pull/1002
> Adjust npm-cd to fit prettier structure

- glide-core/src/client/value_conversion.rs
- glide-core/src/errors.rs
- glide-core/src/lib.rs
- glide-core/src/socket_listener.rs
- glide-core/tests/test_client.rs
- java/src/lib.rs
- node/rust-client/src/lib.rs
- python/src/lib.rs
This will allow FFI clients to use the same logic.
https://github.com/aws/glide-for-redis/issues/1066
> Extract error sorting code to module.

- CHANGELOG.md
- node/src/RedisClusterClient.ts
- python/python/glide/__init__.py
- python/python/glide/constants.py
- python/python/glide/routes.py
- python/python/tests/test_async_client.py
> Python: enable routing by node address.

- .github/workflows/lint-ts.yml
- benchmarks/node/node_benchmark.ts
- benchmarks/node/package.json
- benchmarks/node/tsconfig.json
- benchmarks/utilities/fill_db.ts
- benchmarks/utilities/flush_db.ts
- benchmarks/utilities/package.json
- benchmarks/utilities/tsconfig.json
- benchmarks/utilities/utils.ts
- node/DEVELOPER.md
- node/babel.config.js
- node/npm/glide/index.ts
- node/rust-client/.ort.yml
- node/rust-client/package.json
- node/rust-client/tsconfig.json
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Logger.ts
- node/src/RedisClient.ts
- node/src/RedisClusterClient.ts
- node/src/Transaction.ts
- node/tests/AsyncClient.test.ts
- node/tests/RedisClient.test.ts
- node/tests/RedisClientInternals.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/RedisModules.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
As we recommend in our DEVELOPER.md for Node to use prettier, we should follow the lint of what prettier give as a default. 
As Node developers, we encountered a lot the borden of fixing unwanted lints from prettier, that are actually needed lints, but are not part of the PR context, and for saving our time and nerves I created new workspace with fresh prettier and let it fix the TS files so we don't need to fight with it anymore - all what developers need to do is to use the default of prettier.
Added prettier scripts for check and format, added instructions for usage, added to the CI, and aligned all the file with the standard. 
Changed npm-cd workflow to fit the changes - https://github.com/aws/glide-for-redis/pull/1081
Changed lint-ts to instead of receptively create a task for each …
> Lint all TS files base on our prettier for easier developer life, and added CI prettier step

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: added persist command.

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: added sismember command.

- .github/workflows/csharp.yml
- .github/workflows/go.yml
- .github/workflows/java.yml
- .github/workflows/lint-ts.yml
- .github/workflows/node.yml
- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
- .github/workflows/python.yml
- .github/workflows/rust.yml
Restore CI concurrency removed in #991.
To avoid conflicts between different CI workflows, every group name contains the wrapper name.
The purpose of this to cancel CI for a branch if it got a new commits (so new CI started).
Docs:
https://docs.github.com/en/actions/learn-github-actions/contexts
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
> Configure concurrency for all CI. (#106)

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClientInternals.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: Add support for XADD, XTRIM commands.

- .github/workflows/install-shared-dependencies/action.yml
This fix is missing from #1094
> CI/MacOS: Fixed brew to update and upgrade before installing dependencies

- java/integTest/build.gradle
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TestConfiguration.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
The built-in library is unable to parse versions such as 7.2.0.
> Java: Use 3rd party lib for version checking. (#130)

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Added zremRangeByScore command in Node.

- java/benchmarks/src/main/java/glide/benchmarks/utils/Benchmarking.java
- java/benchmarks/src/main/java/glide/benchmarks/utils/LatencyResults.java
1. Latencies were calculated in seconds, however they are printed as `ms`. Fixed latencies to be calculated in milliseconds.
2. Truncated all latencies to 3 decimal places
3. Converted TPS to int
4. Changed totalHits to totalRequests, as 'hits' in Redis refer to getting/setting an existing key
Prev output:
```
Runtime s: 8.412975
Iterations: 1000000
TPS: 118864.015717
===> SET <===
avg. time ms: 0.000834
std dev ms: 0.000627
p50 latency ms: 0.000768
p90 latency ms: 0.000924
p99 latency ms: 0.002636
Total hits: 199776
===> GET_NON_EXISTING <===
avg. time ms: 0.000830
std dev ms: 0.000590
p50 latency ms: 0.000767
p90 latency ms: 0.000920
p99 latency ms: 0.002542
Total hits: 160035
===> GET_EXISTING <===
avg. time ms: 0.000831
std dev ms: 0.000640
p50 latency ms: 0.000767
p90 latency ms: …
```
> Java: improved benchmark prints and results

- .github/workflows/java.yml
The CI timeout was increased from 25 minutes to 35 minutes due to the failure of CI for some pull requests. This change was necessary because adding more tests caused the previous timeout limit to be exceeded.
> Java: Increased timeout for workflow as CI timed out.

- java/integTest/src/test/java/glide/TestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
The test cluster_route_by_address_reaches_correct_node test was flaky due to timestamp fields in the CLUSTER NODES command output. These fields were "ping-sent" and "pong-recv" . To resolve this, I modified the test to mask the timestamps, focusing only on stable fields. You can find more info about this at https://redis.io/commands/cluster-nodes/. I also believe that the Node and the Python clients equivalent test would be flaky if these fields are not removed. 
> Java: Fixed flakey test for cluster route by address reaches correct node.

- glide-core/tests/test_socket_listener.rs
- java/integTest/src/test/java/glide/TestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- node/tests/RedisClusterClient.test.ts
- python/python/tests/test_async_client.py
https://github.com/aws/glide-for-redis/issues/1122
> Fix flakey test.

- benchmarks/install_and_test.sh
- java/benchmarks/src/main/java/glide/benchmarks/utils/Benchmarking.java
See benchmarking results in: https://github.com/aws/glide-for-redis/issues/691#issuecomment-1980111310
fixes: https://github.com/aws/glide-for-redis/issues/691
Two changes: 
1. Switch from using LinkedBlockingQueue to using SynchronousQueue so that tasks are executed more synchronously (similar to Python and Node benchmarking). 
2. Added a RejectedExecutionHandler to add robustness to the system in case threads are unable to be added to the queue. 
> Java: Update benchmarking to use SynchronousQueue (#129)

- .github/workflows/node.yml
- .github/workflows/pypi-cd.yml
- .github/workflows/python.yml
Due to recent fixes #1094 #1098 in MacOS CI in node and python the overall CI time was increased.
> Increased Python & Node MacOS github actions timeout

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds HVALS command

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/glide/constants.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds ZRANK command

- utils/cluster_manager.py
Fixing flakeyness that is being caused by:
```
subprocess.TimeoutExpired: Command '['redis-cli', '--cluster', 'create', '127.0.0.1:25528', '127.0.0.1:12261', '127.0.0.1:8734', '127.0.0.1:36600', '127.0.0.1:18288', '127.0.0.1:36402', '--cluster-replicas', '1', '--cluster-yes']' timed out after 20 seconds
```
https://github.com/aws/glide-for-redis/actions/runs/8343816789/job/22834784827?pr=1089
This command is responsible for meeting all nodes, set all slots, and make nodes replicas, which can be longer
> cluster_manager: Increased timeout for creating a cluster

- .github/workflows/lint-rust/action.yml
- .github/workflows/rust.yml
- benchmarks/rust/src/main.rs
- csharp/lib/src/lib.rs
- glide-core/Cargo.toml
- glide-core/benches/memory_benchmark.rs
- glide-core/build.rs
- glide-core/src/client/mod.rs
- glide-core/src/client/reconnecting_connection.rs
- glide-core/src/client/standalone_client.rs
- glide-core/src/client/types.rs
- glide-core/src/lib.rs
- glide-core/src/retry_strategies.rs
- glide-core/src/socket_listener.rs
- glide-core/tests/test_client.rs
- glide-core/tests/test_socket_listener.rs
- glide-core/tests/test_standalone_client.rs
- glide-core/tests/utilities/cluster.rs
- glide-core/tests/utilities/mod.rs
- java/Cargo.toml
- node/rust-client/Cargo.toml
- python/Cargo.toml
This will allow the FFI clients to remove their dependency on protobuf. 
Pros:
* faster compile times
* no need for protobuf dependency in FFI wrappers.
Cons:
* code duplication in model.
> Separate connection info from protobuf.

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
"request_policy:all_shards"
"response_policy:agg_sum"
> Python: adds DBSIZE command

- CHANGELOG.md
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/tests/test_async_client.py
> Python: adds TIME command

- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
- .github/workflows/start-self-hosted-runner/action.yml
In order to automatically activate the runner, we did:
1. SSM installed on the EC2 host
2. Created an SSM document to start the runner process on the host
3. IAM user was created for github actions, keys were stored as secrets in github
4. The CD jobs will wait for the runner to be activated
5. The CD job will change ownership permissions for the _work folder to allow checking out the repository (see https://github.com/actions/checkout/issues/211#issuecomment-611986243)
https://github.com/machulav/ec2-github-runner/  haven't been used since it requires an org:admin access in order to generate a registration key for the runner, which `aws` org doesn't provide.
Closes #656
> CD: Automate the activation of the self hosted runner

- node/DEVELOPER.md
- node/jest.config.js
- node/tsconfig-cjs.json
- node/tsconfig-mjs.json
- node/tsconfig.json
If you are using some TS extensions you noticed some new errors showing in some of the TS files.
The reason is that the different TS extensions are looking for tsconfig file for their rules. And since we dont have one anymore some errors pops in the IDE.
Those errors are not real errors, since when build run and test we did config to which config file tsc and jest should go for rules, but while working it can be annoying to see red marks all over your file,
So instead of calling the general config file `tsconfig-base`, we call it simply `tsconfig` and then whatever look for tsconfig as default will find the base rule we use. 
We adding default outDir value, since otherwise the default is /src and it cause more red marks (since we don't have our `d.ts` files in /src).
Since now extensions …
> Node - Minor - changed tsconfig-base to tsconfig and added default outdir

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/socket_listener.rs
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: Brpop Command

- node/hybrid-node-tests/commonjs-test/commonjs-test.cjs
- node/hybrid-node-tests/ecmascript-test/ecmascript-test.mjs
Fix semgrep detected vulnerability in hybrid tests by using array which does not allow shell parameter expansion
> Node - Fix semgrep detected vulnerability in hybrid tests

- benchmarks/node/package.json
- benchmarks/python/requirements.txt
To avoid issues with changes in the clients' licenses
> Set the versions of external clients to be fixed on the current latest releases.

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- python/python/glide/async_commands/redis_modules/json.py
- python/python/glide/constants.py
- python/python/tests/tests_redis_modules/test_json.py
> Python: adds JSON.TOGGLE command

- node/fixup_pj_files_for_build_type
- node/npm/glide/index.ts
- node/npm/glide/package.json
- node/npm/glide/tsconfig-cjs.json
- node/npm/glide/tsconfig-mjs.json
- node/npm/glide/tsconfig.json
- node/package.json
Apparently when inheriting tsconfig, everything is happening in the folder of the parent-file, so paths etc. are  base on where the parent file located, which broke the importing of index file for different arch'
Plus - the index file was written in a way that can work just with esm, so translated it to fit both.
> node - fixed broken path of tsconfig translation

- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
- java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java
- java/client/src/main/java/glide/api/commands/ServerManagementCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/utils/ArrayTransformUtils.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/RedisClusterClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
Add [Time()](https://redis.io/commands/time/) command to the java wrapper for both standalone and cluster modes. 
> Java: Add `Time()` command

- glide-core/Cargo.toml
- glide-core/src/socket_listener.rs
The signals hook caused Node to not respond to ^C and similar signals, since Node yields to existing signals hooks. Tested Python, Node, C#, & Java benchmarks - all closed with ^C after this change.
> Removed signals hook in socket.

- benchmarks/install_and_test.sh
The benchmark shouldn't run twice, and is currently broken for anyone who doesn't have .net 8 installed. If there's an interest in the benchmark result of different frameworks, the framework can be added as an argument.
> C#: run the benchmark once.

- CHANGELOG.md
- python/python/glide/redis_client.py
Resolves error on python3.8:
```
Traceback (most recent call last):
File “client_example.py”, line 6, in <module>
from glide import (
File “/Users/daganh/Library/Python/3.8/lib/python/site-packages/glide/__init__.py”, line 11, in <module>
from glide.async_commands.redis_modules import json
File “/Users/daganh/Library/Python/3.8/lib/python/site-packages/glide/async_commands/redis_modules/json.py”, line 23, in <module>
from glide.redis_client import TRedisClient
File “/Users/daganh/Library/Python/3.8/lib/python/site-packages/glide/redis_client.py”, line 38, in <module>
) -> type[RequestError]:
TypeError: ‘type’ object is not subscriptable
> Python: Fix typing

- csharp/lib/glide.csproj
Before this change, Rust was always compiled in release mode. This allows tests to compile in debug mode, which cuts the compilation time from ~1:20 minutes to 0:30.
> C#: Split debug and release Rust compilation.

- python/python/tests/test_async_client.py
The fix that was done in PR #1123 doesn't properly truncate the cluster nodes output in python, so the test remain flakey.
> Fix python flakey test

- .github/workflows/ort.yml
This is a temporary fix, currently ORT has a bug with newer version of Cargo, till they will fix computability with Cargo newer versions, we will work with 1.76
https://github.com/oss-review-toolkit/ort/issues/8480
> Fix temporarily misalignment with new version of Cargo

- node/src/BaseClient.ts
- node/src/RedisClient.ts
- node/src/RedisClusterClient.ts
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/core.py
> Add missing examples for Python and Node

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
- python/python/glide/async_commands/core.py
> Node: added zrange and zrangeWithScores commands.

- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/RedisClusterClientTest.java
- java/client/src/test/java/glide/connection/ConnectionWithGlideMockTests.java
- java/client/src/test/java/glide/connectors/resources/ThreadPoolResourceAllocatorTest.java
- java/client/src/test/java/glide/ffi/FfiTest.java
- java/client/src/test/java/glide/managers/ConnectionManagerTest.java
- java/client/src/test/java/glide/utils/RustCoreMock.java
- java/integTest/src/test/java/glide/SharedClientTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
Cleans up all compiler warnings in the Java/Client/src/test folder.  Most of the changes are like this:
```java
CompletableFuture<Object> testResponse = mock(CompletableFuture.class);
when(testResponse.get()).thenReturn(value);
```
changed to:
```java
CompletableFuture<Object> testResponse = new CompletableFuture<>();
testResponse.complete(value);
```
The above tests clean up the type error when converting from `CompletableFuture` to `CompletableFuture<Object>`. 
> Clean up all warnings in Java client test

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/StreamAddOptions.java
- node/src/BaseClient.ts
- node/src/Transaction.ts
Update the XADD and XTRIM documentation, and add more context to the commands. 
> Java/Node: Update docs for `xadd` and `xtrim`

- java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java
- java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
N/A
Ninor clean up in trasnaction implementation (without code changes)
No BL changes.
> Java: misc fixes

- java/client/build.gradle
N/A
Hotfix for #1237. While addressing [this comment](https://github.com/aws/glide-for-redis/pull/1237#discussion_r1558888000) we broke the version check.
Before:
```
$ ./gradlew protobuf
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD SUCCESSFUL in 852ms
1 actionable task: 1 executed
```
After:
```
$ ./gradlew protobuf
> Task :client:protobuf FAILED
FAILURE: Build failed with an exception.
* Where: …
```
> Java: Fix protoc version check.

- .github/workflows/csharp.yml
- benchmarks/csharp/Program.cs
- benchmarks/csharp/csharp_benchmark.csproj
- csharp/.editorconfig
- csharp/lib/AsyncClient.cs
- csharp/lib/Logger.cs
- csharp/lib/Message.cs
- csharp/lib/MessageContainer.cs
- csharp/lib/Properties/AssemblyInfo.cs
- csharp/lib/glide.csproj
- csharp/tests/Integration/GetAndSet.cs
- csharp/tests/Integration/IntegrationTestBase.cs
- csharp/tests/Usings.cs
- csharp/tests/tests.csproj
- Enabling strict rules check by adding `dotnet_analyzer_diagnostic.category-Style.severity = error` in .editorconfig and 
`<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild> ` to project files. 
- Added lang section to enable modern syntax
- Added workaround to handle unused imports
- Applied rules in all C# codebase
- disable HandleVeryLargeInput according to https://github.com/aws/glide-for-redis/pull/1085/files
- timer for workflow set to 25 min (better caching strategy pending)
> C#: Strict rules

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/RangeOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
> Java: Add command `Zrangestore`. (Sorted Set Group) (#202)

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
- java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java
- java/client/src/main/java/glide/api/commands/ServerManagementCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/SetOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/RedisClusterClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
- java/integTest/src/test/java/glide/standalone/TransactionTests.java
N/A
https://redis.io/docs/latest/commands/lastsave/
> Java: Add `LASTSAVE` command.

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/__init__.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds GEOADD command

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
This pr is rebased over #1259 
> Python: adds GEOHASH command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/zlexcount/
> Python: add ZLEXCOUNT command (#230)

- csharp/tests/Integration/GetAndSet.cs
- csharp/tests/Integration/IntegrationTestBase.cs
- csharp/tests/Usings.cs
- csharp/tests/tests.csproj
Changing UTest framework to XUnit, because it will allow to address NUnit constrain (Setting Up will require separate method with attribute, so initialising on shared variables couldn't be done in constractor)
> C#: changing utest framework to xunit

- .github/workflows/ort.yml
As ORT fixed their bug, this temporary fix is not needed anymore.
https://github.com/oss-review-toolkit/ort/commit/7522a0c3e9051a7bb8961ae56e7ce35f063a673f
> remove temporary fix as it not nedded anymore

- glide-core/tests/test_client.rs
- glide-core/tests/utilities/cluster.rs
- glide-core/tests/utilities/mod.rs
Core test utilities: moved client creation to a separate function to allow creating additional clients from tests
> Core test utilities: moved client creation to a separate function

- go/benchmarks/benchmarking.go
N/A
- This PR fixes a bug where the benchmarks were ran twice for go-redis when the -clients option was set to "all"
> Go: Fix bug with -clients=all setting

- .github/workflows/go.yml
- go/Makefile
- go/benchmarks/go.mod
- go/benchmarks/go.sum
- go/go.mod
- go/go.sum
- N/A
- equivalent to #1351, but will be merged into the Go feature branch
- this PR addresses a dependabot alert suggesting that the go protobuf version be updated to v1.33.0
> Go: update protobuf version to address dependabot alert

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
- java/integTest/src/test/java/glide/standalone/TransactionTests.java
> Java: Add `Zrevrank` command.

- java/integTest/src/test/java/glide/standalone/TransactionTests.java
Adding shared test for WATCH on a transaction.  Should be updated when we implement the WATCH command. 
> Add WATCH returns null standalone test

- .github/workflows/ort.yml
ORT versions 21.0.0 and above are affected by the issue described in https://github.com/oss-review-toolkit/ort/issues/8571.
This PR downgrades ORT to version 20.1.0. However, since this version also has an issue with Cargo (https://github.com/oss-review-toolkit/ort/issues/8480), we still need to use a workaround to install Rust toolchain v1.76.
To ensure stability, we will stick with a known working version of ORT instead of pulling the latest version.
Once a version newer than 22.1.0, addressing the issue in https://github.com/oss-review-toolkit/ort/issues/8571, is released, we will use it and hardcode it into the action.
> Fix ORT workflow

- .github/workflows/build-node-wrapper/action.yml
- .github/workflows/build-python-wrapper/action.yml
- .github/workflows/csharp.yml
- .github/workflows/go.yml
- .github/workflows/install-shared-dependencies/action.yml
- .github/workflows/java.yml
- .github/workflows/node-create-package-file/action.yml
- .github/workflows/node.yml
- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
- .github/workflows/python.yml
- .github/workflows/rust.yml
- benchmarks/install_and_test.sh
Based on https://github.com/aws/glide-for-redis/pull/1358.
This PR:
- Disables CD workflows on forks (checks fort he repo owner)
- Differentiate between OS and RUNNER ('ubuntu' vs 'ubuntu-latest') argument, to allow fine-grained dependency installation later on
- The github runner for macos-latest was updated, and now it requires some modifications in the CI to support the newer macOS version:
1. The latest MacOS runs on ARM64 vs the former which runs on Intel
2.The latest  MacOS requires installation flag for python installation
Rebased over #1366
> Fix CI workflows

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
- https://redis.io/docs/latest/commands/hrandfield/
- Includes value conversion:
- RESP2 returns a flat array of BulkString values, where even-positioned elements are keys and odd-positioned elements are values. RESP3 returns an array of array of BulkString values (in other words, a 2D-array where the inner arrays are key-value pairs). The value conversion converts the RESP2 responses to the RESP3 format.
- Note that the returned type is a List instead of a Dict because the response may contain duplicates if the user passes in a negative count argument
> Python: add HRANDFIELD command

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
- https://redis.io/docs/latest/commands/zmscore/
- Note: includes value conversion
- RESP2 returns an array of BulkString values, where each string represents a Double. The value conversion added in this PR converts array-of-bulkstring responses to array-of-double responses, which matches the RESP3 format
> Python: add ZMSCORE command

- CHANGELOG.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds XADD, XTRIM commands

- glide-core/tests/utilities/cluster.rs
N/A
A new version of Rust just dropped today (https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html) and it is causing linting to fail on main, which breaks our CI builds. This change fixes the new clippy linting error.
```
error: assigning the result of `Clone::clone()` may be inefficient
--> tests/utilities/cluster.rs:125:13
|
125 |             password = info.password.clone();
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_from()`: `password.clone_from(&info.password)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
= note: `-D clippy::assigning-clones` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::assigning_clones)]`
```
By submitting this …
> Core: Fix clippy linting error

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/sorted_set.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://valkey.io/commands/zrangestore/
> Python: add ZRANGESTORE command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/RedisClient.ts
- node/src/RedisClusterClient.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
- python/python/glide/async_commands/core.py
***Description of changes:***
Currently, the way we convert the rust value returning from core to a js value, is by using napi.
Since napi doesn't support sets, commmands with a return type of set, returns an array in node.
This is breaking the GLIDE API, since similar commands in different wrappers return a completely different type.
Until napi will add support for sets, we will convert each of the command to a Set, in the wrapper. 
> Node: convert Set commands return type to Set

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/utils/ArrayTransformUtils.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
Issue #, if available:
Description of changes:
- adding Geopos
- adding Geopos unit tests & transaction tests
- adding to ArrayTransformUtils
> Java: Add command `GEOPOS`

- node/package.json
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
- python/python/tests/conftest.py
- python/python/tests/test_async_client.py
- python/python/tests/utils/cluster.py
This PR introduces the ability to specify endpoints when running tests for both Python and Node environments.
To run the tests in python using with external endpoints:
`pytest --asyncio-mode=auto --cluster-endpoints=host:port,host2:port2 --standalone-endpoints=host1:port
`
In Node:
`npm run test -- --cluster-endpoints=host:port,host2:port2 --standalone-endpoints=host1:port
`
> Allow endpoint specification for Python and Node test

- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
- node/tests/UtilsTests.test.ts
- python/python/glide/constants.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
- python/python/tests/test_utils.py
- python/python/tests/utils/utils.py
> Refactor map comparison in Python and Node

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/zdiff/
> Python: add ZDIFF command

- python/python/tests/test_async_client.py
Before merging #1319 I forgot to update the new commands with return type of a map
> Python: update map comparisons to use compare_maps function

- CHANGELOG.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/sorted_set.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/bzmpop/
> Python: add BZMPOP command

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/zintercard/
> Python: add ZINTERCARD command

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/zmpop/
> Python: add ZMPOP command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/smove/
> Python: add SMOVE command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/sunionstore/
> Python: add SUNIONSTORE command

- .github/workflows/build-node-wrapper/action.yml
- .github/workflows/install-rust-and-protoc/action.yml
- .github/workflows/install-shared-dependencies/action.yml
- .github/workflows/lint-rust/action.yml
- .github/workflows/node-create-package-file/action.yml
- .github/workflows/node.yml
- .github/workflows/npm-cd.yml
- .github/workflows/rust.yml
- .github/workflows/setup-musl-on-linux/action.yml
- CHANGELOG.md
- node/npm/glide/index.ts
- node/npm/glide/package.json
Issues - #1205 #1226 
Adding support for node on alpine (or any MUSL C library)  for arm64 and x64.
Build and tests on arm alpine added to node CI.
Missing exports added since CI fails on them.
> Adding support for node:alpine

- .github/workflows/npm-cd.yml
Added option of release candidate to the CI.
If a tag including 'rc' in it it will set the publish tag to next, so it won't be install without specific direction.
To my understanding from https://pythonpackaging.info/07-Package-Release.html pypi automatically set version with -rc in their version as prerelease version.
@barshaul @shohamazon please check if i got it right.
> Added check if tag include rc init, if so release as @next

- .github/workflows/node.yml
In order to fix failure on node ci, we'll test musl on x86, using gh runners instead of self-hosted
> Change Node musl tests to running on x86

- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
N/A
- the zmpop docs contain a copy-pasted section from bzmpop that is not applicable to zmpop since zmpop does not have a timeout. This PR fixes the doc for zmpop by removing the mention of the timeout.
> Python: fix minor error in zmpop documentation

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/sinter/
> Python: add SINTER command

- java/integTest/src/test/java/glide/TestUtilities.java
- java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
- java/integTest/src/test/java/glide/standalone/TransactionTests.java
N/A
Add deep comparison for nested collections.
Standard `assertEquals` uses `equals` method co compare collection entries (map, lists, etc), which does not work when an entry stores an array.
Blocker for `FUNCTION LIST` and `LMPOP`.
> Java: Update transaction IT.

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/sdiff/
> Python: add SDIFF command

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
Issue #, if available:
N/A
Description of changes:
Implements `BITPOS` command in the java client.
> Java: Add `BITPOS` command 

- java/integTest/src/test/java/glide/SharedCommandTests.java
- objectIdleTime test fails intermittently, we suspect that idletime doesn't update frequently enough within 1 second, changing to a longer duration
> changing sleep duration for ObjectIdletime Test

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/HashBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
https://redis.io/docs/latest/commands/hrandfield/
Inspired by https://github.com/aws/glide-for-redis/pull/1334 and https://github.com/aws/glide-for-redis/pull/1238
> Java: Add `HRANDFIELD` command.

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/bitmap/BitwiseOperation.java
- java/client/src/main/java/module-info.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
Issue #, if available:
N/A
Description of changes:
Implements `BITOP` command in the java client.
> Java: Add `BITOP` command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/setrange/
> Python: Add SETRANGE command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/object-encoding/
> Python: add OBJECT ENCODING command

- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/ListBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
* Java: Add command BLMPOP
---------
> Java: Add command `BLMPOP`

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/object-freq/
> Python: add OBJECT FREQ command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/object-idletime/
> Python: add OBJECT IDLETIME command

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/module-info.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
Adds the [XLEN](https://valkey.io/commands/xlen/) command to Java
> Java: Add `XLEN` command

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
Adds the [XDEL](https://valkey.io/commands/xdel/) command for Java client
> Java: add `XDEL` command (#318)

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/object-refcount/
> Python: add OBJECT REFCOUNT command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/renamenx/
> Python: add RENAMENX command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/pfmerge/
> Python: add PFMERGE command

- CHANGELOG.md
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/lastsave/
> Python: add LASTSAVE command

- node/src/Commands.ts
- node/tests/RedisClientInternals.test.ts
- node/tests/SharedTests.ts
#1507 
The set command options are not functioning properly.
We found out about it thanks to @Ealenn open an issue.
In order to avoid the repetition of similar bugs, the PR incorporates a fix and a large quantity of tests.
> HOT-FIX: CRITICAL - fixed set command optional arguments and added tests to set command

- node/tests/SharedTests.ts
> All tests will no longer be skipped

- glide-core/src/client/reconnecting_connection.rs
- glide-core/src/client/standalone_client.rs
- glide-core/tests/test_standalone_client.rs
The standalone client receives a list of node addresses and tries to find the primary by getting the node's role from 'info replication'. In some cluster issues there might be more than a single primary so the client won't be able to identify which one is the legit primary, and therefore we should fail the client creation.
> Standalone Client: Raise an error if more than one primary node is found

- glide-core/src/client/mod.rs
- glide-core/src/client/value_conversion.rs
N/A
Small clean up to avoid logging sensitive user data - requests and responses.
https://github.com/Bit-Quill/glide-for-redis/actions/runs/9134317535/job/25119609032?pr=288#step:7:385
> Don't log sensitive user info in GLIDE code

- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
- java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
- java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/RedisClusterClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
N/A
**BEFORE**
```js
String functionLoad(String code);
String functionLoadReplace(String code);
```
**AFTER**
```js
String functionLoad(String code, bool replace);
```
> Java: Update implementation for `FUNCTION LOAD`.

- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
> fixed testing

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/__init__.py
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/command_args.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/sorted_set.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
We separated it into sort and sort_store.
In CME, two arguments (BY/GET) aren't supported, so we dicided to create separate APIs for CMD and CME so in CME those 2 two won't appear as optional.
> Python: Adds Sort command

- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
- java/client/src/main/java/glide/api/commands/GenericCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/Transaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/StandaloneTransactionTests.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
- java/integTest/src/test/java/glide/standalone/TransactionTests.java
> Java: Adding command `COPY`

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node: Add ZINTERSTORE command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
N/A
https://redis.io/docs/latest/commands/sunionstore/
- Stores the members of the union of all sets specified by the `keys` arg into a new set
at `destination`
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/sunionstore.json))
> Node: add SUNIONSTORE command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
N/A
https://valkey.io/commands/pfcount/
> Node: added PFCOUNT command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
N/A
https://valkey.io/commands/object-freq/
> Node: added OBJECT FREQ command

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
- Update `ZUNION`
- Change `String[] zunion(KeysOrWeightedKeys)` -> `String[] zunion(KeyArray)` (weights are noop without `WITHSCORES` modifier)
- Remove `String[] zunion(KeysOrWeightedKeys, Aggregate)`, because it is useless (`Aggregate` is noop without `WITHSCORES` modifier)
- Update `ZINTER`
- Change `String[] zinter(KeysOrWeightedKeys)` -> `String[] zinter(KeyArray)` (weights are noop without `WITHSCORES` modifier)
- Remove `String[] zinter(KeysOrWeightedKeys, Aggregate)`, because it is useless (`Aggregate` is noop without `WITHSCORES` modifier)
- Add `@since` to `ZINTER`, `ZUNION` and `ZDIFF`
- Update UT for `ZINTER`, `ZUNION`
- Update command IT `ZINTER`, `ZUNION` and `ZDIFF` to check version and match new signatures
- Update …
> Java: Update `ZUNION` and `ZINTER` and tests.

- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
Adds the [XREVRANGE](https://redis.io/docs/latest/commands/xrevrange/) command for Java. 
> Java: add `xrevrange` command

- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StringBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
> Java: Adding command MSetNX

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
N/A
https://valkey.io/commands/xlen/
- Returns the number of entries in the stream stored at the given key
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/xlen.json))
> Node: add XLEN command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
N/A
https://valkey.io/commands/zintercard/
- Returns the cardinality of the intersection of the sorted sets specified by the given keys.
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/zintercard.json)).
> Node: add ZINTERCARD command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Transaction.ts
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
N/A
Javascript follows camel-case for its variable naming convention. This PR updates the object command functions to follow camel-case.
> Change object command names to follow camel-case

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
N/A
https://redis.io/docs/latest/commands/object-idletime/
- Returns the time in seconds since the last access to the value stored at `key`.
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/object-idletime.json))
> Node: add OBJECT IDLETIME command

- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StringBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
* Java: Adding command LCS (default & LEN option)
This only covers the signature where LCS returns the LCS as a String and LCS length as a Long. Map return type with the IDX option is coming as a part II
`MINMATCHLEN` does not seem to work:
```
127.0.0.1:6379> set a1 abc
OK
127.0.0.1:6379> set a2 bcd
OK
127.0.0.1:6379> lcs a1 a2
"bc"
127.0.0.1:6379> lcs a1 a2 len
(integer) 2
127.0.0.1:6379> lcs a1 a2 MINMATCHLEN 3
"bc"
127.0.0.1:6379> lcs a1 a2 len MINMATCHLEN 3
(integer) 2
127.0.0.1:6379> lcs a1 a2 idx MINMATCHLEN 3
1) "matches"
2) (empty array)
3) "len"
4) (integer) 2
```
And as a reference https://github.com/valkey-io/valkey/pull/420 discusses how `WITHMATCHLEN` and `MINMATCHLEN` only works/makes sense with the `IDX` option but is …
> Java: Adding command `LCS` (No IDX option)

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
N/A
https://redis.io/docs/latest/commands/object-refcount/
- Returns the reference count of the object stored at `key`.
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/object-refcount.json))
> Node: add OBJECT REFCOUNT command

- java/client/build.gradle
With the release of [protobuf 27.1](https://github.com/protocolbuffers/protobuf/releases/tag/v27.1) we want to update our compilers to compile against the latest and greatest protobuf. 
> Java: Upgrade to protoc 27.1

- node/rust-client/src/lib.rs
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
This PR does the following:
- Any string value returning from Rust core, is kept in its binary form and is converted into `TypeScript` `Uint8Array` data structure
- Fixed all tests to work with binary strings (added various utilities like `checkSimple` and 2 conversion methods `intoString` and `intoArray`)
- Changed `set` API to accept `BulkString` (a union of `string | Uint8Array`)
> Node binding: keep strings as binary data

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/getbit/
- Returns the bit value at `offset` in the string value stored at `key`.
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/getbit.json))
> Python: add GETBIT command

- CHANGELOG.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/bitmap.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/bitcount/
- Counts the number of set bits (population counting) in the string stored at `key`
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/bitcount.json))
> Python: add BITCOUNT command

- glide-core/src/client/value_conversion.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/stream/StreamGroupOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
Adds the following commands: 
https://valkey.io/commands/xgroup-create/
https://valkey.io/commands/xgroup-destroy/
> Java: Add the `XGROUP CREATE` and `XGROUP DESTROY` commands 

- node/rust-client/src/lib.rs
Convert `VerbatimString` into binary safe string
> Node: convert `VerbatimString` into `Uint8Array`

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/sorted_set.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds GEOSEARCHSTORE command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds TOUCH command

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds SUNION command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: adds LSET command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: add GETRANGE command

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/ResponseFlags.java
- java/client/src/main/java/glide/api/commands/StringBaseCommands.java
- java/client/src/main/java/glide/ffi/resolvers/RedisValueResolver.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/src/lib.rs
As discussed, the first step before introducing `GlideString` is to revert PR https://github.com/aws/glide-for-redis/pull/1526 This commit does that
> Java: reverted byte[] overloading

- CHANGELOG.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/bitmap.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/bitop/
- Perform a bitwise operation between multiple keys (containing string values) and store the result in the `destination`.
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/bitop.json))
> Python: add BITOP command

- benchmarks/rust/src/main.rs
- csharp/lib/src/lib.rs
- glide-core/Cargo.toml
- glide-core/benches/connections_benchmark.rs
- glide-core/benches/memory_benchmark.rs
- glide-core/src/client/mod.rs
- glide-core/src/client/reconnecting_connection.rs
- glide-core/src/client/standalone_client.rs
- glide-core/src/client/types.rs
- glide-core/src/protobuf/connection_request.proto
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/protobuf/response.proto
- glide-core/src/request_type.rs
- glide-core/src/socket_listener.rs
- glide-core/tests/test_client.rs
- glide-core/tests/test_standalone_client.rs
- glide-core/tests/utilities/cluster.rs
- glide-core/tests/utilities/mod.rs
- go/src/lib.rs
- node/rust-client/src/lib.rs
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/config.py
- python/python/glide/redis_client.py
- python/python/tests/conftest.py
- python/python/tests/test_async_client.py
- python/src/lib.rs
- utils/cluster_manager.py
Works both in standalone and cluster modes. Pubsub configuration is provided in client creation params.
https://github.com/aws/glide-for-redis/issues/218
> Pubsub implementation in glide-core and with Python wrapper.

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
- java/client/src/main/java/glide/api/commands/TransactionsBaseCommands.java
- java/client/src/main/java/glide/api/commands/TransactionsClusterCommands.java
- java/client/src/main/java/glide/api/commands/TransactionsCommands.java
Comments in https://github.com/aws/glide-for-redis/pull/1539 weren't fully addressed. This PR makes unwatch consistent with other keyless commands where the apis are duplicated for cluster and standalone clients for documentation purposes.
> Separated unwatch to have different docs for standalone

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/bitpos/
- Returns the position of the first bit matching the given `bit` value.
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/bitpos.json))
> Python: add BITPOS command

- python/python/glide/__init__.py
- python/python/glide/async_commands/core.py
N/A
- some classes were missing from the \_\_all__ section of the \_\_init__.py file. This PR adds the missing classes.
- also fixed small error in the bitpos example documentation
> Python: add missing classes to __all__ section in __init__.py

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/__init__.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: Add command GetEX

- CHANGELOG.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/bitmap.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/bitfield/
- Reads or modifies the array of bits representing the string that is held at `key` based on the specified `subcommands`.
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/bitfield.json))
https://redis.io/docs/latest/commands/bitfield_ro/
- Reads the array of bits representing the string that is held at `key` based on the specified `subcommands`.
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/bitfield_ro.json))
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Python: add BITFIELD and BITFIELD_RO commands

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/zrevrank/
- Returns the rank of `member` in the sorted set stored at `key`, where scores are ordered from the highest to lowest, starting from `0`
- Policies: none (see [here](https://github.com/valkey-io/valkey/blob/26388270f197bce84817eea0a73d687d58442654/src/commands/zrevrank.json))
> Python: add ZREVRANK command

- glide-core/src/client/value_conversion.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/stream/StreamReadGroupOptions.java
- java/client/src/main/java/glide/api/models/commands/stream/StreamReadOptions.java
- java/client/src/main/java/glide/utils/ArrayTransformUtils.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
Adds the [XREADGROUP](https://valkey.io/commands/xreadgroup/) command to Java
> Java: Add the `XREADGROUP` command

- java/client/src/test/java/glide/api/RedisClientTest.java
> Fix stream add tests

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/xdel/
> Python: add XDEL command

- glide-core/src/protobuf/redis_request.proto
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StringBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/GetExOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/getex/
> Java: add `GETEX`

- CHANGELOG.md
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://valkey.io/commands/copy
> Python: add COPY Command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/xrevrange/
> Python: add XREVRANGE command

- CHANGELOG.md
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/xgroup-createconsumer/
https://redis.io/docs/latest/commands/xgroup-delconsumer/
> Python: add XGROUP CREATECONSUMER and XGROUP DELCONSUMER commands

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
- java/client/src/main/java/glide/api/models/commands/ExpireOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
GS version of ttl, pttl, expire, pexpire, expireAt, pexpireAt, expireTime, pexpireTime, exists
> GS version of ttl, pttl, expire, pexpire, expireAt, pexpireAt, expireTime, pexpireTime, exists

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java
- java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
support geodist, getbit, setbit and xack with GlideString
> support geodist, getbit, setbit and xack with GlideString

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
- java/client/src/main/java/glide/api/commands/GenericCommands.java
- java/client/src/main/java/glide/api/commands/HashBaseCommands.java
- java/client/src/main/java/glide/api/commands/ListBaseCommands.java
- java/client/src/main/java/glide/api/commands/SetBaseCommands.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
support lset, hexists, sismember and copy with GlideString
> support lset, hexists, sismember and copy with GlideString

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/SetBaseCommands.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
Add support of GlideString interface for sinter, sinterstore and sintercard commands for both standalone and cluster clients.
> Support of GlideString interface for sinter, sinterstore and sintercard commands

- CHANGELOG.md
- benchmarks/python/python_benchmark.py
- examples/python/client_example.py
- python/README.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/redis_modules/json.py
- python/python/glide/config.py
- python/python/glide/glide_client.py
- python/python/tests/conftest.py
- python/python/tests/test_async_client.py
- python/python/tests/test_pubsub.py
- python/python/tests/test_transaction.py
- python/python/tests/tests_redis_modules/test_json.py
- python/python/tests/utils/utils.py
> Python: Rename RedisClient, RedisClusterClient to GlideClient, GlideClusterClient

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/xgroup-setid/
> Python: add XGROUP SETID command

- .github/workflows/java-cd.yml
- java/client/build.gradle
- java/examples/build.gradle
Workflow will only trigger when a tag is pushed to the repo
Version is extracted from the tag and replaced in the build.grade files
reverted changes of java.yml file
> Extracting Java Deployment to a different workflow

- CHANGELOG.md
- glide-core/src/client/standalone_client.rs
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
- adds the RANDOMKEY command to the Python client
- also updates the redis-rs submodule to include fix to a bug where calling RANDOMKEY against a clustered Redis instance with no keys raised a ResponseError instead of returning None
- updates ResponsePolicy::OneSucceededNonEmpty to ResponsePolicy::FirstSucceededNonEmptyOrAllEmpty in standalone_client.rs to get the Rust code building successfully since this was renamed in redis-rs 
> Python: add RANDOMKEY command

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/SortOrder.java
- java/client/src/main/java/glide/api/models/commands/geospatial/GeoSearchOptions.java
- java/client/src/main/java/glide/api/models/commands/geospatial/GeoSearchOrigin.java
- java/client/src/main/java/glide/api/models/commands/geospatial/GeoSearchResultOptions.java
- java/client/src/main/java/glide/api/models/commands/geospatial/GeoSearchShape.java
- java/client/src/main/java/glide/api/models/commands/geospatial/GeoSearchStoreOptions.java
- java/client/src/main/java/glide/api/models/commands/geospatial/GeoUnit.java
- java/client/src/main/java/glide/api/models/commands/geospatial/GeospatialData.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
* Java: Add Command GeoSearch & GeoSearchStore 
> Java: Add Command GeoSearch & GeoSearchStore

- java/integTest/src/test/java/glide/SharedCommandTests.java
- python/python/tests/test_async_client.py
https://github.com/aws/glide-for-redis/issues/1715
Add sleep for two seconds to ensure that the idle_time is at least 1 for tests. 
> #1715: fix flakey test in xpending

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/SetBaseCommands.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
Support GlideString for sdiff commands
> Support GlideString for sdiff commands

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/stream/StreamGroupOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
Add support for the XGROUP SETID command.
This is a port of #1683 for Java.
> Java: Add XGROUP SETID command

- README.md
added Java's README.md to the Getting Started Section
> Java: update README directory to include Java's README.md

- CHANGELOG.md
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
> Python: command WAIT

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/xautoclaim/
> Python: added XAUTOCLAIM command

- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
- python/python/glide/config.py
- python/python/glide/glide_client.py
- python/python/tests/test_pubsub.py
- python/python/tests/test_transaction.py
1. Add publish apis to ClusterTransaction and Transaction.
3. Reverted StandaloneCommands.publish() to return int since it was not a good idea to diverge from the protocol.
3. Improved docs.
4. Updated tests.
5. Added handling of the missing unsubscriptions notifications.
*Issue*
https://github.com/aws/glide-for-redis/issues/1689
> Make (s)publish commands available in transactions

- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
*Issue #, if available:* N/A
A number of the docstrings for python functions are using an old URL pattern which currently results in 404 errors. Updating URLs to new pattern.
> Python: Update docstring links

- CHANGELOG.md
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
- python/python/glide/constants.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
- python/python/tests/utils/utils.py
*Issue #, if available:* N/A
https://redis.io/docs/latest/commands/function-list/
This is based off of the Java implementation from https://github.com/aws/glide-for-redis/pull/1452
> Python: Add `FUNCTION LIST` command.

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/transaction.py
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/xinfo-groups/
https://redis.io/docs/latest/commands/xinfo-consumers/
> Python: add XINFO GROUPS and XINFO CONSUMERS commands

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/HashBaseCommands.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- added hrandfield functions that can recieve GlideString arguments to BaseClient
- included the new override functions in the HashBaseCommands interface 
- added tests to the SharedCommandTests that receive byte types  
> added hrandfield binary functions

- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/redis_modules/json.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/glide/async_commands/transaction.py
> Python: replace all commands links to valkey

- CHANGELOG.md
- glide-core/src/protobuf/redis_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/commands/GenericCommands.java
- java/client/src/main/java/glide/api/models/Transaction.java
- java/client/src/main/java/glide/api/models/commands/scan/ScanOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/StandaloneTransactionTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
- java/integTest/src/test/java/glide/standalone/TransactionTests.java
Add the [SCAN](https://valkey.io/commands/scan/) command for Java (standalone instance)
> Java: Add SCAN command for standalone

- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/stream.py
- python/python/tests/test_async_client.py
> Python: type migration for entries_read

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/commands/stream/StreamGroupOptions.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
> Java: type migration for entries_read

- .github/workflows/java.yml
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/RedisClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
- java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
- java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/RedisClusterClientTest.java
- java/integTest/src/test/java/glide/TestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
Add function list binary output support
1. Add new API to get pattern as GlideString
2. Add new function handleFunctionListResponseBinary to handle binary output
3. Add new test utility to validate binary output
Note: there is a bug where the flags set always return as string. for now I fix the assert of the set with my own assert assertSetsEqual that convert to GlideString.
> Add function list binary output support

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StringBaseCommands.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
> support lcs with GlideString

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://valkey.io/commands/xinfo-groups/
https://valkey.io/commands/xinfo-consumers/
> Java: Add `XINFO GROUPS` and `XINFO CONSUMERS` commands

- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/RedisClusterClient.java
- java/client/src/main/java/glide/api/commands/PubSubBaseCommands.java
- java/client/src/main/java/glide/api/commands/PubSubClusterCommands.java
- java/client/src/main/java/glide/api/logging/Logger.java
- java/client/src/main/java/glide/api/models/BaseTransaction.java
- java/client/src/main/java/glide/api/models/ClusterTransaction.java
- java/client/src/main/java/glide/api/models/GlideString.java
- java/client/src/main/java/glide/api/models/PubSubMessage.java
- java/client/src/main/java/glide/api/models/configuration/BaseSubscriptionConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/ClusterSubscriptionConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/StandaloneSubscriptionConfiguration.java
- java/client/src/main/java/glide/connectors/handlers/CallbackDispatcher.java
- java/client/src/main/java/glide/connectors/handlers/MessageHandler.java
- java/client/src/main/java/glide/connectors/handlers/ReadHandler.java
- java/client/src/main/java/glide/ffi/resolvers/RedisValueResolver.java
- java/client/src/main/java/glide/managers/ConnectionManager.java
- java/client/src/test/java/glide/api/RedisClientTest.java
- java/client/src/test/java/glide/api/RedisClusterClientTest.java
- java/client/src/test/java/glide/api/models/ClusterTransactionTests.java
- java/client/src/test/java/glide/api/models/TransactionTests.java
- java/client/src/test/java/glide/managers/ConnectionManagerTest.java
- java/integTest/build.gradle
- java/integTest/src/test/java/glide/PubSubTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
Address some of the comments in #1662 about aligning with Python:
- Remove spublish() and provide a cluster-only publish() overload that takes a boolean.
- Match argument order for publish() with Python.
- Add missing integration tests.
- Undo splitting of integration tests.
> Java: Address pubsub PR comments

- python/python/tests/test_transaction.py
Resolve merge collision from #1796 and #1816 and #1814
> Python: fix mypy

- java/client/src/test/java/glide/ffi/FfiTest.java
N/A
Fix compiler warning/error about non-ASCII characters in FfiTest.java
> Java: Remove use of non-ASCII characters in String literal in FfiTest

- java/integTest/src/test/java/glide/LoggerTests.java
N/A
This change moves assertions to the end of log_to_file and also initializes a new logger to try and close existing files.
I also tested by running it 100 times using @RepeatedTest to make sure it wasn't still failing with the changes.
> Java: Try to fix log_to_file test flakiness

- python/python/glide/async_commands/transaction.py
> Python: fix transaction publish documentation and typing

- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
- Enabled `workflow_dispatch` for manually triggering a specific workflow without affecting all package managers. Note that it does not automatically push a release tag to GitHub. This feature is primarily for testing purposes; for production releases, trigger the workflow by pushing a release tag or you may need to manually add a release tag afterward.
- Resolved PyPI CD to handle release candidate versions correctly.
> Added a workflow_dispatch to CD workflows

- .github/workflows/python.yml
- glide-core/src/socket_listener.rs
- python/pytest.ini
- python/pytest_pubsub.ini
- python/python/glide/glide_client.py
- python/python/tests/test_pubsub.py
1. Enabled all tests on macos latest with all engine versions.
2. Changed pubsub tests to be run in separate task.
3. Fixed uds message parsing in glide-core.
4. Refactored pubsub tests
> Full tests on macos

- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/src/lib.rs
- Java: always return `byte[]` if `encoding_utf8` is `false` for the following types: `BulkString`, `SimpleString` & `VerbatimString`
- Java: re-enabled `xclaim` binary tests
> Java: re-enabled `xclaim` binary tests

- .github/json_matrices/build-matrix.json
- .github/workflows/csharp.yml
- .github/workflows/go.yml
- .github/workflows/java-cd.yml
- .github/workflows/java.yml
- .github/workflows/node.yml
- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
- .github/workflows/python.yml
- .github/workflows/rust.yml
We used macos-13-xlarge as at that time it was the only github runner for macos on arm64. Now, the macos-latest runner already runs on arm64, so we don't need to use the xl anymore.
Resolves this error:
> The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.
 
> Changed MacOS 13 runner to a normal-sized runner

- .github/workflows/go.yml
- .github/workflows/java-cd.yml
- .github/workflows/java.yml
- .github/workflows/npm-cd.yml
- .github/workflows/ort.yml
- .github/workflows/pypi-cd.yml
Fix CI for all clients + update CD for java
Clones #1868 from a local branch - expecting GHA to find secrets and run
> Fix CI after repo move.

- java/README.md
* Fixed link to glide-core
* Fixed links to unit and integ tests
> Fix links in java README.md

- .github/workflows/go.yml
- .github/workflows/java-cd.yml
- .github/workflows/java.yml
- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
1. Until now, we always checked the repo owner using  `github.repository_owner` which is always equal to valkey-io (upstream owner name) 
But we want to check the pr's branch repo owner, and this is done using `${{ github.event.pull_request.head.repo.owner.login }}`
2. Removed the check of repo owner from amazonlinux CI on java and go workflows
> Fix the way we check repo owner on cd workflows

- java/DEVELOPER.md
- java/client/build.gradle
Replaces obsolete references to `glide-for-redis` with `valkey-glide`.
> Java: Updates `glide-for-redis` references

- java/.gitignore
The VSCode Extension Pack for Java is widely used and includes a Test Runner for Java extension that automatically creates `bin` folders and `junit-platform.properties` files. These files should not be committed. This change adds a `bin/` pattern to the `./java/.gitignore` file to ignore any files automatically created by the extension.
> Ignores VSCode-created `bin` directories (#402)

- .github/workflows/java-cd.yml
- java/client/build.gradle
Unfortunately, commit [036994de296c45](https://github.com/valkey-io/valkey-glide/commit/036994de296c45) was lost from `v1.0` branch and java release artifacts got generated with the wrong version.
* Fixing java artifact version
* Adding mac runners to CD workflow
> Fix release version for java client.

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
https://valkey.io/commands/sunion/
> Node: add SUNION command

- .github/workflows/rust.yml
Add missing GH token to avoid `rate exceeded` error for non authenticated requests
https://github.com/aws/glide-for-redis/actions/runs/9227667494/job/25390082670?pr=1460
```
Prepare all required actions
Getting action download info
Run ./.github/workflows/lint-rust
Run actions/checkout@v4
Syncing repository: aws/glide-for-redis
...
...
Run arduino/setup-protoc@v3
Error: Error: API rate limit exceeded for 20.161.76.225. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
> Fix rust linter CI.

- java/DEVELOPER.md
Revises the `DEVELOPER.md` file to improve clarity and reduce the potential for confusion. The order of some sections has been changed to help ensure the correct dependencies have been installed before attempting to install the protobuf compiler. A forward reference to the `Troubleshooting` section has been added to assist readers in finding solutions to some common installation problems.
> Java: Revises `DEVELOPER.md` file. (#403)

- node/DEVELOPER.md
Following the current documentation for installing ESLint gives users this error:
```
Oops! Something went wrong! :(
ESLint: 8.57.0
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
```
This change adjusts the documentation so that users can avoid this error and install ESLint correctly.
> Node: Fix issue with ESLint installation documentation

- .github/workflows/java-cd.yml
- .github/workflows/java.yml
- java/client/build.gradle
- java/examples/build.gradle
> [Backport] #1922 to 1.0 branch

- .github/workflows/csharp.yml
- .github/workflows/go.yml
- .github/workflows/java.yml
- .github/workflows/node.yml
- .github/workflows/python.yml
- .github/workflows/rust.yml
With the given change a developer can start CI job on any branch without creating a PR nor patching CI workflow.
This adds a button on **Actions** tab on those CI jobs to run it manually on a selected branch.
> Allow developers to run CI on demand

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
https://valkey.io/commands/zdiff/
> Node: add ZDIFF command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
https://valkey.io/commands/setbit/
> Node: add SETBIT command

- java/.ort.yml
Fixes #1971 by removing unnecessary spotbugs from the attribution files
> Fixed Java ORT not to include irrelevant dependencies

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
https://valkey.io/commands/getbit/
> Node: add GETBIT command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
The bug in the ZADD implementation does not allow for users to call `zadd` with only the `changed` parameter. This PR will allow for `zadd("key", { one: 1, two: 2 }, { changed: true });` to be supported.
> Node: fix ZADD bug

- CHANGELOG.md
- java/client/src/main/java/glide/api/BaseClient.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
[XRange](https://valkey.io/commands/xrange/) and [XRevRange](https://valkey.io/commands/xrevrange/) will thrown an error when count is less than or equal to zero:
```
GlideException: Unexpected return type from Glide: got null expected Map
```
> Java: `XRange`/`XRevRange` should return `null` instead of `GlideException` when given a negative count

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/GlideClusterClient.ts
- node/src/Transaction.ts
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/TestUtilities.ts
https://valkey.io/commands/fcall/
> Node: added FCALL and FCALL_RO commands

- .github/workflows/node.yml
due to failure https://github.com/valkey-io/valkey-glide/actions/runs/10076781196/job/27857892422
> Node: increase ubuntu wokflow run time

- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/TestUtilities.ts
Make failure of transaction IT readable. Also fix checking numbers in the transaction response (they were just ignored).
Failure before: https://github.com/valkey-io/valkey-glide/actions/runs/10069186874/job/27835788398?pr=2007#step:5:25100
```
● GlideClient › can send transactions_1
expect(received).toEqual(expected) // deep equality
Expected: "OKOKOKOK0.00OKbarOKembstrstring03184ec2-47a1-4617-9415-a9122ed3610cnullbarbazOKbarbaz3.001.001.001.0003184ec2-47a1-4617-9415-a9122ed3610c03184ec2-47a1-4617-9415-a9122ed3610c1367dc0b-fa35-4902-8e8a-ac9cb4b05b8b03184ec2-47a1-4617-9415-a9122ed3610c1.00null4.001367dc0b-fa35-4902-8e8a-ac9cb4b05b8b43.001.00OKOK1367dc0b-fa35-4902-8e8a-ac9cb4b05b8b31367dc0b-fa35-4902-8e8a-ac9cb4b05b8b21367dc0b-fa35-4902-8e8a-ac9cb4b05b8b31367dc0b-fa35-4902-8e8a-ac9cb4b05b8 …
```
> Node: Rework transaction IT.

- glide-core/Cargo.toml
- glide-core/tests/utilities/mod.rs
- java/Cargo.toml
Yesterday new version of rust was released (1.80) which switches `unexpected_cfgs` lint to `warn` mode by default.
Even without rust code changes, CI started to fail:
https://github.com/valkey-io/valkey-glide/actions/runs/10098572063/job/27925904384?pr=2007
<details>
<summary>Error message</summary>
```
error: unexpected `cfg` condition name: `ffi_test`
--> src/lib.rs:28:7
|
28 | #[cfg(ffi_test)]
|       ^^^^^^^^
|
= help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, …
```
> Add rust lint config for unknown cfgs.

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
https://valkey.io/commands/bzmpop/
> Node: add `BZMPOP` command

- java/README.md
This updates all current documentation to not use hard-coded versions of 1.0.0/1.0.1 for valkey-glide, which should help us avoid needing to update our documentation so frequently.
> Update documentation to use valkey-glide version 1.x.x

- glide-core/Cargo.toml
- glide-core/src/client/standalone_client.rs
- glide-core/tests/test_standalone_client.rs
- logger_core/Cargo.toml
[Fixes for rust 1.80.0](https://github.com/valkey-io/valkey-glide/commit/102775283dc6601cb98b0aa871558877b944d807):
Including: 
- Removed default features from tracing-appender that has `time` dependency hardcoded with old version, causing to this build error: https://github.com/rust-lang/rust/issues/127343#issuecomment-2218261296
- Lint: Fixed unexpected config for the standalone_heartbeat feature https://doc.rust-lang.org/beta/nightly-rustc/rustc_lint/builtin/static.UNEXPECTED_CFGS.html
[Merge from upstream redis-rs](https://github.com/valkey-io/valkey-glide/commit/d58129dd04be8a3e2019b14ba4330d74d340e569):
Including: 
- Removed IP constrains
- Changed non-key based commands not to be routed to a random node
- Rust 1.80.0 linter fixes
> Merge from redis-rs and fixes for rust 1.80.0 

- node/jest.config.js
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/TestUtilities.ts
- utils/TestUtils.ts
Rework changes introduced in #1993:
- use `exec` in an async function to ensure that default value isn't used
- fix the version check condigion
- increase timeouts
> Node: Fix version check - again.

- node/rust-client/src/lib.rs
- node/src/BaseClient.ts
- node/tests/RedisClient.test.ts
- node/tests/RedisClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
Reference PR: https://github.com/valkey-io/valkey-glide/pull/1953
- BaseClient is hardcoded to use the stringDecoder.
- `checkSimple` calls in SharedTests.ts.
- One test is failing and marked as TODO as it needs to be discussed. The test is `bitop test`.
> Node: add minimal binary support

- node/src/BaseClient.ts
- node/tests/PubSub.test.ts
- node/tests/RedisClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
* Fix issue caused by merging #2047 and #2026/#2046 w/o rebase
* Fix pubsub IT to work with already existing clusters
* Removed `Buffer`, `checkSimple` and `intoString` references from tests
* Fix transaction IT response validation to use deep comparison and reporting (#2010)
> Node: Fix tests.

- .github/workflows/lint-ts.yml
- node/npm/glide/index.ts
- node/tests/AsyncClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
1. `eslint` probably got new update and started producing new errors, which we never seen before ([CI run](https://github.com/valkey-io/valkey-glide/actions/runs/10185991412/job/28176763111?pr=2057))
2. Update lint CI to allow running in demand according to #1967 
```
/home/runner/work/valkey-glide/valkey-glide/node/npm/glide/index.ts
20:45  error  A `require()` style import is forbidden  @typescript-eslint/no-require-imports
23:45  error  A `require()` style import is forbidden  @typescript-eslint/no-require-imports
26:45  error  A `require()` style import is forbidden  @typescript-eslint/no-require-imports
33:45  error  A `require()` style import is forbidden  @typescript-eslint/no-require-imports
36:45  error  A `require()` style import is forbidden …
```
> Node: fix lints

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
https://valkey.io/commands/xdel/
> Node: Added `XDEL` command

- .github/workflows/lint-rust/action.yml
This should fix the lint-rust CI workflow.  This is the second time this has happened.  I added `--locked` because we did not do this last time and it is the recommended option by the maintainers of `cargo-deny`: https://github.com/EmbarkStudios/cargo-deny/issues/641#issuecomment-2016478168
> Downgrade and fix cargo-deny version

- python/python/glide/__init__.py
`get_pubsub_message` returns a `PubSubMsg`. Therefore, we should export this class so users can use it, for instance for typing purposes.
> Python: Export PubSubMsg

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
https://valkey.io/commands/append/
> Node: added APPEND command

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
- node/tests/GlideClusterClient.test.ts
Commands that return `Promise<>` should include the `async` label, to indicate that users can `await` on those commands.
> Node: Add async to commands

- glide-core/src/client/mod.rs
Cluster mode: ATM we're using redis-rs default retries which is 16, which is A LOT and with exponential backoff between retries it takes more than 15 seconds to finish all retries. In glide we're wrapping the command execution futures with timeout so we'll drop the future after the given timeout and response back to the user with timeout error. However, once request is added to redis-rs's pending requests queue, it won't stop to run it until the retries are exceeded. That means that we can see old requests being sent long long after we've responded with timeout error back to the user.
We shall provide a solid fix where dropped requests/timed out requests will be dropped also in redis-rs. 
This PR introduce only a fix to minimze the delta between glide's timeout to the actual completion of …
> Core/Cluster mode: Added default retries to the cluster client builder

- node/src/BaseClient.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
- node/src/Transaction.ts
Updates javadoc on all node commands to use `@see` and `@remarks` to help document links and remarks. 
Example - see and remarks can be grouped together: 
```
* @see {@link https://valkey.io/commands/mget/|valkey.io} for details.
* @remarks When in cluster mode, the command may route to multiple nodes when `keys` map to different hash slots.
```
multiple remarks - also the "Since" comment is updated to a `@remark` to format it correctly:
```
* @see {@link https://valkey.io/commands/blmove/|valkey.io} for details.
* @remarks When in cluster mode, both `source` and `destination` must map to the same hash slot.
* @remarks `BLMOVE` is a client blocking command, see {@link https://github.com/valkey-io/valkey-glide/wiki/General-Concepts#blocking-commands|Valkey Glide Wiki} for more details and …
```
> Node: Clean `since` tags in command documentation

- .github/workflows/install-shared-dependencies/action.yml
This fixes the following error ([example](https://github.com/valkey-io/valkey-glide/actions/runs/10373323035/job/28718163220?pr=2114#step:7:538)):
```
Warning: Failed to restore: Unable to locate executable file: tar. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
> CI: fix amazon linux job

- CHANGELOG.md
- node/.prettierignore
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
replaces: https://github.com/valkey-io/valkey-glide/pull/1499
> Node: add `hkeys` command

- node/src/Transaction.ts
Added binary support to these transaction commands, for which the binary option was already merged - 
*append
*getrange
*hget
*mget
*hvals
*lpush
*lpop
*lpopcount
*lrange
*lindex
*lmove
*blmove
*linsert
*llen
*rpush
*rpop
*rpopcount
*blpop
*brpop
> Node - Add binary support to transaction commands

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
commands updated:
- bitop
- getbit
- setbit
- bitpos/bitposInterval
- bitfield
- bitfield_ro
- bitcount
> Node: Add binary api for bitmap commands

- node/src/BaseClient.ts
- node/tests/GlideClient.test.ts
- node/tests/GlideClusterClient.test.ts
- node/tests/TestUtilities.ts
Issue description - https://github.com/valkey-io/valkey-glide/issues/2119 
Warping the valueFromSplitPointer rust function with try-cache and adding tests
> Node: warp with try-catch the rust call and tests

- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
PR to add node Binary api code changes for the following commands:
1. **blmpop** (https://valkey.io/commands/blmpop/)
2. **lrem** (https://valkey.io/commands/lrem/)
3. **lset** (https://valkey.io/commands/lset/)
4. **ltrim** (https://valkey.io/commands/ltrim/)
5. **rpushx** (https://valkey.io/commands/rpushx/)
> Node binary api: blmpop, lrem, lset, ltrim and rpushx  commands updated for binary command inputs

- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
Binary support added to commands - 
`SCARD`
`SMOVE`
`SISMEMBER`
`SMISMEMBER`
`SRANDMEMBER`
`SRANDMEMBERCOUNT`
> Node: Add binary support to scard smove sismember srandmember

- .github/workflows/go.yml
- go/Makefile
- go/api/base_client.go
- go/go.mod
- go/src/lib.rs
- Use the go string internal pointer in Rust code
- Do not copy go string pointers when building Redis command in lib.rs
- Added an option to build the client in debug mode (`make build-debug`)
- Added Makefile target `clean`
- Added Makefile target `build-debug`
- Running `make build` should also build the benchmark app
This PR improves performance of GO client by roughly `~35%`
Go expert: please review :)
> GO: performance improvement

- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
- node/src/Transaction.ts
- node/tests/PubSub.test.ts
PubSub (part 1):
`Publish`
`SPublish`
`PUBSUB CHANNELS`
`PUBSUB SHARDCHANNELS`
`PUBSUB NUMPAT` - No change required
For the remaining PubSub commands,`Record< >` are used. They will be handled in the next PR.
> Node: add binary support for PubSub commands, part 1

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
commands included:
- SET 
- INCR
- INCRBY
- INCRBYFLOAT
- DECR 
- DECRBY
- GETEX 
- LCS
> Node: add binary support to string commands

- go/api/base_client.go
- go/api/commands.go
- go/api/response_handlers.go
- go/integTest/shared_commands_test.go
- go/src/lib.rs
- go/utils/transform_utils.go
Implementing the following 5 string commands:
- Incr
- IncrBy
- IncrByFloat
- Decr
- DecrBy
> Go: Implement incr and decr commands

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
Commands included:
- `XINFO CONSUMERS`
- `XINFO STREAM`
- `XLEN`
- `XPENDING`
- `XRANGE`
- `XREAD`
- `XREADGROUP`
- `XREVRANGE`
- `XTRIM`
> Node: Add Binary support for stream commands, part 2

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/GlideClusterClient.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
* `ZAdd`
* `ZAddIncr`
* `ZLexCount`
* `ZMPop`
* `ZMScore`
* `ZPopMax`
* `ZPopMin`
* `ZRandMember` / `ZRandmemberWithCount` / `ZRandmemberWithCountWithScores`
* `ZRange` / `ZRangeWithScores`
* `ZRangeStore`
* `ZRank` / `ZRankWithScore`
* `ZRem`
* `ZRemRangeByLex`
* `ZRemRangeByRank`
* `ZRemRangeByScore`
* `ZRevRank` / `ZRevrankWithScore`
* `ZScan`
* `ZScore`
* `ZUnion` / `ZUnionWithScores`
* `ZUnionStore`
Notes:
* `ZADD` supports two types of input arguments for better compatibility and UX
* Some commands updated in this PR return `Record<string, ...>` - this remains unchanged and will be fixed in scope of #2207. Even though I added decoder option to these commands, I can't test them with binary decoder yet.
> Node: Add binary variant to sorted set commands - part 2.

- .github/workflows/rust.yml
- deny.toml
- glide-core/tests/utilities/mod.rs
- We are ignoring the error
```
proc-macro-error 1.0.4 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
```
for now as it is in nested dependencies and requires more discussion.
Reference: https://rustsec.org/advisories/RUSTSEC-2024-0370.html
- Fixed the lint error 
```
error: the borrowed expression implements the required traits
--> tests/utilities/mod.rs:361:18
|
361 |             .arg(&format!("{size}"))
|                  ^^^^^^^^^^^^^^^^^^ help: change this to: `format!("{size}")`
```
> Ignore proc-macro-error lint failure

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
> Node: Add binary support for HSCAN

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
- node/tests/GlideClient.test.ts
- node/tests/GlideClientInternals.test.ts
- node/tests/GlideClusterClient.test.ts
- node/tests/SharedTests.ts
Change log:
1. Updated decoder to DecoderOption, router to RouterOption in GlideClient.ts, GlideClusterClient.ts and BaseClient.ts.
2. Update test cases based on the changes in point 1.
3. Moved toProtobufRoute to BaseClient.
In BaseClient.ts, replaced decoder with decoderOption for the following commands:
1. get (https://valkey.io/commands/get/)
2. getdel(https://valkey.io/commands/getdel/)
4. getrange (https://valkey.io/commands/getrange/)
5. mget (https://valkey.io/commands/mget/)
6. lpop (https://valkey.io/commands/lpop/)
7. lpopCount (https://valkey.io/commands/lpopCount/)
8. lrange (https://valkey.io/commands/lrange/)
9. lmove (https://valkey.io/commands/lmove/)
10. blmove (https://valkey.io/commands/blmove/)
11. rpop (https://valkey.io/commands/rpop/)
12. rpopCount …
> Node: replace `decoder` by `DecoderOption` and `route` by `RouteOption` in API

- .github/json_matrices/build-matrix.json
- .github/workflows/java-cd.yml
- CHANGELOG.md
- java/benchmarks/build.gradle
- java/build.gradle
Completes: https://github.com/valkey-io/valkey-glide/issues/2000 and https://github.com/valkey-io/valkey-glide/issues/2040
The Maven Release can be triggered by creating a release tag on GitHub or manually running the Java Prepare Deployment workflow. Once the workflow is running, a member of AWS_ACTIONS will be required to approve twice:
1. To publish the deployment, and 
2. To publish the release on Maven Central.
Create a release with tag v*.*.* (e.g. `v1.2.0`, or `v1.3.0-rc2` for a release candidate) which will determine the version of the release. 
Manually run the workflow by going to https://github.com/valkey-io/valkey-glide/actions/workflows/java-cd.yml and specifying the version and checking the box for publishing.
If the last job for publishing the release to Maven Central …
> Java: Update workflow to zip bundle files and use build-matrix.json

- .github/codeql/codeql-config.yml
- .github/workflows/codeql.yml
This CodeQL configuration is primarily a default configuration generated by github, which enabled security check for all languages, including Java-Kotlin, python, node-js, go and c#. The only change made is to exclude the `examples` directory for CodeQL through an external configuration file `.github/codeql/codeql-config.yml`.
> add CodeQL configuration

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- glide-core/src/protobuf/command_request.proto
- glide-core/src/request_type.rs
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/core.py
- python/python/glide/async_commands/standalone_commands.py
- python/python/tests/test_async_client.py
- python/python/tests/utils/utils.py
Inheriting the changes from PR: https://github.com/valkey-io/valkey-glide/pull/2094 & addressing existing comments
putting transactions out of scope for this PR since script_invocation and script_invocation_pointers seem to be parallel with transactions and more investigation might be needed for the implementation of invoke_script.
> Python: Add Script commands

- CHANGELOG.md
- eslint.config.mjs
- node/.prettierignore
- node/DEVELOPER.md
- node/package.json
- package.json
Address unresolved issues in #2263
Now `npm run lint` will run both linters, `npm run lint:fix` will try to apply fixes from both as well
> Node: Fix linter config.

- CHANGELOG.md
- java/client/src/main/java/glide/utils/ArrayTransformUtils.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
Fixes a bug that incorrectly converts non UTF-8 bytes GlideString to String with the value `"Value not convertible to string: byte[] "` instead of throwing an exception.
convertMapToKeyValueGlideStringArray:
- `public CompletableFuture<String> msetBinary(@NonNull Map<GlideString, GlideString> keyValueMap)`
- `public CompletableFuture<Long> hset(
@NonNull GlideString key, @NonNull Map<GlideString, GlideString> fieldValueMap)`
- `public CompletableFuture<GlideString> xadd(
@NonNull GlideString key,
@NonNull Map<GlideString, GlideString> values,
@NonNull StreamAddOptionsBinary options)`
- `public CompletableFuture<Boolean> msetnxBinary(
@NonNull Map<GlideString, GlideString> keyValueMap)`
convertNestedArrayToKeyValueGlideStringArray:
- `public CompletableFuture<GlideString> xadd(
@NonNull …
> Java: Fix byte GlideString conversion to String bug

- CHANGELOG.md
- java/client/src/main/java/glide/api/GlideClusterClient.java
- java/client/src/main/java/glide/api/commands/PubSubClusterCommands.java
- java/client/src/main/java/glide/api/models/ClusterTransaction.java
- java/client/src/test/java/glide/api/GlideClusterClientTest.java
- java/client/src/test/java/glide/api/models/ClusterTransactionTests.java
- java/integTest/src/test/java/glide/PubSubTests.java
Implemented PUBSUB SHARDCHANNELS command in Java.
> Java: Add PUBSUB SHARDCHANNELS command

- glide-core/src/protobuf/command_request.proto
- glide-core/src/request_type.rs
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
- java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsBaseCommands.java
- java/client/src/test/java/glide/api/GlideClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/GlideClusterClient.ts
- node/tests/SharedTests.ts
- python/python/glide/async_commands/core.py
- python/python/tests/test_async_client.py
TODO:
- add default routing to random node
- add to is_readonly_cmd
> Add SCRIPT SHOW command

- glide-core/Cargo.toml
- glide-core/benches/connections_benchmark.rs
- glide-core/src/client/mod.rs
- glide-core/src/client/reconnecting_connection.rs
- glide-core/src/client/standalone_client.rs
- glide-core/tests/test_client.rs
- glide-core/tests/test_socket_listener.rs
- glide-core/tests/test_standalone_client.rs
- glide-core/tests/utilities/mod.rs
- node/rust-client/src/lib.rs
Maintaining a continuous connection to the server(s) is crucial, especially in PubSub contexts, where undetected disconnects can render the listener inoperable.
Additionally, immediately attempting to reestablish a closed connection reduces latency for the next command.
This functionality is implemented differently for standalone and cluster modes:
- In standalone mode, it utilizes the reconnect functionality, triggered immediately upon detecting a disconnect, without waiting for the next command.
- In cluster mode, it relies on the changes introduced in https://github.com/amazon-contributing/redis-rs/commit/2c7faec028d3ab4a751c309f6af9d6c706e79864.
The validation processes are lightweight in terms of performance and run every 3 seconds.
> Integrate passive disconnect handling and automatic reconnect functionality

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- java/client/src/main/java/glide/utils/ArrayTransformUtils.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
Expands on testing for https://github.com/valkey-io/valkey-glide/pull/2271.
Tests were included for stream, sorted set, list,  and geospatial data types.
Also specified `?` type to `double` for `convertMapToValueKeyStringArray`'s parameter. This function affects 
```
CompletableFuture<Long> zadd(
@NonNull String key,
@NonNull Map<String, Double> membersScoresMap,
@NonNull ZAddOptions options,
boolean changed)
```
> Java: Expanded tests for converting non UTF-8 bytes to Strings

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
- node/src/Transaction.ts
- node/tests/GlideClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
1. Use `options` struct for all optional args for all commands
2. Fix arg types for some stream commands
Purpose of this change:
1. To align all API, especially across standalone and cluster clients and transaction
2. If we don't release it in 1.1, that will be a breaking change
3. Adding new optional argument won't be a breaking change for existing API
> Node: Use `options` for options.

- node/package.json
Not needed packages.
Plus — are part of general dependencies for no reason.
> remove packges not in use

- go/benchmarks/benchmarking.go
- go/src/lib.rs
- The latency numbers for `get_existing` were off because initially it was not always fetching the existing keys. This PR fixes the same.
- For the response side optimisation, copying of `Value` received from server to `Rust vec` is avoided and the pointer is passed directly to Go.
Benchmarking command:
```
go run . -resultsFile gobenchmarks.json -dataSize "100 1000 10000" -concurrentTasks "10" -clients all -host localhost -port 6379 -clientCount "1"
```
> Go:Fix benchmarking code and improve response side performance

- CHANGELOG.md
- python/pyproject.toml
- python/requirements.txt
Let me prefix that one by saying that I haven't been testing it extensively, it just seems to be working as expected.
This PR would fix https://github.com/valkey-io/valkey-glide/issues/2298. Can you just trigger the test suite and see what happens? They seem to be passing fine there: https://github.com/Rafiot/valkey-glide/actions/runs/10905533315
> Replace google-api-python-client by protobuf

- CHANGELOG.md
- examples/node/index.ts
- examples/node/package.json
- node/npm/glide/index.ts
- node/src/Logger.ts
Fixed missing exports:
- `Script`
- `ObjectType`
- `ClusterScanCursor`
- `BaseClientConfiguration`
- `GlideClusterClientConfiguration`
- `LevelOptions`
This PR will resolve issue https://github.com/valkey-io/valkey-glide/issues/2307
> Node: Fixed missing exports

- go/api/response_handlers.go
- go/src/lib.rs
Initially the code was handling Array of Strings. With this change, Rust code will support all kinds of arrays.
> Go: Handling generic arrays instead of only string arrays

- .github/json_matrices/engine-matrix.json
- node/tests/PubSub.test.ts
Required by #2296
Removing standalone client from a test which checks `numsub` and `shardnumsub` together, because shard commands available on cluster only. Those commands are checked in other tests.
fixes: https://github.com/valkey-io/valkey-glide/issues/2327
> Node: fix pubsub IT

- .github/json_matrices/engine-matrix.json
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/TransactionTestUtilities.java
- java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
instead of testing with valkey8 rc on our ci, we will now test with valkey 8
inn valkey 8 rc the valkey version was 7.9.240, so all the version checks needs to be updated
> Update Valkey version to 8.0.0 in test matrix and version checks

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Commands.ts
- node/src/Transaction.ts
- node/tests/SharedTests.ts
Add support for: 
- The xinfoGroups key argument should take binary keys. 
- lrem for transactions members argument should take binary keys. 
Fixes: https://github.com/valkey-io/valkey-glide/issues/2325
> Node: fix xinfogroups; fix lrem

- .github/workflows/java-cd.yml
Fixes starting the Valkey server in the java-cd workflow.
Resolves https://github.com/valkey-io/valkey-glide/issues/2318
> Java: fix CI job for testing Maven Deployment

- go/api/base_client.go
- go/api/commands.go
- go/api/glide_client.go
- go/api/response_handlers.go
- go/integTest/shared_commands_test.go
- go/utils/transform_utils.go
- go/utils/transform_utils_test.go
This PR implements the following Valkey hash commands:
- HGet: Get value of a hash field
- HGetAll: Get all fields and values in a hash
- HMGet: Get values of multiple hash fields
- HSet: Set value of a hash field
- HSetNX: Set value of a hash field if not exists
- HDel: Delete hash field(s)
- HLen: Get number of fields in a hash
- HVals: Get all values in a hash
- HExists: Check if a hash field exists
- HKeys: Get all field names in a hash
- HStrLen: Get string length of a hash field's value
> Go: Implementing Hash commands

- examples/node/README.MD
- examples/node/index.ts
- examples/node/package.json
1. Use the latest version from npm.
2. Clear up the doc.
3. Comment out the cluster mode in the example, leaving standalone mode by default.
> Fix node examples

- csharp/lib/Logger.cs
- csharp/lib/src/lib.rs
- java/client/src/main/java/glide/api/logging/Logger.java
- java/client/src/test/java/glide/connection/ConnectionWithGlideMockTests.java
- java/src/lib.rs
- logger_core/src/lib.rs
- node/rust-client/src/lib.rs
- node/src/Logger.ts
- python/python/glide/glide.pyi
- python/python/glide/logger.py
- python/src/lib.rs
- utils/cluster_manager.py
> Added option to turn off logger

- java/Cargo.toml
This PR strips debugging symbols from the compiled Rust shared object (`libglide_rs.so`)
and reduces its size from `59MB` down to `4.4MB`
Closes: https://github.com/valkey-io/valkey-glide/issues/2039
Before:
```bash
$ ls -lh ./target/release/deps/libglide_rs.so
-rwxrwxr-x 2 ubuntu ubuntu 59M Sep 29 11:15 ./target/release/deps/libglide_rs.so
```
After:
```bash
$ ls -lh ./target/release/deps/libglide_rs.so
-rwxrwxr-x 2 ubuntu ubuntu 4.4M Sep 29 11:51 ./target/release/deps/libglide_rs.so
```
> Reduce glide_rs.so size (for Java)

- node/src/GlideClusterClient.ts
- node/tests/ScanTest.test.ts
Reorganize imports - no real change for a user.
> Node: Fix imports for `Script` and `ClusterScanCursor`.

- go/api/base_client.go
- go/api/command_options.go
- go/api/list_commands.go
- go/api/response_handlers.go
- go/integTest/shared_commands_test.go
Implementing the following List commands:
- LPUSH
- LPOP, LPOP count
- LPOS, LPOS with options, LPOS count, LPOS count with options
- RPUSH
> Go: Implementing List commands

- glide-core/src/client/mod.rs
- glide-core/src/client/types.rs
- glide-core/src/protobuf/connection_request.proto
- glide-core/src/socket_listener.rs
- glide-core/tests/test_socket_listener.rs
- python/python/glide/config.py
- python/python/tests/conftest.py
- python/python/tests/test_async_client.py
This PR introduces a new feature that limits the maximum number of concurrent (inflight) requests sent to Valkey through each connection of a Glide client. This feature is implemented in the Glide infrastructure and is currently supported for the Python client, with plans to extend support to other language clients in the future.
Limiting the number of inflight requests per connection can help prevent the queues in the Glide infrastructure from running out of memory (OOM) due to excessive queuing or blocking. When the Glide infrastructure receives more requests than it can handle, it may start queuing requests, leading to increased memory usage and potential OOM situations in the queues. By controlling the number of inflight requests, this feature aims to mitigate the risk of the Glide …
> Added inflight_requests_limit

- logger_core/src/lib.rs
- logger_core/tests/test_logger.rs
Calling RollingFileAppender::new tries to create the directory for the log files even though logging is turned off by Logger.init('off', null). This change simply postpones the initialization of RollingFileAppender until it is actually needed. This way if we do eg. Logger.init("info", null) it works as expected and does not throw an error on readonly filesystems.
Fixes #2387
> Fix logger initialization on readonly filesystems

- java/build.gradle
Additional logging of failed tests at the end of each test run. No need to search in big output for failures.
Example of message:
```
Failed tests for `:client`:
glide.ExceptionHandlingTests.verify_future_pipeline_abortion()
Failed tests for `:integTest`:
glide.cluster.CommandTests.flushall()
glide.cluster.CommandTests.fcall_readonly_binary_function()
glide.cluster.CommandTests.fcall_readonly_function()
```
<details>
```
...
TransactionTests > sort and sortReadOnly PASSED
TransactionTests > test transaction dump restore STARTED
glide.standalone.TransactionTests.test_transaction_dump_restore(): SUCCESS 0.001s
TransactionTests > test transaction dump restore PASSED
328 tests completed, 3 failed, 6 skipped
> Task :integTest:test FAILED
> Task :integTest:stopAllAfterTests
INFO:root:## …
```
> Java: log failed tests

- java/integTest/src/test/java/glide/LoggerTests.java
Since #2391 log file isn't created if no writes requested. Test "LoggerTests > log to file" starts to fail on `main` branch.
> Java: fix logger test

- .github/workflows/java.yml
- java/integTest/src/test/java/glide/cluster/CommandTests.java
1. Fix flaky IT
2. Activate that test with valkey 8
3. Uncomment a test
> Java; Fix IT

- go/api/base_client.go
- go/api/commands.go
- go/integTest/shared_commands_test.go
> Go: Implementing PING command

- java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/GlideClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/GlideClusterClientConfiguration.java
- java/client/src/main/java/glide/managers/ConnectionManager.java
- java/client/src/test/java/glide/managers/ConnectionManagerTest.java
- java/integTest/src/test/java/glide/SharedClientTests.java
Adding support for this client config `inflightRequestsLimit`
The maximum number of concurrent requests allowed to be in-flight (sent but not yet completed).
This limit is used to control the memory usage and prevent the client from overwhelming the server or getting stuck in case of a queue backlog.
If not set, a default value will be used.
> Added inflightRequestsLimit client config to java

- .github/workflows/python.yml
- .github/workflows/start-self-hosted-runner/action.yml
- Replacing the installation of flake8, isort, and black with threeal/pipx-install-action.
- Changing the AWS CLI installation to use sudo snap refresh and sudo snap install aws-cli --classic, removing unnecessary apt commands.
This Pull Request is linked to issue (URL): #2447 
Due to failing: https://github.com/valkey-io/valkey-glide/actions/runs/11313325861/job/31462097795?pr=2372
> Fix CI failing

- python/python/tests/test_async_client.py
due to failing https://github.com/valkey-io/valkey-glide/actions/runs/11328568407/job/31502098614
This Pull Request is linked to issue (URL): #2454 
* ~[ ] CHANGELOG.md and documentation files are updated.~ not needed
> Fix mypy failing

- node/rust-client/src/lib.rs
- node/src/BaseClient.ts
- node/tests/GlideClient.test.ts
- node/tests/GlideClusterClient.test.ts
Adding support for this client config inflightRequestsLimit
The maximum number of concurrent requests allowed to be in-flight (sent but not yet completed).
This limit is used to control the memory usage and prevent the client from overwhelming the server or getting stuck in case of a queue backlog.
If not set, a default value will be used.
Issue link
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/1253
> Added inflightRequestsLimit client config to Node

- .github/workflows/java.yml
- CHANGELOG.md
Revert https://github.com/valkey-io/valkey-glide/pull/2404 - allow a developer to run modules CI without creating a PR
> Java: Allow to run modules CI on demand.

- go/api/base_client.go
- go/api/commands.go
- go/api/generic_commands.go
- go/integTest/shared_commands_test.go
> Go: Implementing DEL command

- .github/workflows/python.yml
Replay #2444 which was reverted by #2456
Fixes CI failures:
https://github.com/valkey-io/valkey-glide/actions/runs/11364202422/job/31638558098
```
Run black --check --diff .
Usage: black [OPTIONS] SRC ...
Try 'black -h' for help.
Error: Invalid value for '-t' / '--target-version': 'py311' is not one of 'py27', 'py33', 'py34', 'py35', 'py36', 'py37', 'py38', 'py39', 'py310'.
Error: Process completed with exit code 2.
```
Incorrect version of `black` was installed
> Fix python CI: fix linter installation

- .github/workflows/build-node-wrapper/action.yml
- .github/workflows/install-shared-dependencies/action.yml
- .github/workflows/node.yml
- CHANGELOG.md
- node/package.json
- node/tests/ServerModules.test.ts
- node/tests/TestUtilities.ts
This Pull Request is linked to issue (URL): [[#2431](https://github.com/valkey-io/valkey-glide/issues/2431)]
> Node: Add CI support for server modules

- CHANGELOG.md
- glide-core/src/client/value_conversion.rs
- java/client/src/main/java/glide/api/commands/servermodules/FT.java
- java/integTest/src/test/java/glide/modules/VectorSearchTests.java
> Java: add `FT.INFO`

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/servermodules/FT.java
- java/integTest/src/test/java/glide/modules/VectorSearchTests.java
- python/python/glide/async_commands/server_modules/ft.py
> Java: FT.ALIASADD, FT.ALIASDEL, FT.ALIASUPDATE

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/servermodules/Json.java
- java/integTest/build.gradle
- java/integTest/src/test/java/glide/modules/JsonTests.java
- java/integTest/src/test/java/glide/modules/VectorSearchTests.java
> Java: `JSON.ARRINSERT` and `JSON.ARRLEN`

- glide-core/redis-rs/redis/src/aio/connection.rs
- glide-core/redis-rs/redis/src/aio/connection_manager.rs
- glide-core/redis-rs/redis/src/aio/multiplexed_connection.rs
- glide-core/redis-rs/redis/src/cluster.rs
- glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/types.rs
- glide-core/redis-rs/redis/tests/test_async.rs
- glide-core/redis-rs/redis/tests/test_cluster_async.rs
- glide-core/tests/test_socket_listener.rs
ATM, on I/O errors, we would reconnect to the failed node and retry the request if there were more retries left. This approach had a critical issue: we couldn’t reliably determine if the server had already received the request before the connection was broken. Retrying in such cases could result in duplicate command execution.
**Example:**
1. Client sends `INCR key`.
2. Server receives the request and increments the key (e.g., key = 1).
3. A network issue disconnects the client before the server can respond.
4. The client reconnects and retries the `INCR key`.
5. Server increments the key again (now key = 2). **BAD outcome**.
This PR differentiates between errors where it’s safe to retry and those where it’s not. Specifically, with multiplexed connections, if the `send` function returns …
> Avoid retrying on IO errors when it’s unclear if the server received the request

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/servermodules/Json.java
- java/integTest/src/test/java/glide/modules/JsonTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2430
> Java: add JSON.ARRAPPEND command

- CHANGELOG.md
- glide-core/src/retry_strategies.rs
- glide-core/src/socket_listener.rs
- glide-core/tests/test_socket_listener.rs
1.Introduced a user-land mechanism for ensuring singleton behavior of the socket, rather than relying on OS-specific semantics. This addresses the issue where macOS and Linux report different errors when the socket path already exists.
2.Simplified the implementation by removing unnecessary abstractions, including redundant connection retry logic.
This Pull Request is linked to issue (URL): [https://github.com/valkey-io/valkey-glide/issues/2433]
> Core: UDS Socket Handling Rework

- .github/workflows/node.yml
- CHANGELOG.md
- node/src/server-modules/GlideJson.ts
- node/tests/ServerModules.test.ts
This Pull Request is linked to issue (URL): https://github.com/orgs/valkey-io/projects/10/views/2?filterQuery=milestone%3A%221.2%22&pane=issue&itemId=82990279&issue=valkey-io%7Cvalkey-glide%7C2375
> Node: Add command JSON.TOGGLE

- java/integTest/src/test/java/glide/SharedCommandTests.java
Fixes failure of `non_UTF8_GlideString_map_of_arrays` test on redis 6.2. `lmpop` exists from version 7+
https://github.com/valkey-io/valkey-glide/actions/runs/11440382907/job/31827744171?pr=2051#step:7:35157
> Java: fix IT

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/servermodules/Json.java
- java/integTest/src/test/java/glide/modules/JsonTests.java
https://github.com/valkey-io/valkey-glide/issues/2430
> Java: add JSON.TOGGLE command

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/servermodules/Json.java
- java/integTest/src/test/java/glide/modules/JsonTests.java
> Java: `JSON.OBJLEN` and `JSON.OBJKEYS`.

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/servermodules/Json.java
- java/client/src/test/java/glide/api/commands/servermodules/JsonTest.java
- java/integTest/src/test/java/glide/modules/JsonTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2430
> Java: add JSON.RESP

- .github/json_matrices/build-matrix.json
- .github/workflows/install-shared-dependencies/action.yml
- .github/workflows/node.yml
- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
- .github/workflows/setup-musl-on-linux/action.yml
- node/package.json
This pull request includes multiple changes to the GitHub Actions workflows and configuration files to improve compatibility, update dependencies, and streamline processes. The most important changes include fixing the alpine version used to fix node release.
Other noticeable changes include Node.js and Python versions, adjustments to the build matrix, and various workflow improvements.
* Updated Node.js version to the latest in multiple workflows (`.github/workflows/node.yml`, `.github/workflows/npm-cd.yml`, `.github/workflows/ort.yml`) [[1]](diffhunk://#diff-4e88a8cc63d2540befa3412886ac9b9db5cd10bce852960298517ea4bd7f7bb7L73-R73) [[2]](diffhunk://#diff-d82fbe1e66dd8b4d402dbfe77afd4797282eaa290459f5a4bd71e941f835ce71L339-R345) [[3]](diffhunk://#diff-75ac158aae3cd2a706ad143f554be6e3edb0274 …
> Rc 1.2 fix

- CHANGELOG.md
- python/python/glide/async_commands/server_modules/json.py
- python/python/tests/tests_server_modules/test_json.py
> Python: adds JSON.STRLEN, JSON.STRAPPEND commands

- CHANGELOG.md
- python/python/glide/async_commands/server_modules/json.py
- python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): #645 
> Python: adds JSON.ARRINSERT command

- CHANGELOG.md
- python/python/glide/async_commands/server_modules/json.py
- python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): #2412 
> Python: add JSON.DEBUG.FIELDS and JSON.DEBUG.MEMORY commands

- CHANGELOG.md
- python/python/glide/async_commands/server_modules/json.py
- python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): #645 
> Python: adds JSON.ARRTRIM command

- CHANGELOG.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/command_args.py
- python/python/glide/async_commands/server_modules/ft.py
- python/python/glide/async_commands/server_modules/ft_options/ft_aggregate_options.py
- python/python/glide/async_commands/server_modules/ft_options/ft_constants.py
- python/python/tests/tests_server_modules/test_ft.py
This Pull Request is linked to issue (URL): #2429
> Python: FT.AGGREGATE command added

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/servermodules/Json.java
- java/client/src/test/java/glide/api/commands/servermodules/JsonTest.java
- java/integTest/src/test/java/glide/modules/JsonTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2430
> Java: add JSON.TYPE

- java/integTest/src/test/java/glide/TestUtilities.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
Fix failure of the following IT
```
glide.cluster.CommandTests.scriptKill_with_route()
glide.cluster.CommandTests.scriptKill_unkillable()
glide.standalone.CommandTests.scriptKill()
glide.standalone.CommandTests.scriptKill_unkillable()
```
especially on redis 6, which has no `function kill`.
ref #2524
> Java: Fix script kill IT

- node/DEVELOPER.md
- node/package.json
- node/tsconfig.json
https://www.npmjs.com/package/ts-node
> Add node REPL

- CHANGELOG.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/server_modules/json.py
- python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): #645 
> Python: adds JSON.ARRPOP command

- .github/workflows/test-benchmark/action.yml
Fix test-benchmark CI error MISCONF by disabling the RDB snapshots on the server (with `--save ""`):
> [ErrorReply: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.]
https://github.com/valkey-io/valkey-glide/actions/runs/11643552677/job/32424425430#step:8:2
> Fix benchmark CI error MISCONF

- python/python/tests/test_async_client.py
- python/python/tests/utils/utils.py
This Pull Request is linked to issue (URL): #2594 
> Python: Round map values in tests for floating-point comparison

- glide-core/Cargo.toml
- glide-core/redis-rs/redis/Cargo.toml
- glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
- glide-core/redis-rs/redis/src/cluster_async/connections_logic.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/src/client/mod.rs
- glide-core/src/client/reconnecting_connection.rs
- glide-core/src/client/standalone_client.rs
- glide-core/src/lib.rs
- glide-core/telemetry/Cargo.toml
- glide-core/telemetry/src/lib.rs
- glide-core/tests/test_client.rs
- glide-core/tests/utilities/cluster.rs
With this PR, `glide-core` + `redis-rs` adds the ability to count for active connections + clients (this is done per process and **not** per client).
Exposing this functionality to the end user will be done in separate PRs.
Related issue: https://github.com/valkey-io/valkey-glide/issues/2376
> Added `Telemetry` support for GLIDE client (core only)

- node/tests/TestUtilities.ts
Clients may not be properly closed when FLUSHALL command times out in flushAndCloseClient, despite being handled in afterEach blocks of test suites.
The issue is reproducible by configuring an extremely low random requestTimeout value in ClientConfiguration during [testTeardown execution](https://github.com/jhpung/valkey-glide/blob/b33968cce98c1f4897448841289e0cec3dc75050/node/tests/TestUtilities.ts#L400-L405)
Fixes CI: https://github.com/avifenesh/valkey-glide/actions/runs/11678481691/job/32518075011
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2336
- …
> Node: Ensure client closure in flushAndCloseClient with try-finally

- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
> Node tests - transactions fix

- java/integTest/src/test/java/glide/SharedClientTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
This Pull Request is linked to issue (URL): Fixes #2619 and #2618
Raised Timeouts to add flexibility on some tests and avoid time outs for tests:
* `glide.SharedClientTests.send_and_receive_large_values`
* `glide.cluster.CommandTests.fcall_readonly_function`
Fixes CI run: https://github.com/valkey-io/valkey-glide/actions/runs/11691408118 (note: modules test was rejected - hence the red 'X')
-   N/A This Pull Request is related to one issue - fixes similar bugs.
-   N/A Commit message has a detailed description of what changed and why.
-   N/A CHANGELOG.md and documentation files are updated.
> Bump valkey 8 wait timeout

- node/jest.config.js
- node/package.json
- node/tests/GlideClient.test.ts
- node/tests/GlideClusterClient.test.ts
- node/tests/PubSub.test.ts
- node/tests/ScanTest.test.ts
- node/tests/ServerModules.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
- node/tests/setup.js
- node/tests/setup.ts
- node/tests/tsconfig.json
- utils/TestUtils.ts
- utils/package.json
- utils/release-candidate-testing/node/index.js
The main reason of this PR is to fix parsing issue with modules tests,
This pull request includes several changes to the `node` and `utils` directories, focusing on improving test configurations, updating dependencies, and refactoring code for better maintainability. The most important changes are grouped into test configuration updates, dependency updates, and code refactoring.
* [`node/jest.config.js`](diffhunk://#diff-3c657330b3b1f8ed84fa9c7ec5cb77162627b38e2a64f3af0c2ddf23c1258d65L32-R32): Updated the `setupFilesAfterEnv` configuration to use `setup.ts` instead of `setup.js`.
* [`node/package.json`](diffhunk://#diff-d6e19f28e97cfeda63a9bd9426f10f1d2454eeed375ee1235e8ba842ceeb46a0L37-R37): Modified the `test-modules` script to run tests in-band for better isolation.
* …
> Node modules test fix

- node/tests/GlideClient.test.ts
- node/tests/GlideClusterClient.test.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
Changed Node's SCRIPT KILL test to test only that the command works, not that a script is actually being killed (to test the client and not the server). Moved to SharedTests.
This Pull Request is linked to issue (URL): closes #2625 
> Node: Increase times for SCRIPT KILL tests to avoid flakiness

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/servermodules/FT.java
- java/integTest/src/test/java/glide/modules/VectorSearchTests.java
> Java: `FT._LIST`.

- CHANGELOG.md
- node/src/server-modules/GlideJson.ts
- node/tests/ServerModules.test.ts
> Node: add command JSON.NUMINCRBY and JSON.NUMMULTBY

- CHANGELOG.md
- node/src/server-modules/GlideJson.ts
- node/tests/ServerModules.test.ts
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2529
> Node: add JSON.OBJLEN and JSON.OBJKEYS

- deny.toml
- python/python/tests/test_transaction.py
This pull request includes updates to the `deny.toml` file to ignore additional security advisories and adds a warning filter to a test in the `test_transaction.py` file.
Security updates:
* [`deny.toml`](diffhunk://#diff-1040309c64844eb1b6b63d8fd67938adbf9461f1b3c61f12cf738f064a02d3deR27-R28): Added "RUSTSEC-2024-0384" and "RUSTSEC-2024-0388" to the list of ignored advisories.
Test improvements:
* [`python/python/tests/test_transaction.py`](diffhunk://#diff-0e76e703bbbc3d8fba066a7e2d2dfa3d620ca525655886096cf249f92e6d5ab4R1036-R1038): Added a filter to ignore warnings for the `test_transaction_clear` function.
This Pull Request is linked to issue #2669
-   [x] Commit message …
> Rust dep ci issue and warning in transaction py fix

- glide-core/redis-rs/redis/Cargo.toml
- glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/commands/cluster_scan.rs
- glide-core/redis-rs/redis/tests/support/util.rs
- glide-core/redis-rs/redis/tests/test_basic.rs
This PR refactors the connection container lock to use a synchronous RwLock instead of an asynchronous one, ensuring that the lock is held only briefly and not across await points. This change addresses potential deadlocks and improves overall lock acquisition time.
In the redis-rs implementation, the entire request pipeline is blocked while the cluster client is in a recovery state. Specifically, when poll_flush calls poll_recover, the system waits for the recovery future to complete before processing other tasks. During this recovery period, some in-flight requests may already be running but remain pending. This creates a risk of deadlock if a request holds the connection container lock while the recovery future is waiting for it.
Switching to a synchronous lock ensures that the …
> Core: Refactored the connection container lock to use a sync RwLock

- CHANGELOG.md
- benchmarks/rust/Cargo.toml
- deny.toml
- glide-core/Cargo.toml
- glide-core/redis-rs/redis/Cargo.toml
- glide-core/redis-rs/redis/src/aio/connection_manager.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_topology.rs
- glide-core/src/client/reconnecting_connection.rs
- glide-core/src/retry_strategies.rs
- go/Cargo.toml
- go/src/lib.rs
**PR Description:**
This PR enhances the retry strategy and addresses dependency maintenance issues in the Rust lint CI:
- **Replaced Unmaintained Crates**: Removed the `backoff`, `tokio-retry`, `futures-time` and `Derivative` crates due to limited functionality and lack of maintenance. Previously, the project used both `backoff` (unmaintained) and `tokio-retry` (last updated 3 years ago). These have been replaced with `tokio-retry2`, which offers enhanced features for exponential backoff. Additionally, `Derivative` was removed as it is no longer maintained.
- **Improved Retry Functionality**: The new `tokio-retry2` crate includes better jitter control, ensuring consistent exponential backoff intervals without erratic timings. The previous implementation produced inconsistent retry …
> Improve retry logic and update unmaintained dependencies for Rust lint CI

- CHANGELOG.md
In the previous implementation, the read lock (inner.conn_lock.read()) was held throughout the entire connection refresh process (for all connections sent to refresh), including while attempting to establish connections (via get_or_create_conn). If connections were slow or timed out, the lock was held for an extended duration, blocking other tasks requiring a write lock.
The new implementation releases the read lock before making connection attempts. If the connection is successfully established, the read lock is reacquired to update the connection container. This approach ensures that other operations needing the lock (e.g., write operations) can proceed while connections are being established.
This commit was already approved on our redis-rs fork but wasn't merged into glide, see former …
> Core: Release the read lock while creating connections in `refresh_connections`

- CHANGELOG.md
- glide-core/redis-rs/redis/src/cluster.rs
- glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_routing.rs
- glide-core/redis-rs/redis/src/cluster_slotmap.rs
- glide-core/redis-rs/redis/src/cluster_topology.rs
- glide-core/redis-rs/redis/src/commands/cluster_scan.rs
- glide-core/redis-rs/redis/tests/auth.rs
- glide-core/redis-rs/redis/tests/test_cluster_async.rs
This PR was previously reviewed in our redis-rs fork at https://github.com/amazon-contributing/redis-rs/pull/190 but was on hold due to lock issues. The recently merged PR #2643 addresses the encountered lock issues, making this PR now ready for merging.
This pull request introduces two significant updates:
1. **SlotMap Refactor**: The SlotMap structure has been updated with the addition of a `NodesMap`, which allows shard addresses to be shared between shard nodes and slot map values. This refactor optimizes how shard information is managed. For a detailed explanation, refer to PR [#185](https://github.com/amazon-contributing/redis-rs/pull/185).
The diagram on the left illustrates the current SlotMap design, while the diagram on the right shows the newly implemented structure:
2. **MOVED …
> Core: SlotMap refactor - Added NodesMap, Update the slot map upon MOVED errors

- CHANGELOG.md
- node/rust-client/src/lib.rs
- node/src/BaseClient.ts
- node/tests/GlideClusterClient.test.ts
This Pull Request is linked to issue (URL): #2376 
> Node - Client API for retrieving internal statistics

- .github/json_matrices/supported-languages-versions.json
- go/DEVELOPER.md
- go/Makefile
- go/benchmarks/go.mod
Signed-off-by: avifenesh <aviarchi1994@gmail.com>
https://github.com/valkey-io/valkey-glide/issues/2739
> Update supported Go language versions to include 1.20.0

- .github/json_matrices/build-matrix.json
- .github/workflows/npm-cd.yml
- node/package.json
This pull request includes several updates to the build and deployment workflows, as well as dependency updates. The most important changes are improvements to the npm publish process, the addition of a package deprecation step on failure, and updates to the build matrix and dependencies.
* [`.github/workflows/npm-cd.yml`](diffhunk://#diff-d82fbe1e66dd8b4d402dbfe77afd4797282eaa290459f5a4bd71e941f835ce71L184-R198): Improved the npm publish process by enhancing error handling and logging, and simplified the command to filter out notices and warnings.
* [`.github/workflows/npm-cd.yml`](diffhunk://#diff-d82fbe1e66dd8b4d402dbfe77afd4797282eaa290459f5a4bd71e941f835ce71R382-R431): Added a step to deprecate packages if the job fails, ensuring deprecated packages are marked correctly. This …
> Node rc fixes + unpublish on failure mechanism

- java/README.md
- java/client/build.gradle
- java/integTest/build.gradle
Remove macos x64 references left from readme - not supported anymore
> Java: Fix readme

- node/src/BaseClient.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
This Pull Request is linked to issue (URL): #2729 
> Node: Add Documentations for base objects

- node/npm/glide/package.json
npm RC release is missing the server-modules definition files: 
see: https://www.npmjs.com/package/@valkey/valkey-glide/v/1.2.0-rc16?activeTab=code
With this change, we have the following files in node/npm/glide/build-ts with a `build`: 
```
index.d.ts	index.js	src
./src:
BaseClient.d.ts		Errors.d.ts		GlideClusterClient.d.ts	ProtobufMessage.d.ts	server-modules
Commands.d.ts		GlideClient.d.ts	Logger.d.ts		Transaction.d.ts
./src/server-modules:
GlideFt.d.ts		GlideFtOptions.d.ts	GlideJson.d.ts
```
This Pull Request is linked to issue (URL): #2755
-   N/A Tests are added or updated.
-   N/A CHANGELOG.md and …
> Node: Add server-modules to npm release

- glide-core/redis-rs/redis/src/cluster.rs
- glide-core/redis-rs/redis/src/cluster_routing.rs
- glide-core/redis-rs/redis/src/cmd.rs
- glide-core/redis-rs/redis/src/commands/cluster_scan.rs
- glide-core/redis-rs/redis/src/connection.rs
- glide-core/redis-rs/redis/src/types.rs
- glide-core/redis-rs/redis/tests/test_async_cluster_connections_logic.rs
- glide-core/redis-rs/redis/tests/test_cluster_async.rs
Apply linters to submodule
Unblock CI https://github.com/valkey-io/valkey-glide/actions/runs/12108231639/job/33756004011?pr=2778#step:6:105
Depends on #2648
> Apply linters to submodule

- glide-core/redis-rs/redis/Cargo.toml
Fix [CI failures on main](https://github.com/valkey-io/valkey-glide/actions/runs/12242609472/job/34150311714#step:3:762):
```
warning[license-not-encountered]: license was not encountered
┌─ /home/runner/work/valkey-glide/valkey-glide/deny.toml:57:6
│
57 │     "Unicode-DFS-2016",
│      ━━━━━━━━━━━━━━━━ unmatched license allowance
error[vulnerability]: `idna` accepts Punycode labels that do not produce any non-ASCII when decoded
┌─ /home/runner/work/valkey-glide/valkey-glide/glide-core/Cargo.lock:83:1
│
83 │ idna 0.5.0 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ security vulnerability detected
│
├ ID: RUSTSEC-2024-0421
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0421
├ `idna` 0.5.0 and earlier accepts …
```
> Fix rust CI: bump `idna`.

- .github/workflows/python.yml
- Makefile
- python/DEVELOPER.md
- python/dev_requirements.txt
- python/requirements.txt
It is impossible to run tests without building the client, so we need both requirement files.
It is impossible to work on client (e.g. add or fix a feature) without using both requirement files again.
So I merged them.
I also updated `mypy` to avoid errors [like these](https://github.com/valkey-io/valkey-glide/actions/runs/11677295143/job/32514951690#step:6:43). It is fixed in https://github.com/python/mypy/issues/6463 a year ago.
-   [x] Commits will be …
> Merge python requirement files.

- node/src/server-modules/GlideJson.ts
Fix small mistake in examples in docs for JSON module.
Thanks @jbrinkman for finding that!
> Node: fix examples in docs

- .github/workflows/java-cd.yml
- .github/workflows/java.yml
- CHANGELOG.md
- java/DEVELOPER.md
- java/client/build.gradle
> Protobuf: bump to 29.1

- CHANGELOG.md
- node/npm/glide/index.ts
- node/npm/glide/package.json
This Pull Request resolves issue (https://github.com/valkey-io/valkey-glide/issues/2799).
This change removes the native package reference in package.json and updates the `npm/glide` index file to remove the native binding for the Darwin-x64 package which was removed in the Valkey-Glide 1.2.0 release.
> remove native package references for MacOS x64 architecture

- python/src/lib.rs
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/2809): [#2809 ]
> Fix memory leak in Python

- go/api/base_client.go
- go/api/generic_commands.go
- go/integTest/shared_commands_test.go
> Go: Implement Type, Touch and Unlink commands

- go/Makefile
- go/api/glide_client.go
- go/api/glide_cluster_client.go
- go/api/response_handlers.go
- go/api/response_types.go
- go/integTest/cluster_commands_test.go
- go/integTest/standalone_commands_test.go
* cluster client compilation fixes
* `CustomCommand` for cluster client
* `CustomCommand` doc update for standalone
* `ClusterValue` and related things
* Tests (no routing yet)
* Update map and set handling to store strings only as keys (and test update)
* makefile fixes
> Go: Add custom command to cluster client

- .github/workflows/create-test-matrices/action.yml
Space in `CONTAINER_OPTIONS` was interpreted by `awk` as field separator and it caused CI failures:
https://github.com/valkey-io/valkey-glide/actions/runs/12148100672/job/33875834171#step:3:41
Matrix entry become broken:
```
host-matrix=[{"OS":"ubuntu","NAMED_OS":"linux","RUNNER":"ubuntu-24.04","ARCH":"x64","TARGET":"x86_64-unknown-linux-gnu","PACKAGE_MANAGERS":["pypi","npm","maven"],"run":"always","languages":["python","node","java","go","dotnet"]},{"OS":"ubuntu","NAMED_OS":"linux","ARCH":"x64","TARGET":"x86_64-unknown-linux-musl","RUNNER":"ubuntu-24.04","IMAGE":"node:lts-alpine","CONTAINER_OPTIONS":"--user
```
(`$1` stands for the first field, `$0` for entire line)
> Fix full matrix CI

- CHANGELOG.md
- go/api/base_client.go
- go/api/options/zadd_options.go
- go/api/sorted_set_commands.go
- go/go.mod
- go/integTest/shared_commands_test.go
- go/utils/transform_utils.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2833
> Go: Add command ZAdd

- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_slotmap.rs
- glide-core/redis-rs/redis/src/commands/cluster_scan.rs
- glide-core/redis-rs/redis/src/commands/mod.rs
- glide-core/redis-rs/redis/src/lib.rs
- glide-core/redis-rs/redis/tests/test_cluster_scan.rs
- glide-core/src/client/mod.rs
- glide-core/src/protobuf/command_request.proto
- glide-core/src/socket_listener.rs
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/core.py
- python/python/glide/glide_client.py
- python/python/tests/conftest.py
- python/python/tests/test_scan.py
- python/python/tests/test_transaction.py
This pull request focuses on refactoring and simplifying the `cluster_scan` functionality in the `glide-core/redis-rs` library and adding allow non cover slots functionality to the core and py. Other important changes include removing redundant methods, consolidating the `cluster_scan` functions, and updating the related tests.
Refactoring and simplification:
* [`glide-core/redis-rs/redis/src/cluster_async/mod.rs`](diffhunk://#diff-75c8b034d9c8c02514ee9481ea89ba896f0d6ba79831ad28f91630b454aff53bL145-R154): Removed the `cluster_scan_with_pattern` method and consolidated its functionality into the `cluster_scan` method. Updated the `cluster_scan` method to use the `ClusterScanArgs` struct for arguments. [[1]](diffhunk://#diff-75c8b034d9c8c02514ee9481ea89ba896f0d6ba79831ad28f91630b454aff53bL1 …
> Core + Py: add allow_non_covered_slots to ClusterScan and related commands

- CHANGELOG.md
- go/api/base_client.go
- go/api/response_handlers.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
Adding command Zpopmin and zpopmax for the go wrapper
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2833
> Go: Add ZPopMin and ZPopMax

- go/api/options/base_scan_options.go
Refactoring changes:
1. Move BaseScanOptions to a separate file: options/base_scan_options.go to use as an embedding in other commands.
This Pull Request is linked to issue (URL): #2832 
> Go: Add base scan options for hscan

- CHANGELOG.md
- java/client/src/main/java/glide/api/models/commands/scan/ScanOptions.java
- java/client/src/main/java/glide/managers/CommandManager.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2436
> Java: Allow uncovered slots ClusterScan

- .github/workflows/python.yml
- CHANGELOG.md
- Makefile
- eslint.config.mjs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_slotmap.rs
- glide-core/redis-rs/redis/src/commands/cluster_scan.rs
- glide-core/redis-rs/redis/src/commands/mod.rs
- glide-core/redis-rs/redis/src/lib.rs
- glide-core/redis-rs/redis/tests/test_cluster_scan.rs
- glide-core/src/client/mod.rs
- glide-core/src/protobuf/command_request.proto
- glide-core/src/socket_listener.rs
- java/client/src/main/java/glide/api/models/commands/scan/ScanOptions.java
- java/client/src/main/java/glide/managers/CommandManager.java
- node/src/Commands.ts
- node/src/GlideClusterClient.ts
- node/tests/ScanTest.test.ts
- node/tests/TestUtilities.ts
- package.json
- python/DEVELOPER.md
- python/dev_requirements.txt
- python/python/glide/async_commands/cluster_commands.py
- python/python/glide/async_commands/core.py
- python/python/glide/glide_client.py
- python/python/tests/conftest.py
- python/python/tests/test_scan.py
- python/python/tests/test_transaction.py
- python/requirements.txt
- utils/TestUtils.ts
This pull request adds modifications to the cluster scanning functionality, allowing uncovered slots cluster scan.
* [`.github/workflows/python.yml`](diffhunk://#diff-092659a9bd0068791326fb1d08f005532e5aeb983b999a7bd32c51deee0a71d5L118-R118): Changed the dependency installation from `dev_requirements.txt` to `requirements.txt` in the Python workflows. [[1]](diffhunk://#diff-092659a9bd0068791326fb1d08f005532e5aeb983b999a7bd32c51deee0a71d5L118-R118) [[2]](diffhunk://#diff-092659a9bd0068791326fb1d08f005532e5aeb983b999a7bd32c51deee0a71d5L181-R181)
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L61): Removed the installation of `dev_requirements.txt` to streamline the setup process.
* [`glide-core/redis-rs/redis/src/cluster_async/mod.rs`](diffhun …
> Release 1.2 uncoverd slots

- .github/workflows/java-cd.yml
- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
This Pull Request is linked to issue https://github.com/valkey-io/valkey-glide/issues/2885
-   [-] Tests are added or updated.
-   [-] CHANGELOG.md and documentation files are updated.
> CD fixes nedded for Release 1.2.1

- go/api/base_client.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2833
> Go: `ZREM`.

- CHANGELOG.md
- java/client/src/main/java/glide/api/BaseClient.java
- java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java
- java/client/src/test/java/glide/api/GlideClientTest.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2845
> Java: Add binary version of ZRANK WITHSCORE

- CHANGELOG.md
- go/api/base_client.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2833
> Go: add ZCARD

- .github/ISSUE_TEMPLATE/flaky-ci-test-issue.yml
- .github/ISSUE_TEMPLATE/inquiry.yml
- .github/ISSUE_TEMPLATE/task.yml
- .github/workflows/lint-yaml.yml
- .github/workflows/pypi-cd.yml
This Pull Request is linked to issue: [#2717]
> CI: Add workflow that runs prettier on yaml workflow files 

- .github/workflows/build-python-wrapper/action.yml
- .github/workflows/ort.yml
- .github/workflows/python.yml
- python/.ort.yml
- python/DEVELOPER.md
- python/dev_requirements.txt
- python/pyproject.toml
- python/requirements.txt
- utils/get_licenses_from_ort.py
This Pull Request is linked to issue (URL): [2774](https://github.com/valkey-io/valkey-glide/issues/2774), [2709](https://github.com/valkey-io/valkey-glide/issues/2709)
> Update ORT to skip approved packages or those under testing

- java/benchmarks/build.gradle
- java/client/build.gradle
- java/integTest/build.gradle
Fixes #2817
No changes in API nor in CD or build process.
We used release config even for unit testing. Duplicated tasks for release/debug build remain from the very first poc of the java client.
> fix gradle

- .github/workflows/go.yml
- go/DEVELOPER.md
- go/Makefile
- go/api/options/zadd_options.go
- go/integTest/glide_test_suite_test.go
- go/integTest/shared_commands_test.go
1. Minor fix in few tests
2. Test report generation
> Go: test fixes + reporting

- CHANGELOG.md
- go/api/base_client.go
- go/api/response_handlers.go
- go/api/response_types.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/2833)
> GO: Add BZPopMin command

- glide-core/redis-rs/redis/src/cluster_async/mod.rs
Moving to not throttle refresh slots after reconnecting to initial nodes, as this operation is kind of 'resetting' the client, so it should let it discover the whole topology before moving on to handle requests.
> Enable refresh slots after reconnecting to initial nodes.

- benchmarks/rust/src/main.rs
- deny.toml
- glide-core/build.rs
- python/Cargo.toml
- python/python/tests/test_async_client.py
- python/src/lib.rs
Backport some fixes to 1.1 to unblock CI on this branch:
https://github.com/valkey-io/valkey-glide/actions/runs/12656712513/job/35269914890?pr=2421
https://github.com/valkey-io/valkey-glide/actions/runs/12656712527/job/35269924311?pr=2421
https://github.com/valkey-io/valkey-glide/actions/runs/12658199998/job/35274599049?pr=2923
https://github.com/valkey-io/valkey-glide/actions/runs/12658033208/job/35274061342?pr=2923
https://github.com/valkey-io/valkey-glide/actions/runs/12658033237/job/35274061696?pr=2923
Changes taken from:
#2673
#2773
#2584 (python)
#2453
#2793
> Fix CI on 1.1

- csharp/lib/src/lib.rs
- glide-core/benches/rotating_buffer_benchmark.rs
- glide-core/src/rotating_buffer.rs
- glide-core/src/socket_listener.rs
- go/api/response_handlers.go
- go/src/lib.rs
- java/src/ffi_test.rs
- node/rust-client/src/lib.rs
- python/src/lib.rs
The purpose of this PR is to use newer pointer/C-string APIs that weren't available when the repo was created, in order to make the handling of raw pointers slightly safer.
This change is only a partial change - hopefully I'll have time to go over more of the pointer conversions and double check them.
This is in preparation of the [pointer provenance](https://doc.rust-lang.org/beta/std/ptr/index.html#provenance) change that will hopefully land in the next Rust release, which will allow for even better safety in handling pointers.
-   [ ] CHANGELOG.md and documentation …
> Some pointer shenanigans.

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Transaction.ts
Node: Fix `zrangeWithScores` (disallow `RangeByLex` as it is not supported)
```ts
> await client.zrangeWithScores("zz", { start: '-', end: '+', type: "byLex"})
2025-01-08T02:49:25.077335Z  WARN logger_core: received error - An error was signalled by the server - ResponseError: syntax error, WITHSCORES not supported in combination with BYLEX
Uncaught:
RequestError: An error was signalled by the server - ResponseError: syntax error, WITHSCORES not supported in combination with BYLEX
at GlideClient.processResponse (node/build-ts/src/BaseClient.js:337:20)
at GlideClient.handleReadData (node/build-ts/src/BaseClient.js:322:22)
```
> Node: Fix `zrangeWithScores` (disallow `RangeByLex` as it is not supported)

- go/api/base_client.go
- go/api/options/constants.go
- go/api/response_handlers.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2833
> Go: Add command ZRank and ZRevRank

- go/api/base_client.go
- go/api/options/stream_options.go
- go/api/stream_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2881 
> Go: Add XTrim, XLen commands

- go/api/base_client.go
- go/api/options/zrange_options.go
- go/api/sorted_set_commands.go
- go/integTest/glide_test_suite_test.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2878
> Go: ZRANGE

- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_topology.rs
- glide-core/redis-rs/redis/src/sentinel.rs
- glide-core/redis-rs/redis/tests/test_cluster_scan.rs
This fixes the new lints introduced in Rust 1.84.0.
> Fix new clippy lints.

- CHANGELOG.md
- java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/ProtocolVersion.java
- java/client/src/main/java/glide/managers/ConnectionManager.java
- java/client/src/test/java/glide/managers/ConnectionManagerTest.java
- java/integTest/src/test/java/glide/ConnectionTests.java
- java/integTest/src/test/java/glide/PubSubTests.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
- java/integTest/src/test/java/glide/standalone/TransactionTests.java
- node/src/BaseClient.ts
- python/python/glide/config.py
And update tests
~Depends on #2381~
#2724
> Java: Add RESP2 support

- node/src/BaseClient.ts
- node/src/GlideClusterClient.ts
This Pull Request is linked to issue (URL): #2365 
> Node: refactor writeOrBufferCommandRequest (#2675)

- go/api/base_client.go
- go/api/generic_base_commands.go
- go/api/hash_commands.go
- go/api/hyperloglog_commands.go
- go/api/list_commands.go
- go/api/response_handlers.go
- go/api/response_types.go
- go/api/set_commands.go
- go/api/sorted_set_commands.go
- go/api/stream_commands.go
- go/api/string_commands.go
- go/integTest/shared_commands_test.go
- go/integTest/standalone_commands_test.go
Return `int64` instead of `Result[int64]` where possible. 
Few commands still return nullable `int64`, e.g. `ZRANK`
> Go: Fix return types, part 1: `int64` instead of `Result[int64]`

- go/api/base_client.go
- go/api/generic_base_commands.go
- go/api/hash_commands.go
- go/api/response_handlers.go
- go/api/response_types.go
- go/api/set_commands.go
- go/api/sorted_set_commands.go
- go/api/string_commands.go
- go/integTest/shared_commands_test.go
Return `float64` instead of `Result[float64]` where possible. 
Few commands still return nullable `float64`, but no commands return nullable bool
> Go: Fix return types, part 2: `float64` instead of `Result[float64]` and bool

- go/api/base_client.go
- go/api/glide_client.go
- go/api/list_commands.go
- go/api/response_handlers.go
- go/api/response_types.go
- go/api/server_management_commands.go
- go/api/string_commands.go
- go/benchmarks/glide_benchmark_client.go
- go/examples/main.go
- go/integTest/glide_test_suite_test.go
- go/integTest/shared_commands_test.go
- go/integTest/standalone_commands_test.go
Return `string` instead of `Result[string]` where possible. 
Few commands still return nullable `string`.
Also fixed null handling for few commands.
> Go: Fix return types, part 3: `string` instead of `Result[string]`

- utils/cluster_manager.py
Valkey changed template for `--version`
```
$ ./valkey-7.2.8 --version
Server v=7.2.8 sha=f6852069:0 malloc=jemalloc-5.3.0 bits=64 build=67cf89c66d1115f6
$ ./redis-7.2.3 --version
Redis server v=7.2.3 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=9b0796a828280810
$ ./valkey-8 --version
Valkey server v=8.0.0 sha=2b5c7a0d:0 malloc=jemalloc-5.3.0 bits=64 build=3c5eadb1cbf9fac2
```
Need to adopt script, otherwise it crashes all CI on version 7.2
```
Traceback (most recent call last):
File "/mnt/c/GitHub/babushka/utils/./cluster_manager.py", line 1257, in <module>
main()
File "/mnt/c/GitHub/babushka/utils/./cluster_manager.py", line 1193, in main
servers = create_servers(
^^^^^^^^^^^^^^^
File "/mnt/c/GitHub/babushka/utils/./cluster_manager.py", line 472, in create_servers
start_server( …
```
> Fix `cluster_manager` script

- go/api/base_client.go
- go/api/options/constants.go
- go/api/options/zscan_options.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2878
> Go: Add command ZScan

- .github/workflows/ort.yml
- CHANGELOG.md
- java/.ort.yml
- java/benchmarks/build.gradle
- java/build.gradle
- java/client/build.gradle
- java/integTest/build.gradle
```
./gradlew publishToMavenLocal
```
publishes package to the local maven cache using default version:
```sh
$> ls -1 ~/.m2/repository/io/valkey/valkey-glide/255.255.255/
valkey-glide-255.255.255-javadoc.jar
valkey-glide-255.255.255-linux-x86_64.jar
valkey-glide-255.255.255-sources.jar
valkey-glide-255.255.255.module
valkey-glide-255.255.255.pom
```
There are these files:
[valkey-glide-255.255.255.module.txt](https://github.com/user-attachments/files/18382435/valkey-glide-255.255.255.module.txt)
[valkey-glide-255.255.255.pom.txt](https://github.com/user-attachments/files/18382436/valkey-glide-255.255.255.pom.txt)
[valkey-glide-255.255.255-javadoc.zip](https://github.com/user-attachments/files/18382437/valkey-glide-255.255.255-javadoc.zip) …
> Java: Shadow protobuf dependency

- go/api/base_client.go
- go/api/options/zrange_options.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2878
> Go: Add commands ZRemRangeByRank/ZRemRangeByScore/ZRemRangeByLex

- go/api/base_client.go
- go/api/options/stream_options.go
- go/api/response_handlers.go
- go/api/response_types.go
- go/api/stream_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2881
> Go: XAUTOCLAIM.

- go/api/base_client.go
- go/api/generic_base_commands.go
- go/api/hash_commands.go
- go/api/list_commands.go
- go/api/response_handlers.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
Fix return types for commands which return arrays.
\+ fix couple of comments left which return strings.
> Go: Fix return types, part 6

- go/api/base_client.go
- go/api/glide_client.go
- go/api/hash_commands.go
- go/api/list_commands.go
- go/api/response_handlers.go
- go/api/server_management_commands.go
- go/api/set_commands.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
- go/integTest/standalone_commands_test.go
Fix return in go client commands.
Fix maps and sets.
> Go: Fix return types, parn 5

- go/api/base_client.go
- go/api/options/stream_options.go
- go/api/stream_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2968
> Go: `XGROUP SETID`.

- CHANGELOG.md
- python/python/glide/__init__.py
- python/python/glide/async_commands/core.py
- python/python/tests/test_async_client.py
Implements the `IFEQ` option into the `SET` command. Tests were added on test_async_client.py. 
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2811
> Implemented IFEQ set command in python with tests

- .github/workflows/ort.yml
- node/.ort.yml
> ORT- Add resolutions for hybrid-node-tests and bump versions

- CHANGELOG.md
- java/client/src/main/java/glide/api/BaseClient.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3024
> Java: Fix lpopCount null handling

- java/client/src/main/java/glide/connectors/resources/Platform.java
This Pull Request is linked to issue (URL): #3006 
> Java: updating error message in thread pool supplier

- go/api/base_client.go
- go/api/options/constants.go
- go/api/options/weight_aggregate_options.go
- go/api/options/zinter_options.go
- go/api/sorted_set_commands.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2972
> Go: Add command zinter

- CHANGELOG.md
- java/client/src/main/java/glide/api/commands/StringBaseCommands.java
- java/client/src/main/java/glide/api/models/commands/SetOptions.java
- java/client/src/test/java/glide/api/GlideClientTest.java
This Pull Request is linked to issue (URL): [valkey-io/valkey-glide/issues/2811]
This pull Request is implemented the `IFEQ` option in the `SET` commamnd. Tests were added, and docstring to the command and the related method.
> SET IFEQ command implemented in Java + tests 

- CHANGELOG.md
- glide-core/redis-rs/redis/src/aio/mod.rs
- glide-core/redis-rs/redis/src/client.rs
- glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
- glide-core/redis-rs/redis/src/cluster_async/connections_logic.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_client.rs
- glide-core/redis-rs/redis/src/cluster_slotmap.rs
- glide-core/redis-rs/redis/tests/test_cluster_async.rs
- glide-core/src/client/mod.rs
- glide-core/src/client/standalone_client.rs
- glide-core/src/client/types.rs
- glide-core/src/protobuf/connection_request.proto
- glide-core/tests/test_standalone_client.rs
- node/src/BaseClient.ts
This Pull Request is linked to issue (URL): #2792 
> Core: Add AzAffinityReplicasAndPrimary Read Strategy

- CHANGELOG.md
- python/python/glide/config.py
- python/python/tests/test_config.py
- python/python/tests/test_read_from_strategy.py
This Pull Request is linked to issue (URL): #2792 
> Python: add AZAffinityReplicasAndPrimary ReadFrom strategy support

- CHANGELOG.md
- java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/ReadFrom.java
- java/client/src/main/java/glide/managers/ConnectionManager.java
- java/client/src/test/java/glide/managers/ConnectionManagerTest.java
- java/integTest/src/test/java/glide/ConnectionTests.java
> Java: Add AzAffinityReplicasAndPrimary Read Strategy

- node/tests/SharedTests.ts
#3061 
Flakiness is happening on ephemeral only, which has less compute power, so potentially having CPU throttling while running long tests suite.
Using the exact second for TTL, in case of throttling, might not be enough margin, and while the next command arrive to the server the second already changed. Note that we use exact, and not how long it will live, meaning in some cases the next second is just a few ms away.
-   [x] Create merge commit if merging …
> Fix flaky test set for more margine for ttl

- python/python/glide/__init__.py
- python/python/glide/async_commands/server_modules/json_batch.py
- python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): #3031 
> Python: rename modules transaction to batch

- go/api/base_client.go
- go/api/command_options.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2811
> Go: Add IFEQ to SetOptions

- CHANGELOG.md
- glide-core/telemetry/Cargo.toml
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3124
> Rust: Fix opentelemetry_sdk dependency

- CHANGELOG.md
- glide-core/telemetry/Cargo.toml
Backport #3123 to `release-1.3` branch.
> [Backport `1.3`] Rust: Fix opentelemetry_sdk dependency (#3123)

- .github/workflows/install-engine/action.yml
This commit https://github.com/valkey-io/valkey-glide/commit/890cffc882eb4281e80accadfa37f2446150fa74
removed the preparation of the sources for the non ephemeral self-hosted runner, where valkey directory is already exist. The assumption was that the non ephemeral runner will be deprecated. Since we decided to keep the CD workflows on the non ephemeral runner, the preparation on existing sources should be reintroduced
-   ~[ ] CHANGELOG.md and documentation files are …
> Fix engine builds on non ephemeral self hosted runner 

- .github/workflows/pypi-cd.yml
PyO3/maturin-action@v1 fails for ARM build due to aarch64-linux-gnu-gcc cannot be found in the docker.
Since the script uses quay.io/pypa/manylinux2014_aarch64:latest docker, the compiler name is probably changed to a more convenient gcc in the latest version
> Fix py-cd for ARM CD

- .github/workflows/install-engine/action.yml
Prepare Valkey sources is cloning the repo into a wrong directory
> Fix working directory for valkey sources

- .github/workflows/npm-cd.yml
- CHANGELOG.md
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3157
Backport of #3155 to `release-1.3`
> Node: Fix NPM CD tag on release-1.3

- .github/workflows/go-cd.yml
Backport #3146 to `release-1.3` branch.
> [Backport `1.3`] Go: Add Go CD approval (#3146)

- .github/workflows/go-cd.yml
- go/.cargo/config.toml
- go/api/base_client.go
- go/api/errors/errors.go
- go/api/glide_client.go
- go/api/glide_cluster_client.go
- go/api/response_handlers.go
Partially fixes #3177 (1, 2, 3, 4 and 6 from https://github.com/valkey-io/valkey-glide/issues/3177#issuecomment-2660623226, 5 remains unfixed)
Fix following errors:
```
ld: warning: ignoring duplicate libraries: '-lglide_rs', '-lm'
```
```
ld: warning: search path '/Users/runner/work/valkey-glide/valkey-glide/go/api/errors/../rustbin/aarch64-apple-darwin' not found
ld: warning: search path '/Users/runner/work/valkey-glide/valkey-glide/go/api/target/release' not found
```
```
ld: warning: search path '/Users/runner/work/valkey-glide/valkey-glide/go/target/release' not found
```
(visible if GLIDE go glide is taken from the repo)
```
ld: warning: object file (/Users/runner/work/valkey-glide/valkey-glide/go/target/release/libglide_rs.a....) was built for newer 'macOS' version (14.5) than …
```
> Go: fix ld warnings on macos

- .github/workflows/go-cd.yml
- go/Makefile
- go/api/base_client.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3177
> Go: Unify bianry path

- go/README.md
One of warning reported in #3177 remains unfixed. Adding `KNOWN ISSUES` section to readme with info about it.
See also #3178.
> Go: add known issues to readme

- glide-core/redis-rs/redis/src/cluster_async/connections_container.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_client.rs
- glide-core/redis-rs/redis/tests/support/mod.rs
- glide-core/redis-rs/redis/tests/test_cluster_async.rs
- glide-core/src/client/mod.rs
- python/python/tests/conftest.py
- python/python/tests/test_auth.py
**Core Changes:**
* Move refresh_connection to run as a tokio task in the background, eliminating blocking in poll_recover for Reconnect.
* Modify get_connection to intelligently wait on refresh operations so it won't send the command right away when the connection is removed when triggering a new refresh task.
**Triggering Refresh Task:**
- Removes the existing failed connection from the connection_map
- Triggering a new Tokio task to run in the background.
**Refresh Task Behavior:**
- Starting a new connection to the node
- Adding the connection into the connection_map
**New State Management:**
- Add refresh state tracking per address
- Introduce notifier mechanism that's triggered by the refreshing task after the first connection attempt
- New state enum for refresh operations:
* …
> [redis-rs][core] Move connection refresh to the background

- go/integTest/cluster_commands_test.go
https://github.com/valkey-io/valkey-glide/actions/runs/13419211709/job/37487583002#step:5:663
`DBSize` test fails if command was randomly routed to a node which has no keys (or it was flushed in a previous test).
Note: `RandomRoute` is used in that test.
> Go: Fix flaky test.

- CHANGELOG.md
- go/api/base_client.go
- go/api/options/zrange_options.go
- go/api/sorted_set_commands.go
- go/api/sorted_set_commands_test.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2972
> Go: Add command zlexcount

- .github/workflows/go-cd.yml
- .github/workflows/java-cd.yml
- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
Fixes the issue where running the CD workflows would result in this error - 
`Error when evaluating 'runs-on' for job 'publish-binaries'. .github/workflows/pypi-cd.yml (Line: 77, Col: 18): Unexpected value 'OS',.github/workflows/pypi-cd.yml (Line: 77, Col: 18): Unexpected value 'NAMED_OS',.github/workflows/pypi-cd.yml (Line: 77, Col: 18): Unexpected value 'RUNNER',.github/workflows/pypi-cd.yml (Line: 77, Col: 18): Unexpected value 'ARCH',.github/workflows/pypi-cd.yml (Line: 77, Col: 18): Unexpected value 'TARGET',.github/workflows/pypi-cd.yml (Line: 77, Col: 18): Unexpected value 'PACKAGE_MANAGERS',.github/workflows/pypi-cd.yml (Line: 77, Col: 18): Unexpected value 'run',.github/workflows/pypi-cd.yml (Line: 77, Col: 18): Unexpected value 'languages'`
example - …
> Fixes the RUNNER for the CD workflows 

- .github/workflows/pypi-cd.yml
This Pull Request is linked to issue (): [#3189 ]
> Add source distribution upload to the PyPi-cd workflow 

- python/src/lib.rs
For now, we temporarily suppress the useless conversion warnings until we get more information on what we need to change for upgrading to rust 1.85.
> Python: Temporarily suppress rust linter warnings

- python/python/tests/test_async_client.py
- python/python/tests/test_transaction.py
- python/src/lib.rs
Replaced old Python code that handled incompatible versions.
> Python: Added skip markers to tests

- python/dev_requirements.txt
- python/python/tests/utils/utils.py
This PR caches the server version to avoid redundant calls to `info` for other tests.
> Python: Cache server version

- csharp/tests/Integration/GetAndSet.cs
- csharp/tests/tests.csproj
- csharp/tests/xunit.runner.json
Without these changes, logs from tests were never printed.
To have logging in IT, use `ITestOutputHelper` which has `WriteLine` API similar to `Console.WriteLine`.
```diff
--- a/csharp/tests/Integration/GetAndSet.cs
+++ b/csharp/tests/Integration/GetAndSet.cs
@@ -7,8 +7,10 @@ using Glide;
using static Tests.Integration.IntegrationTestBase;
namespace Tests.Integration;
-public class GetAndSet : IClassFixture<IntegrationTestBase>
+public class GetAndSet(ITestOutputHelper output) : IClassFixture<IntegrationTestBase>
{
+    private readonly ITestOutputHelper _output = output;
+
private async Task GetAndSetValues(AsyncClient client, string key, string value)
{
Assert.Equal("OK", await client.SetAsync(key, value));
```
See xunit docs on https://xunit.net/docs/capturing-output and …
> C#: Fix tests logging.

- CHANGELOG.md
- go/api/base_client.go
- go/api/pinner.go
- go/api/pinner_old.go
- go/api/pinner_test.go
- go/integTest/glide_test_suite_test.go
- go/integTest/parallelized_test.go
This fixes https://github.com/valkey-io/valkey-glide/issues/3207 and makes the Go client deliver responses to the correct channels.
The current way of passing `uintptr(unsafe.Pointer)` to rust and back to Go is not safe for dereferencing. Go can still move the address.
Use [`runtime.Pinner`](https://pkg.go.dev/runtime#Pinner) or  `cgo.Handle` to pin the channel address before passing it to the rust.
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3207
-   [x] …
> Go: Fix channel passing from Go to Rust by using `runtime.Pinner` or `cgo.Handle`

- csharp/lib/glide.csproj
Fix IT failure on windows ([logs](https://github.com/Yury-Fridlyand/valkey-glide/actions/runs/13464806277/job/37628183568#step:5:208)):
```
System.DllNotFoundException : Unable to load DLL 'libglide_rs' or one of its dependencies: The specified module could not be found. (0x8007007E)
```
`cargo` on windows creates `glide_rs.dll`, while on other platforms `libglide_rs.*`. To align file name (not extension) I add file name fix. It [worked](https://github.com/Yury-Fridlyand/valkey-glide/actions/runs/13465016151/job/37628860553#step:5:201).
This Pull Request is linked to issue (URL): Fixes #3269
-   [x] …
> C#: Fix build on windows.

- .github/json_matrices/supported-languages-versions.json
- .github/workflows/go-cd.yml
- .github/workflows/go.yml
- go/Makefile
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3271
> Go: Update Go versions used in CI

- CHANGELOG.md
- go/api/base_client.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3219
> Go: fix data race on the coreClient with `sync.Mutex` and a channel map

- glide-core/redis-rs/README.md
- glide-core/redis-rs/redis/Cargo.toml
- glide-core/redis-rs/redis/tests/support/mod.rs
Adding option to print logs in redis-rs tests.
When running tests, you might want to see the logs from with-in redis-rs or glide.
In order to print logs, add `init_logger();` in the beginning of the needed test, and from then all logs will appear.
Note to run the test with **nocapture** and **RUST_LOG** with the needed log level:
e.g.: `RUST_LOG=debug cargo test --locked -p redis -- --nocapture --test-threads=1`
> Adding option to print logs in redis-rs tests

- README.md
Reverts valkey-io/valkey-glide#3262 and backports #3319
> Revert "Update readme - include compatibility notice"

- .github/workflows/java.yml
- java/DEVELOPER.md
- java/integTest/build.gradle
Now `./gradlew build` and `./gradlew :integTest:test` don't include pubsub IT.
To run it do `./gradlew :integTest:pubsubTest`
> Java: move pubsub IT to another suite

- java/integTest/build.gradle
- java/integTest/src/test/java/glide/TestConfiguration.java
Issue introduced by #2352 - modules test was starting clusters and tried to use them to get the version version. Connection was failing because TLS flag was set.
The actual fix is in `build.gradle`, but I also added verbose diagnostics and more accurate version checking in `TestConfiguration` init.
This Pull Request is linked to issue (URL): Fixes #3341
> Java: Fix version check in IT/MT startup.

- glide-core/redis-rs/redis-test/src/lib.rs
- glide-core/redis-rs/redis/src/aio/connection.rs
- glide-core/redis-rs/redis/src/aio/multiplexed_connection.rs
- glide-core/redis-rs/redis/src/cluster.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_async/pipeline_routing.rs
- glide-core/redis-rs/redis/src/cluster_pipeline.rs
- glide-core/redis-rs/redis/src/connection.rs
- glide-core/redis-rs/redis/src/parser.rs
- glide-core/redis-rs/redis/src/pipeline.rs
- glide-core/redis-rs/redis/src/types.rs
- glide-core/redis-rs/redis/tests/parser.rs
- glide-core/redis-rs/redis/tests/support/mock_cluster.rs
- glide-core/redis-rs/redis/tests/support/mod.rs
- glide-core/redis-rs/redis/tests/test_cluster_async.rs
- glide-core/src/client/value_conversion.rs
- glide-core/tests/utilities/mod.rs
- java/src/lib.rs
- node/rust-client/src/lib.rs
- python/src/lib.rs
This PR refactors the handling of `ServerError` by moving it into the `redis::Value` enum, which eliminates the need for the InternalValue type. This change simplifies error handling and lays the foundation for returning failed commands in batch operations without raising errors.
> Move ServerError into Value

- glide-core/redis-rs/redis/src/cluster.rs
- glide-core/redis-rs/redis/src/cluster_async/pipeline_routing.rs
- glide-core/redis-rs/redis/src/cluster_pipeline.rs
- glide-core/redis-rs/redis/src/cmd.rs
- glide-core/redis-rs/redis/src/pipeline.rs
- glide-core/src/client/mod.rs
This PR refactors the pipeline command handling by replacing direct Cmd instances with Arc<Cmd>. Previously, commands were frequently cloned due to being used in multiple places, leading to unnecessary allocations. Using Arc allows for efficient shared ownership, reducing memory overhead and improving performance.
This change is part of the ongoing work on pipelines and is targeted at the pipelines-target-branch, as the pipeline implementation is still in progress.
This Pull Request is linked to issue (URL): #3237 
-   [ ] CHANGELOG.md and documentation files are …
> Refactor command handling to use Arc<Cmd> for pipelines

- csharp/lib/src/lib.rs
- go/src/lib.rs
Use `Arc` instead of `Box` to wrap the `ClientAdapter`, so that the lifetime of the adapter will be extended even in cases where the client is closed during commands. This also saves on using `as usize` conversions to the pointer, which cause provenance to be lost and might lead to undefined behavior.
The memory cost of this change is increasing the allocation of the client by one pointer size, and the runtime cost is 4 atomic increments/decrements per command. 
-   [ ] Destination branch is correct - main or …
> Safer wrapping for FFI clients.

- node/tests/TestUtilities.ts
This PR fixes an issue with a flaky field in the `xpendingWithOptions` test and introduces a new function that can be used for future flaky tests.
This Pull Request is linked to issue (URL): #3066 #3327 
> Node: Fix `xpendingWithOptions` Flaky Test

- node/src/server-modules/GlideJson.ts
This PR fixes incorrect documentation for the `GlideJson.get` method. 
The original example was missing the `client` parameter and contained syntax errors, including an extra parenthesis and incorrect object structure.
- Updated examples to include `client` as the first argument.
- Removed extra parentheses.
- Fixed incorrect formatting in the multi-path JSON retrieval example.
This Pull Request is linked to issue ([URL](https://github.com/valkey-io/valkey-glide/issues/2911)): [2911]
- Please review if the updated example aligns with the expected method behavior.
- Let me know if any additional clarifications are needed.
-   [Yes] This Pull Request is related to one issue.
-   [Yes] Commit message has a detailed description of …
> Fix documentation for GlideJson.get method

- csharp/lib/Cargo.toml
Connections to a cluster with TLS were failing with
```
thread '<unnamed>' panicked at src/lib.rs:51:68:
called `Result::unwrap()` on an `Err` value: Cluster(Failed to create initial connections - IoError: Failed to refresh both connections - IoError: Node: "clustercfg.memorydb-01.nra7gl.memorydb.us-east-1.amazonaws.com:6380" received errors: `invalid peer certificate: UnknownIssuer`, `invalid peer certificate: UnknownIssuer`)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:223:5:
panic in a function that cannot unwind
```
With this fix (copied from go client) it doesn't fail anymore.
> C#: Fix TLS

- go/integTest/glide_test_suite_test.go
- go/integTest/shared_commands_test.go
> Go: Add bulk args test

- CHANGELOG.md
- go/api/base_client.go
- go/api/generic_base_commands.go
- go/api/update_connection_password_test.go
- go/integTest/cluster_commands_test.go
- go/integTest/standalone_commands_test.go
- go/src/lib.rs
This Pull Request is linked to issue (URL):https://github.com/valkey-io/valkey-glide/issues/3268
> Go: Add support for updating connection password

- .github/workflows/csharp.yml
Without creating a `global.json`, dotnet didn't use correct version of SDK on mac runners.
> C#: CI - fix dotnet installation on mac runners

- .github/workflows/csharp.yml
- .github/workflows/go.yml
- .github/workflows/java.yml
- .github/workflows/node.yml
- .github/workflows/python.yml
This PR updates the GitHub Actions workflow for python pub sub test to improve debugging by printing the full matrix configuration in the logs for each job. 
The previous job name was truncated, making it hard to track matrix parameters used in each job. This change ensures that the full matrix configuration is printed to the logs.
- Added a step to output the full matrix configuration to the logs using `toJson(matrix)`.
- Trimmed the job header with Language Version, Engine version and TARGET
- Above changes are done for Python, node, Go, CSharp, Java WF
This Pull Request is linked to issue ([URL](https://github.com/valkey-io/valkey-glide/issues/3398)): [3398]
- Please review if the updated example aligns with the requirement.
- Let me know if any additional clarifications are needed. …
> Fix: Update CI Job names with required config params

- README.md
Moved Known Issues section to wiki page: https://github.com/valkey-io/valkey-glide/wiki/Known-Issues
> Doc: Move Known Issues from README.md to wiki

- glide-core/redis-rs/redis/src/aio/multiplexed_connection.rs
- glide-core/redis-rs/redis/src/client.rs
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/src/client/mod.rs
- glide-core/src/client/reconnecting_connection.rs
- glide-core/src/client/standalone_client.rs
- java/integTest/src/test/java/glide/TestUtilities.java
- java/integTest/src/test/java/glide/cluster/ClusterClientTests.java
- java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java
- node/tests/AuthTest.test.ts
- python/python/tests/conftest.py
- python/python/tests/test_auth.py
- python/python/tests/utils/utils.py
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/3289
This PR fixes the update connection password to add the username as arg in `update_connection_password(immediateAuth = True)`  (i.e. send "AUTH [username] [password]")  in case username was configured in ServerCredentials during client creation.
Currently, only "AUTH [password]" is sent.
Additionally, it fixes the implementation of `update_connection_password` in CMD - previously, the updated password would be saved only in the multiplexed_connection struct, and then upon disconnection the authentication would still be with the old password. Now, the password is updated in the `ReconnectingConnection` struct which is used in reconnecitons.
NOTES- 
- Deleting the user with …
> Authentication: Fix immediate update_connection_password to use username

- node/tests/TestUtilities.ts
This PR re-enables `xpendingWithOptions` which was accidentally left disabled when the flakiness fix was merged.
This Pull Request is linked to issue (URL): #3327 
> Node: Re-enable `xpendingWithOptions` in Transaction Tests

- CHANGELOG.md
- go/api/base_client.go
- go/api/geospacial_commands.go
- go/api/geospacial_commands_test.go
- go/api/options/constants.go
- go/api/options/geoadd_options.go
- go/api/options/geosearch_options.go
- go/api/response_handlers.go
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3365
> Go: Add command `GeoSearch`

- utils/cluster_manager.py
When running the full matrix tests, we sometimes get a timeout error like: Timeout exceeded trying to wait for server 127.0.0.1:34011 to know all hosts. After this happens, lots of tests fail afterwards. This PR bumps up the value of retries which should give enough time for the clusters to be ready.
This Pull Request is linked to issue (URL): #3421 
> Node: Fix Cluster Manager Timeout

- .github/workflows/python.yml
Since the `Running Module Tests` job in Python CI has been hardcoded to run on self-hosted arm64 runner, the condition on the `sudo chown` command is no longer necessary.
> CI: Fix Python Module Tests

- .github/workflows/build-node-wrapper/action.yml
- .github/workflows/build-python-wrapper/action.yml
- .github/workflows/create-test-matrices/action.yml
- .github/workflows/install-engine/action.yml
- .github/workflows/lint-ts/action.yml
- .github/workflows/node-create-package-file/action.yml
- .github/workflows/node.yml
- .github/workflows/npm-cd.yml
- .github/workflows/run-ort-tools/action.yml
- .github/workflows/setup-musl-on-linux/action.yml
- .github/workflows/start-self-hosted-runner/action.yml
- .github/workflows/test-benchmark/action.yml
- .github/workflows/update-glide-version/action.yml
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3383
> CI: Address semgrep findings

- java/client/src/main/java/glide/api/models/commands/scan/ScanOptions.java
Fix small compiler warning
```
> Task :client:compileJava
.../glide/java/client/src/main/java/glide/api/models/commands/scan/ScanOptions.java:19: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@EqualsAndHashCode
```
> Java: Fix compiler warning

- csharp/sources/Valkey.Glide/BaseClient.cs
Minor change to help debugging tests. How we can track which exactly client is used in tests and how it was shared.
Before
```
Passed Valkey.Glide.IntegrationTests.SharedCommandTests.GetReturnsLastSet(client: GlideClient { }) [1 ms]
Passed Valkey.Glide.IntegrationTests.SharedCommandTests.GetReturnsLastSet(client: GlideClusterClient { }) [1 ms]
```
After
```
Passed Valkey.Glide.IntegrationTests.SharedCommandTests.GetReturnsLastSet(client: GlideClient { 0x7EE8DC022CA0 }) [2 ms]
Passed Valkey.Glide.IntegrationTests.SharedCommandTests.GetReturnsLastSet(client: GlideClusterClient { 0x7EE8DC024670 }) [2 ms]
```
> C#: Give client an ID

- .github/workflows/go-cd.yml
- .github/workflows/npm-cd.yml
- .github/workflows/pypi-cd.yml
Add `publish` checkbox for node and python CD.
When CD started manually, but with unchecked `publish`, it will do everything except actually publishing. It allows to test and verify changes in CI/CD pipelines without publishing dummy RCs.
Already implemented for go and java.
> CD: Add `publish` checkbox for node and python CD.

- utils/cluster_manager.py
This PR is aimed to fix the issue of node container tests failing, due to errors of case:
```
WARNING:root:Timeout exceeded trying to check if address already in use for server 127.0.0.1:xxxxx!
Traceback (most recent call last):
File "/__w/valkey-glide/valkey-glide/utils/cluster_manager.py", line 1256, in <module>
main()
File "/__w/valkey-glide/valkey-glide/utils/cluster_manager.py", line 1192, in main
servers = create_servers(
^^^^^^^^^^^^^^^
File "/__w/valkey-glide/valkey-glide/utils/cluster_manager.py", line 500, in create_servers
raise Exception(
Exception: Waiting for server 127.0.0.1:xxxxx to start exceeded timeout.
```
I ran a succesfull test with these changes, and the container tests seemed to pass:
https://github.com/valkey-io/valkey-glide/actions/runs/14440907860
This Pull …
> Fix: Add support for both musl and glibc error messages when checking port availability

- CHANGELOG.md
- glide-core/Cargo.toml
- glide-core/src/socket_listener.rs
Ensure the UDS socket filename is truly unique by appending a UUID as a suffix. This approach is preferred over relying solely on PID-based naming with manual file removal, as it avoids filesystem manipulation and eliminates the risk of collisions due to PID reuse such as docker usage.
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/2985
-   ~[ ] Tests are added or updated.
-   [X] Create merge commit if merging release branch into main, squash …
> Ensure the UDS socket filename is truly unique

- CHANGELOG.md
- go/api/glide_client.go
- go/api/glide_cluster_client.go
- go/api/scripting_and_function_cluster_commands.go
- go/api/scripting_and_function_commands_test.go
- go/api/scripting_and_function_standalone_commands.go
- go/integTest/cluster_commands_test.go
- go/integTest/standalone_commands_test.go
> Go: Add command FUNCTION DELETE

- benchmarks/csharp/Program.cs
As @jbrinkman noticed, benchmarking app crashes if `resultsFile` parameter has no directory path.
It fails when `resultsFile = "test.json"`, but doesn't fail when `resultsFile = "./test.json"`. This PR offers a fix.
> C#: benchmark fix

- CHANGELOG.md
- glide-core/src/socket_listener.rs
- utils/cluster_manager.py
In the Full Matrix Tests, We encountered errors on macOS instances, that clusters couldn't be created in the node client.
You can see such errors in this [run](https://github.com/valkey-io/valkey-glide/actions/runs/14483970827/job/40626124407)
Thus, we realized that on macOS instances, the UDS socket filename is too long when using the base directory.
So, our solution is to save the filename in the tmp dir, and to restrict it's permissions for security measures
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3441
-   [x] …
> Core: Move UDS Socket Filename to tmp 

- CHANGELOG.md
- benchmarks/rust/src/main.rs
ATM, the Rust benchmark latencies calculation was off, as it didn't sort the latencies vector before calculating the latencies. 
This Pull Request is linked to issue (URL): closes #3637
> Rust: Fix rust bench latencies calculation

- CHANGELOG.md
- go/api/glide_cluster_client.go
- go/integTest/cluster_commands_test.go
- go/integTest/readfrom_strategy_test.go
- java/client/src/main/java/glide/api/GlideClusterClient.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
> Fix custom command response handling

- node/src/Commands.ts
The comment for `keepExisting` is not included in the `Command.d.ts` declaration file.
https://www.runpkg.com/?@valkey/valkey-glide@1.3.2/build-ts/src/Commands.d.ts#51
Fixes https://github.com/valkey-io/valkey-glide/issues/3652
> Node: Fix comment for `keepExisting` in `SetOptions`

- java/integTest/src/test/java/glide/SharedCommandTests.java
Reduce data size on scan tests and small fix for `zscan_binary` to solve issue of `RESP2` flakily timing out on some Java CI runs.
This Pull Request is linked to issue (URL): #3597 
> Java: Prevent Scan Tests from Timing Out

- CHANGELOG.md
- go/api/base_client.go
- go/api/response_handlers.go
- go/api/sorted_set_commands.go
- go/api/sorted_set_commands_test.go
- go/integTest/shared_commands_test.go
This PR fixes the issue of using maps (unordered) in Go to return the result from `ZRangeWithScores`.
This Pull Request is linked to issue (URL): #3639 
> Go: Fix `ZRangeWithScores` Order

- go/Makefile
This PR enables AddressSanitizer (ASAN) for integration tests for the Go client.
ASAN doesn't find any issues in our current integration tests.
To verify this change, I made a temporary modification to our Rust FFI layer, in which we dereference a synthesized pointer without proper provenance:
```
let a: *const u32 = 24 as *const u32;
println!("{}", unsafe { *a });
```
Re-running `make integ-test` with these changes causes ASAN to pipe up with the following report:
```
==59610==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x00010d628365 bp 0x70001675aea0 sp 0x70001675a580 T3)
==59610==The signal is caused by a READ memory access.
==59610==Hint: address points to the zero page.
#0 0x00010d628365 in command+0x35 (integTest.test:x86_64+0x1006d3365)
#1 0x00010d49345f in …
```
> Go: Enable AddressSanitizer in integration tests

- java/integTest/src/test/java/glide/SharedCommandTests.java
This PR addresses the issue where we were doing a regular `zscan` without acknowledging the fact that members `{ a b c d e }` may have been added beforehand causing the test to fail when asserting that each retrieved member needed to contain the string `"member"`.
Full matrix run (with Java 21 support): https://github.com/valkey-io/valkey-glide/actions/runs/14844001245
This Pull Request is linked to issue (URL): 
-   [x] Create merge commit if merging …
> Java: Fix flaky `zscan` and `zscan_binary`

- .github/workflows/pypi-cd.yml
- python/python/glide/glide_client.py
This Pull Request is linked to issue #3553 
This PR - 
1. updates the pypi-cd workflow to build pypy wheels and publish them
2. changes the use of `sys,getsizeof()` to `len()` in `glide_client.py` since pypy doesn't support `sys,getsizeof()` (Tested - they return more or less the same value's for big sizes, +-100bytes of difference). 
3. Fixes the cd workflow to use the given version when testing the rc.
-   [x] Create merge commit if merging release branch …
> Python: added pypy support to pypi cd

- .github/workflows/install-shared-dependencies/action.yml
This change fixes an issue where CI test runs on Amazon Linux 2 fail, as seen in this test run:
https://github.com/valkey-io/valkey-glide/actions/runs/14934337857/job/41958100815#step:8:654
This Pull Request is linked to issue (URL): 
https://github.com/valkey-io/valkey-glide/issues/3709
https://github.com/valkey-io/valkey-glide/issues/3650
> Add libasan to AL2 installed dependencies for CI

- CHANGELOG.md
- java/client/build.gradle
- java/integTest/build.gradle
Bump netty to address secutiry issues
1. CVE-2025-24970 / GHSA-4g8c-wm8x-jfhw
2. CVE-2025-25193 / GHSA-389x-839f-4rhx
See also https://mvnrepository.com/artifact/io.valkey/valkey-glide/1.3.2
> Java: Bump `netty`.

- java/client/src/main/java/glide/api/commands/GenericBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseBatch.java
The `wait` command clashes with Java's built-in `wait` method which may cause some confusion. This note allows users to be aware of this clash.
> Java: Add a note to `wait`

- CHANGELOG.md
- go/api/base_client.go
- go/api/connection_management_cluster_commands.go
- go/api/glide_client.go
- go/api/glide_cluster_client.go
This Pull Request is linked to issue (URL): #3807
> Go: Remove redundant implementations of echo

- .github/workflows/pypi-cd.yml
- .github/workflows/python.yml
- .gitignore
- python/Cargo.toml
- python/dev_requirements.txt
- python/pyproject.toml
Bump the `maturin` version to current stable, and fix the bad `sed` version match in the release CI introduced in https://github.com/valkey-io/valkey-glide/pull/3795. 
> Python: bump package build tooling

- .github/workflows/mkdocs-deploy.yml
- docs/README.md
- docs/markdown/python/base_batch.md
- docs/markdown/python/cluster_batch.md
- docs/markdown/python/cluster_transaction.md
- docs/markdown/python/standalone_batch.md
- docs/markdown/python/standalone_transaction.md
- docs/mkdocs.yml
This Pull Request is linked to issue: #3882 
This PR partially addresses the issue by:
Changing the documentation deployment workflow to trigger only via workflow_dispatch, and restricting it to branches starting with release-*.
Adding notes indicating that transaction is deprecated and that Batch is coming soon in version 2.0.0.
Currently, the documentation is deployed from main, but the release-1.3 branch doesn't include the website structure at all. This creates a situation where including full docs for transaction would require merging all site additions into release-1.3—which is a relatively large effort given that the 2.0.0 release is imminent.
As a result, the docs are currently incomplete (missing transaction), but at least they’re not misleading. After merging this PR, we can …
> Docs: fixed mkdocs workflow trigger, fixed transaction/batch sections

- glide-core/redis-rs/redis/tests/test_cluster_async.rs
Added a test to show the current impl. of the data path is blocked on the refresh slot process - Head of the line blocking.
This Pull Request is linked to issue (URL): #3851
> Added head of the line blocking test for refresh slot

- .github/workflows/go-cd.yml
- CHANGELOG.md
- ffi/.cargo/config.toml
- ffi/DEVELOPER.md
- go/Makefile
- go/integTest/shared_commands_test.go
This Pull Request is linked to issue: #3904
This PR modifies go makefile to use custom `lib-name` and `lib-ver` identifiers (defines how the client identifies it's client version to the server and appear in the CLIENT INFO output). The name is "GlideGo" and version "unknown", and the version is overriden while publishing a package in go-cd to the actual published version. Previously, these identifiers were taken from the glide-ffi `config.toml` file, which would give them a "GlideFFI" name and version "0.1.0", which is not indicative of the actual package. 
I left the `config.toml` file in the ffi dir there for now, so that running `cargo build` from the ffi dir would still be possible.
-   [x] This Pull Request is related to …
> Go: add client library name and version identifiers

- ffi/src/lib.rs
- go/api/callbacks.go
Free error string right after the callback.
> Go: Rework how error strings are freed.

- CHANGELOG.md
- glide-core/src/scripts_container.rs
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
- node/rust-client/src/lib.rs
- node/tests/SharedTests.ts
- python/tests/test_async_client.py
Scripts are now stored with a reference counter, and only removed from the local container when the count reaches zero. This allows multiple instances of the same script (with identical code) to coexist safely.
Added test to all wrappers that verifies a script is not removed from the local container while another instance with the same hash is still active, even after the original reference is released and the server-side cache is flushed.
This Pull Request is linked to issue (URL): Closes https://github.com/valkey-io/valkey-glide/issues/3902
-   [x] CHANGELOG.md and …
> Core: Added reference counting to the Script container to support multiple instances

- go/Makefile
Running unit-test locally would return Makefile Error 141 (which I think stems from the command treating `utils` as a different package. This patch makes it work on both CI and local testing.
```bash
~ make unit-test
mkdir -p reports
set -o pipefail; \
go test -v ./... -skip 'Example|TestGlideTestSuite'  \
| tee >(go tool test2json -t -p github.com/valkey-io/valkey-glide/go/v2 utils | go-test-report -o reports/unit-tests.html -t unit-test > /dev/null)
make: *** [unit-test] Error 141
```
This Pull Request is linked to issue (URL): #3960 
-   [ ] CHANGELOG.md and …
> Go: Fix Makefile Path for Unit Test

- node/src/BaseClient.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
> Node: move BackoffStrategy configuration to BaseConfiguration + Added Jitter param

- CHANGELOG.md
- java/client/src/main/java/glide/api/models/configuration/AdvancedBaseClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/AdvancedGlideClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/AdvancedGlideClusterClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/GlideClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/GlideClusterClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/TlsAdvancedConfiguration.java
- java/client/src/main/java/glide/managers/ConnectionManager.java
- java/client/src/test/java/glide/managers/ConnectionManagerTest.java
- java/integTest/src/test/java/glide/ConnectionTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3376
> Java: implement support for using insecure TLS

- python/python/glide/sync/glide_client.py
- python/tests/sync_tests/test_sync_client.py
This Pull Request is linked to issue : #239 
-   [] CHANGELOG.md and documentation files are updated.
> Add sync multiprocess support

- python/python/glide/__init__.py
- python/python/glide/commands/async_commands/core.py
- python/python/glide/commands/core_options.py
- python/python/glide/config.py
- python/python/glide/glide_client.py
- python/tests/async_tests/test_pubsub.py
Currently, PubSubMsg is found under the async_commands/core.py file, so it doesn't allow reusing it and seperating the sync and async modules as required. This PR places the ground work for splitting the sync and async python client builds.
> Python: Move PubSubMsg into a shared file

- python/python/glide/__init__.py
- python/python/glide/commands/async_commands/core.py
- python/python/glide/commands/core_options.py
- python/python/glide/config.py
- python/python/glide/exceptions.py
- python/python/glide/glide_client.py
- python/python/glide/sync/glide_client.py
- python/tests/async_tests/test_pubsub.py
- python/tests/sync_tests/test_sync_client.py
- python/tests/test_api_export.py
Contains two changes (separated by commit):
1. move get_request_error_class to a shared location
2. Change the client internal fields to private
This PR places the ground work for splitting the sync and async python client builds.
Rebased over #3998 
> Python/sync: Cleanup the sync client

- go/integTest/cluster_commands_test.go
- go/integTest/glide_test_suite_test.go
- go/integTest/pubsub_basic_test.go
- go/integTest/pubsub_commands_test.go
- go/integTest/readfrom_strategy_test.go
- go/integTest/shared_commands_test.go
- go/integTest/standalone_commands_test.go
- Replaced assert statements with require statements in multiple test files for better error handling.
- Modified CreatePubSubReceiver calls to include the testing context.
- Ensured proper error handling when creating clients in standalone and routing tests.
These changes were needed to ensure that client creation errors would properly terminate an integration test to prevent panics in tests from trying to execute commands on a nil reference. Errors needed to be surfaced so that the proper testing context could be skipped in the case of Sub-tests, allowing other sub-tests to be executed.
This Pull Request is linked to issue (#3704):
-   [x] Commit message has a detailed …
> Go: Refactor integration tests to use require assertions

- go/integTest/batch_test.go
Adding Generic Cluster Commands Tests (only look at `batch_test.go`)
> Go: Add Batch Generic Cluster Commands Tests

- .github/workflows/rust.yml
- CHANGELOG.md
- glide-core/redis-rs/redis/Cargo.toml
- glide-core/redis-rs/redis/src/cluster_async/mod.rs
- glide-core/redis-rs/redis/src/cluster_async/pipeline_routing.rs
- glide-core/redis-rs/redis/src/parser.rs
- glide-core/redis-rs/redis/tests/test_cluster_async.rs
- glide-core/src/socket_listener.rs
- glide-core/telemetry/Cargo.toml
- glide-core/telemetry/src/open_telemetry.rs
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3812 , https://github.com/valkey-io/valkey-glide/issues/3629
* Set Spans status to `ok` and `Error` according to the request's result.
Test for `set_status` options.
* Add metrics of `moved` and `retry_attempt`.
Tests for the new metrics recorded on regular command, atomic pipepline, and non atomic pipeline.
- If `moved` happend it will record `retry` and `moved` metrics. 
- If different `retry` it will record only `retry` metric
-   [x] CHANGELOG.md and documentation files are …
> Opentelemetry - set status, moved counter, retry_attempts counter 

- .github/workflows/go.yml
- CHANGELOG.md
- ffi/src/lib.rs
- ffi/tests/ffi_client_tests.rs
- go/Makefile
- go/base_client.go
- go/integTest/glide_test_suite_test.go
- go/integTest/opentelemetry_test.go
- go/internal/opentelemetry/opentelemetry.go
- go/opentelemetry.go
old PR closed to re-target at main: https://github.com/valkey-io/valkey-glide/pull/3834/
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3531
> Go: Add otel support

- node/src/BaseClient.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
- node/tests/TestUtilities.ts
- node/tests/TlsTest.test.ts
- node/tsconfig.json
- utils/TestUtils.ts
This Pull Request is linked to issue https://github.com/valkey-io/valkey-glide/issues/3376
Expose TlsMode::Insecure client option for the node wrapper using advanced config.
TLS state defaults to secured. When using this option, the client will bypass certificate verification, allowing connections to Valkey/Redis instances with self-signed or otherwise unauthorized certificates. This option is intended for local development or testing environments where a valid certificate may not be available. It is not recommended for production use, as disabling certificate validation exposes the connection to potential security risks such as man-in-the-middle attacks.
-   [x] Commit message …
> Node Wrapper - Support TLS insecure

- glide-core/redis-rs/redis/src/aio/multiplexed_connection.rs
- go/config/config.go
- java/README.md
- java/client/src/main/java/glide/api/models/configuration/AdvancedBaseClientConfiguration.java
- java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java
- node/README.md
- node/src/BaseClient.ts
- python/README.md
- python/python/glide/config.py
This pull request includes updates to improve timeout configurations across multiple client implementations and examples, as well as a modification to the default connection timeout in the Redis library. The most important changes are grouped below by theme.
* Added a `requestTimeout` parameter with a recommended value of 500ms to the `GlideClient` and `GlideClusterClient` examples in the Java documentation (`java/README.md`). [[1]](diffhunk://#diff-0c997611c3c5fb9fa0641cb88e5aaa485b5fbc7293676fc28afab310dd430812R219-R220) [[2]](diffhunk://#diff-0c997611c3c5fb9fa0641cb88e5aaa485b5fbc7293676fc28afab310dd430812R271-R272)
* Added a `requestTimeout` parameter with a recommended value of 500ms to the `GlideClient` and `GlideClusterClient` examples in the Node.js documentation …
> Increase default connection attempt timeout to 2000ms

- CHANGELOG.md
- go/base_client.go
- go/geospacial_commands_test.go
- go/integTest/shared_commands_test.go
- go/internal/interfaces/geospacial_commands.go
- go/pipeline/base_batch.go
Supersedes #4098 with was messed up by mistake
`GeoHash` returns an array which contains strings and/or nulls.
This Pull Request is linked to issue (URL): closes #4097 
> Go: Fix `GeoHash` Return Type to include Nillable Strings

- CHANGELOG.md
- java/client/src/main/java/glide/api/models/commands/FT/FTSearchOptions.java
- java/integTest/src/test/java/glide/modules/VectorSearchTests.java
This Pull Request is linked to issue: #4064 
There was a bug with the `lombok` handling in `FTSearchOptions` - to my understanding, setting a field with @Builder.default doesn't automatically initialize the field from the beginnig. What it does is, only when `build()` is called, checks the `field$set` flag, if it's set (meaning the generated `identifiers` setter was called), it takes the set value, otherwise it takes the default value that was defined. Before `build()` is called, the field is null.
So what happened was -  because we call `addReturnField` before `build()`, it was still null. 
The fix includes - 
- add a custom `FTSearchOptionsBuilder` builder that sets the identifiers field new a new hashMap (in order for it not to be null)
- add a custom `identifiers` setter that makes …
> Java: fix addReturnField in FT.search 

- .github/workflows/full-matrix-tests-sweeper.yml
- .github/workflows/full-matrix-tests.yml
Currently the full matrix tests can be scheduled only for main branch.
This PR utilizes the ORT sweeper technique to allow scheduling for different branches. 
> Allow scheduling of full matrix tests for different branches

- .github/workflows/full-matrix-tests-sweeper.yml
- .github/workflows/full-matrix-tests.yml
- .github/workflows/go.yml
- .github/workflows/java.yml
- .github/workflows/node.yml
- .github/workflows/python.yml
Currently modules tests will run unconditionally on workflow_dispatch trigger.
The introduction of full-matrix-tests-sweeper.yml requires explicit parameter for running the modules tests, since the sweeper being triggered by cron, triggers the CI tests via workflow_dispatch event.
> Add explicit run-modules-tests parameter to workflow_dispatch trigger of CI tests

- CHANGELOG.md
- ffi/src/lib.rs
- go/.gitignore
- go/base_client.go
- go/callbacks.go
- go/config/config_test.go
- go/config/request_routing_config.go
- go/constants/constants.go
- go/errors.go
- go/errors/errors.go
- go/glideErrors/errors.go
- go/glide_client.go
- go/glide_cluster_client.go
- go/integTest/batch_test.go
- go/integTest/cluster_commands_test.go
- go/integTest/connection_test.go
- go/integTest/glide_test_suite_test.go
- go/integTest/shared_commands_test.go
- go/integTest/standalone_commands_test.go
- go/integTest/vss_module_test.go
- go/internal/utils/transform_utils.go
- go/opentelemetry.go
- go/options/bitop_options.go
- go/options/command_options.go
- go/pipeline/base_batch.go
- go/pipeline/batch.go
- go/response_handlers.go
Supersedes #4090
* Convert Batch errors to `[]error`
* Implement custom `BatchError` to defer formatting batch error message until needed.
* Fix error messages to follow idiomatic Go guideline: start with lowercase letters and don't end with punctuation.
This PR is dependent on #3989 
This Pull Request is linked to issue #4031
> Go: Use errors idiomatically

- CHANGELOG.md
- go/base_client.go
- go/generic_base_commands_test.go
- go/integTest/batch_test.go
- go/integTest/shared_commands_test.go
- go/internal/interfaces/generic_base_commands.go
- go/internal/interfaces/stream_commands.go
- go/pipeline/base_batch.go
- go/stream_commands_test.go
It makes more sense to keep it consistent for all the commands. By using `time.Duration` we make the commands more readable and easier for the user.
Modified Commands:
- Expire
- ExpireWithOptions
- ExpireAt
- ExpireAtWithOptions
- PExpire
- PExpireWithOptions
- PExpireAt
- PExpireAtWithOptions
- Restore
- RestoreWithOptions
- Wait
- XAutoClaim
- XAutoClaimWithOptions
- XAutoClaimJustId
- XAutoClaimJustIdWithOptions
- XClaim
- XClaimWithOptions
- XClaimJustId
- XClaimJustIdWithOptions
This Pull Request is linked to issue (URL): #4070, closes #4006
-   [x] CHANGELOG.md …
> Go: Modifying Commands to use `time.Duration`

- .github/workflows/go-cd.yml
When the recent restructuring was done, the protobuf path in the CD pipeline was not updated to match the new location.
This Pull Request is linked to issue (#4148)
> fix: resolve broken protobuf path

- CHANGELOG.md
- go/base_client.go
- go/integTest/shared_commands_test.go
- go/internal/interfaces/stream_commands.go
- go/stream_commands_test.go
`XAdd` can never return null/nil when there is no optional arguments provided, updating the return type accordingly
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4070
> Fix XAdd return type with no optional args

- benchmarks/install_and_test.sh
The problem was caused by improper bash parameter quoting in the install_and_test.sh script. The $concurrentTasks variable contains space-separated values ("1 10 100 1000"), and without proper quoting, bash was splitting the command line incorrectly, causing parameter misalignment.
> Go: fix go benchmark parameter format

- python/tests/test_opentelemetry.py
This PR fixes OTel tests memory checks in python, which were flaky (see - https://github.com/valkey-io/valkey-glide/actions/runs/15573227804/job/43858277697). It changes it from testing that a threshold of 10 Mb increase in memory is not crossed, to testing that there's no more than 10% increase, which is aligned with the other tests and with the equivalent tests in the other wrappers.
-   [x] Create merge commit if merging release branch into main, squash …
> Python: fix flaky Open Telemetry memory checks

- go/base_client.go
- go/pipeline/base_batch.go
- java/client/src/main/java/glide/api/commands/ListBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseBatch.java
- node/src/BaseClient.ts
- node/src/Batch.ts
- python/python/glide/async_commands/batch.py
- python/python/glide/async_commands/core.py
Description of count param should be in params section. This applies to all the clients
```go
// Removes the first count occurrences of elements equal to element from the list stored at key.
// If count is positive: Removes elements equal to element moving from head to tail.
// If count is negative: Removes elements equal to element moving from tail to head.
// If count is 0 or count is greater than the occurrences of elements equal to element, it removes all elements equal to
// element.
//
// See [valkey.io] for details.
//
// Parameters:
//
//	ctx     - The context for controlling the command execution.
//	key     - The key of the list.
//	count   - The count of the occurrences of elements equal to element to remove.
//	element - The element to remove from the list.
```
This Pull …
> Fix `LREM` Count Parameter Docs

- java/client/src/main/java/glide/api/BaseClient.java
Command `xpendingWithOptions` returns an array of few items, but code has `handleArrayOrNullResponse`
Even in the case where there's nothing pending, we will still get an array of some sort (NOT `null`). Thus, this handler partially makes sense here and should be changed
> Java: Change Response Handler for `xpending`

- java/client/src/main/java/glide/api/BaseClient.java
Go:
```go
// Return value:
//
//	Array of elements as models.Result[string] in the specified range
```
but return value is 
```go
([]string, error)
```
Node: returns `GlideString[]`, python too
Java: `handleArrayOrNullResponse` (e.g. array or null, not array of nullables).
It shouldn't be possible to have a null inside the return value, so we need to fix the docs for the Go client.
-   [x] Create merge …
> Go: Fix `LRange` Docs Return Type

- go/integTest/batch_test.go
Add version check for [`SCRIPT SHOW`](https://valkey.io/commands/script-show/) command in batch tests. It was [failing](https://github.com/valkey-io/valkey-glide/actions/runs/15598722134/job/43934630822#step:7:748) on servers < 8
This Pull Request is linked to issue (URL): #4070
> Fix `SCRIPT SHOW` in batch test.

- go/batch_test.go
Fix batch example tests https://github.com/valkey-io/valkey-glide/actions/runs/15640000268/job/44064842032#step:8:47
Initially, timeout was in ms, but later it was changed to `time.Duration` where units are ns.
This Pull Request is linked to issue (URL): #4070
> Go: Fix batch examples.

- CHANGELOG.md
- go/base_client.go
- go/integTest/shared_commands_test.go
- go/internal/interfaces/sorted_set_commands.go
- go/sorted_set_commands_test.go
Command returns a nil or int, but doc doesnt say when null is returned.
In reality, `ZAddIncr` without options will **never** return `nil`. This aligns with the Java client's implementation. We should update it to reflect this fact.
https://github.com/valkey-io/valkey-glide/blob/184772bdf65d2eae723d8f2dba8e224a1b21069d/java/client/src/main/java/glide/api/BaseClient.java#L2059-L2067
-   [x] Create merge …
> Go: Fix `ZAddIncr` Return Type

- go/base_client.go
- go/config/config.go
- go/glide_client.go
- go/glide_cluster_client.go
- go/pipeline/base_batch.go
Need to fix links to other classes in docs.
For example, [BLMOVE](https://pkg.go.dev/github.com/valkey-io/valkey-glide/go@v1.3.0-rc4/api#GlideClient.BLMove): ListDirection should be clickable. Description also has a mistake.
[BZPOPMIN](https://pkg.go.dev/github.com/valkey-io/valkey-glide/go@v1.3.0-rc4/api#GlideClient.BZPopMin) - link to ZMPopMindoesn’t work, link to wiki too.
[BitField](https://pkg.go.dev/github.com/valkey-io/valkey-glide/go@v1.3.0-rc4/api#GlideClient.BitField) - no links in args.
We are able to link to other functions in the comments. This allows users to click on the related function directly allowing for a seamless experience.
This Pull Request is linked to issue (URL): #4070
-   [x] This Pull Request is …
> Go: Fix Linking to Other Commands in Docs

- CHANGELOG.md
- go/base_client.go
- go/integTest/shared_commands_test.go
- go/internal/converter_helpers.go
- go/internal/converters.go
- go/internal/interfaces/list_commands.go
- go/list_commands_test.go
- go/models/key_values.go
- go/models/response_types.go
- go/response_handlers.go
This PR updates the return type for List commands (`LMPop`, `LMPopCount`, `BLMPop`, `BLMPopCount`) to provide a more user-friendly response structure. This change is part of the initiative to return smart objects for commands with complex return types.
This Pull Request is linked to issue https://github.com/valkey-io/valkey-glide/issues/4144
> Go: Update return type for LMPop and related commands

- go/config/request_routing_config.go
- go/options/bitfield_options.go
- go/options/geosearch_options.go
- go/options/zrange_options.go
Fix interface collision for option types. Added few private dummy methods which protects versus misuse option types.
This Pull Request is linked to issue (URL): fixes #4142
> Go: Fix collision in option types.

- go/base_client.go
- go/pipeline/base_batch.go
- java/client/src/main/java/glide/api/commands/ListBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseBatch.java
- node/src/BaseClient.ts
- node/src/Batch.ts
- python/python/glide/async_commands/batch.py
- python/python/glide/async_commands/core.py
Doc says
```
Always `"OK"`.
If start exceeds the end of the list, or if start is greater than end, the result will be an empty list (which causes key to be removed).
```
Need to reword this. In all clients.
> Fix `LTRIM` Docs

- CHANGELOG.md
- go/base_client.go
- go/integTest/shared_commands_test.go
- go/internal/cmd.go
- go/internal/converter_helpers.go
- go/internal/interfaces/string_commands.go
- go/models/response_types.go
- go/response_handlers.go
- go/string_commands_test.go
This PR updates the return type for LCS commands to return strongly typed objects instead of raw responses, making the API more user-friendly and consistent with other commands. This addresses part of issue #4144, which aims to return smart and user-friendly objects/structs for commands with complex return types.
This Pull Request is linked to issue (#4144)
> Go: Return strongly typed object for LCS commands

- java/client/src/main/java/glide/api/commands/StreamBaseCommands.java
- java/client/src/main/java/glide/api/models/BaseBatch.java
In these two commands, it shouldn't be possible to return `null` since they don't have access to `count` so they won't be able to set it to a negative number.
This Pull Request is linked to issue (URL): #4239 
> Java: Fix Incorrect `XRANGE` `XREVRANGE` Return Docs

- .github/workflows/full-matrix-tests-sweeper.yml
Revert some changes from #4119 to run full matrix tests on main branch.
> CI: Run fill matrix on main.

- csharp/DEVELOPER.md
One small step is missing in the docs, and `dotnet test` would cause cluster manager to fail sometimes
This Pull Request is linked to issue (URL): closes #4228 
> C#: Fix `dotnet` Docs

- CHANGELOG.md
- node/src/BaseClient.ts
Adding the check in baseclient config so that an error is thrown when the readfrom strategy is specified to be AZAffinity, but a clientAZ is not present.
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4233
> Node: Validate clientAZ when using AZ affinity strategies

- .github/workflows/full-matrix-tests.yml
Fix full matrix pipeline. It wasn't able to start if manually triggered.
Fixing following errors:
[one](https://github.com/valkey-io/valkey-glide/actions/runs/16060472310)
> [Invalid workflow file: .github/workflows/full-matrix-tests.yml#L66](https://github.com/valkey-io/valkey-glide/actions/runs/16060472310/workflow)
> The workflow is not valid. .github/workflows/full-matrix-tests.yml (Line: 66, Col: 5): Error calling workflow 'valkey-io/valkey-glide/.github/workflows/redis-rs.yml@1a7701ce0d752df6e3db36afbc66ad4c2dc10611'. The workflow is requesting 'actions: write', but is only allowed 'actions: none'.
[two](https://github.com/valkey-io/valkey-glide/actions/runs/16060552793)
> [Invalid workflow file: .github/workflows/full-matrix-tests.yml#L79](https://github.com/valkey-io/valkey-glide/a …
> CI: Fix GHA

- .github/workflows/full-matrix-tests-sweeper.yml
Fix "Resource not accessible by integration" error in CI by adding the necessary actions:write permission to the workflow. This permission is required for the workflow to trigger the full-matrix-tests workflow using the GitHub API via github.rest.actions.createWorkflowDispatch().
Without this permission, the workflow was unable to trigger other workflows, causing the CI process to fail.
-   [X] Create merge commit if merging release branch into main, …
> CI: Add actions:write permission to full-matrix-tests-sweeper

- csharp/sources/Valkey.Glide/Abstract/ConnectionMultiplexer.cs
- csharp/sources/Valkey.Glide/Abstract/ValkeyServer.cs
- csharp/sources/Valkey.Glide/Internals/Utils.cs
- csharp/tests/Valkey.Glide.IntegrationTests/ServerTests.cs
- csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
The issue caused by calling `ToString()` method on an `DnsEndPoint` instance, which prints address familty, so resulting string were "Unspecified/localhost:6379".
This Pull Request is linked to issue (URL): fixes #4391
> C#: fix endpoint string conversion

- .gitignore
- csharp/sources/Valkey.Glide/BaseClient.SortedSetCommands.cs
- csharp/sources/Valkey.Glide/Commands/Constants/Constants.cs
- csharp/sources/Valkey.Glide/Commands/ISortedSetCommands.cs
- csharp/sources/Valkey.Glide/Commands/Options/ZCountOptions.cs
- csharp/sources/Valkey.Glide/Commands/Options/ZRangeOptions.cs
- csharp/sources/Valkey.Glide/Internals/Request.SortedSetCommands.cs
- csharp/sources/Valkey.Glide/Pipeline/BaseBatch.SortedSetCommands.cs
- csharp/sources/Valkey.Glide/Pipeline/IBatchSortedSetCommands.cs
- csharp/tests/Valkey.Glide.IntegrationTests/BatchTestUtils.cs
- csharp/tests/Valkey.Glide.IntegrationTests/SortedSetCommandTests.cs
- csharp/tests/Valkey.Glide.UnitTests/BoundaryTests.cs
- csharp/tests/Valkey.Glide.UnitTests/CommandTests.cs
- csharp/tests/Valkey.Glide.UnitTests/SortedSetCommandTests.cs
This PR adds the rest of the Sorted Set Public Preview Commands
**Note**:
`SortedSetLengthAsync` is split into `SortedSetLengthAsync` (`ZCard`) and `SortedSetCountAsync` (`ZCount`)
For `SortedSetRangeByValueAsync` (ZRange BYLEX), it doesn't have a `WithScores` method in SER.
This Pull Request is linked to issue (URL): #4222 
> C#: Sorted Set Public Preview Commands

- CHANGELOG.md
- go/config/config.go
- go/config/config_test.go
- go/integTest/connection_test.go
- go/integTest/glide_test_suite_test.go
This PR implements lazy connection functionality for the Valkey GLIDE Go client, allowing clients to defer connection establishment until the first operation is executed.
- **Deferred Connection**: Clients with lazy connect enabled only establish connections when the first operation is executed
- **Backward Compatibility**: Lazy connect is disabled by default, maintaining existing behavior
- **Full Support**: Available for both standalone and cluster client configurations
- **Testing**: Includes unit tests and integration tests validating the lazy connection behavior
- New unit tests verify configuration and protobuf conversion
- Integration tests confirm lazy connection behavior in both standalone and cluster modes
- Connection count monitoring ensures connections are established only …
> GO: Lazy connect implementation

- .github/workflows/ort.yml
Currently ORT workflow doesn't have permissions to push a branch or create a PR, because of this change in permissions -https://github.com/valkey-io/valkey-glide/pull/4274
This PR fixed the permissions and adds `exit` statements to fail the workflow if something fails.
> ORT: fix workflow permissions

- python/glide-sync/glide_sync/glide_client.py
- python/tests/async_tests/conftest.py
- python/tests/sync_tests/conftest.py
- python/tests/sync_tests/test_sync_auth.py
- python/tests/utils/utils.py
This PR adds the update connection password function and tests to the python sync client.
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/4516
> Python sync: add update_connection_password

- glide-core/redis-rs/redis/examples/async-await.rs
- glide-core/redis-rs/redis/examples/async-multiplexed.rs
- glide-core/redis-rs/redis/examples/async-pub-sub.rs
- glide-core/redis-rs/redis/examples/async-scan.rs
- glide-core/redis-rs/redis/examples/basic.rs
- glide-core/redis-rs/redis/src/aio/multiplexed_connection.rs
- glide-core/redis-rs/redis/src/cluster.rs
- glide-core/redis-rs/redis/src/cluster_async/connections_logic.rs
- glide-core/redis-rs/redis/src/cluster_async/pipeline_routing.rs
- glide-core/redis-rs/redis/src/cluster_routing.rs
- glide-core/redis-rs/redis/src/commands/macros.rs
- glide-core/redis-rs/redis/tests/test_async.rs
- glide-core/redis-rs/redis/tests/test_cluster_async.rs
- glide-core/src/client/mod.rs
- glide-core/src/client/standalone_client.rs
- glide-core/src/client/value_conversion.rs
- glide-core/tests/test_client.rs
- glide-core/tests/test_standalone_client.rs
- glide-core/tests/utilities/cluster.rs
- glide-core/tests/utilities/mod.rs
- Fix lifetime syntax warnings by adding explicit lifetime annotations
- Add type annotations to query/query_async calls to resolve never type fallback warnings
- Update redis-rs cluster_routing.rs, commands/macros.rs, multiplexed_connection.rs, connections_logic.rs, and cluster.rs
> CORE: resolve clippy warnings and future incompatibility issues

- ffi/Cargo.toml
- ffi/miri-tests/Cargo.toml
- ffi/miri-tests/mock-glide-core/src/lib.rs
- ffi/miri-tests/mock-glide-core/src/request_type.rs
- ffi/miri-tests/mock-logger-core/Cargo.toml
- ffi/miri-tests/mock-logger-core/src/lib.rs
- ffi/miri-tests/mock-redis/src/lib.rs
- ffi/miri-tests/mock-telemetry/src/lib.rs
- ffi/miri-tests/tests/ffi_miri_tests.rs
- ffi/src/lib.rs
- ffi/tests/ffi_client_tests.rs
- ffi/tests/test_enhanced_error_handling.rs
- ffi/tests/test_otel_ffi_integration.rs
- glide-core/telemetry/Cargo.toml
- glide-core/telemetry/src/open_telemetry.rs
- go/base_client.go
- go/examples/examples.md
- go/integTest/glide_test_suite_test.go
- go/integTest/opentelemetry_test.go
- go/opentelemetry.go
- go/opentelemetry_examples_test.go
- go/span_context_test.go
This PR significantly enhances the OpenTelemetry integration by implementing comprehensive span context attachment functionality, enabling proper parent-child span relationships and improved tracing capabilities across the Glide client library.
- **New FFI Functions**:
- `create_named_otel_span()` - Creates spans with custom names for user operations
- `create_otel_span_with_parent()` - Creates child spans with parent-child relationships
- `create_batch_otel_span_with_parent()` - Creates batch spans with parent context
- **Enhanced Error Handling**:
- Input validation with detailed logging
- Graceful fallback mechanisms for invalid parent spans
- Memory safety improvements with pointer validation
- Panic recovery in span cleanup operations
- **Public Span Management APIs**:
- …
> CORE/FFI/GO - SpanFromContext implementation

- ffi/miri-tests/README.md
- ffi/miri-tests/mock-logger-core/src/lib.rs
- ffi/miri-tests/tests/ffi_miri_tests.rs
- ffi/src/lib.rs
- python/glide-async/python/glide/logger.py
- python/glide-shared/glide_shared/__init__.py
- python/glide-shared/glide_shared/exceptions.py
- python/glide-sync/glide_sync/__init__.py
- python/glide-sync/glide_sync/glide_client.py
- python/glide-sync/glide_sync/logger.py
- python/tests/sync_tests/conftest.py
- python/tests/test_utils.py
- python/tests/utils/utils.py
This PR adds FFI logger functions and implements the logger for the sync python client.
The FFI log function puts the responsibility of checking whether a log is below or above the set logger level **on the calling wrappper**, in order to avoid redundant FFI calls. 
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/3999
> FFI & Sync Python: add sync logger

- python/tests/async_tests/test_async_client.py
- python/tests/sync_tests/test_sync_client.py
- python/tests/test_api_consistency.py
- python/tests/test_api_export.py
- python/tests/test_options.py
This PR - 
1. Adds a `test_api_consistency.py` file that includes 2 test - 
- A test that finds all function names in the sync/async class and makes sure there are no unapproved functions that exist only in one of them.
- A test that finds all test names in the sync/async test dirs and makes sure there are no unapproved tests that exist only in one of them.
2. Adds a test called `test_shared_symbols_reexported` to the `test_api_export.py` file, which checks that all public symbols exported from the shared package are then also exported by both the async and sync packages.
2. Moves the tests in the TestCommandsUnitTests class, that are relevant to both async and sync, from the `test_async_client` file to a new `test_options` file.
3.  Adds the test …
> Python: added async-sync API consistency test, re-export test

- .github/workflows/csharp.yml
- .github/workflows/go.yml
- .github/workflows/java.yml
- .github/workflows/node.yml
- .github/workflows/python.yml
Fix artifact (test reports) naming errors spotted in [full matrix tests](https://github.com/valkey-io/valkey-glide/actions/runs/16612782839), such as:
1. using unsanitized image name
```
The artifact name is not valid: test-reports-dotnet-8.0-valkey-8.0-amazonlinux:latest-x64. Contains the following character:  Colon :
```
2. using unset variables (`test-report-node-16.x-redis-6.2--x64`)
3. using `RUNNER` as a name (`test-reports-dotnet-6.0-redis-6.2-Array`)
See test run with fixes: https://github.com/valkey-io/valkey-glide/actions/runs/16631192125
> Fix test report artifact name

- java/integTest/src/test/java/glide/cluster/CommandTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4574
This PR is an effort to try to get more information on the flakey test config_reset_stat, to at least get the value of both `valueBefore` and `valueAfter`, instead of current useless message of `expected: <true> but was: <false>`
> Java: add more output when config_reset_stat failed

- .github/workflows/python.yml
Because python sync tests were added, the slower runners struggle to finish the job in 90 mins.
This is the solution just to get the jobs to stop timing out for now, in the future we can consider separating the python sync and async jobs.
> Python: increase test workflow timeout

- CHANGELOG.md
- glide-core/src/socket_listener.rs
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4591
> Core: Fix UDS infinite loop

- .github/json_matrices/engine-matrix.json
- CHANGELOG.md
- go/integTest/cluster_commands_test.go
- go/integTest/standalone_commands_test.go
- java/client/src/main/java/redis/clients/jedis/Jedis.java
- java/integTest/src/test/java/compatibility/jedis/JedisTest.java
- java/integTest/src/test/java/glide/BatchTestUtilities.java
- java/integTest/src/test/java/glide/SharedCommandTests.java
- java/integTest/src/test/java/glide/cluster/CommandTests.java
- java/integTest/src/test/java/glide/standalone/CommandTests.java
- node/tests/GlideClient.test.ts
- node/tests/GlideClusterClient.test.ts
- python/tests/async_tests/test_async_client.py
- python/tests/async_tests/test_batch.py
- python/tests/sync_tests/test_sync_batch.py
- python/tests/sync_tests/test_sync_client.py
This PR addresses compatibility issues with Valkey 9 by updating test assertions and fixing hash field expiration command implementations across multiple language clients (Go, Java, Node.js, Python).
Updated test assertions across all language clients to support both Redis and Valkey version output formats:
- **Go**: Updated `cluster_commands_test.go` and `standalone_commands_test.go` to use regex pattern matching for version strings
- **Java**: Modified test files in `cluster/CommandTests.java`, `standalone/CommandTests.java`, and `BatchTestUtilities.java` to accept both "Redis ver." and "Valkey ver." formats
- **Node.js**: Updated `GlideClient.test.ts` and `GlideClusterClient.test.ts` to use regex matching instead of string contains
- **Python**: Modified async and sync test files to …
> FIX: resolve Valkey 9 compatibility issues across all clients

- utils/cluster_manager.py
Fixes a flaky test described in the issue below.
The change is to increase wait time for retries from 0.5s to 1s.
This Pull Request is linked to issue (URL): [#4652](https://github.com/valkey-io/valkey-glide/issues/4652)
> Util: Updated wait time for retries from 0.5s to 1s

- .github/json_matrices/engine-matrix.json
- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Batch.ts
- node/src/Commands.ts
- node/tests/SharedTests.ts
- node/tests/TestUtilities.ts
This PR implements comprehensive support for Valkey's new hash field expiration commands, enabling field-level TTL management within hash data structures. This feature allows individual fields in a hash to expire independently, providing fine-grained control over data lifecycle management.
- **Protobuf & Rust Core**: Added 11 new RequestType enums (617-627) for all hash field expiration commands
- **Command Mapping**: Updated Rust request_type.rs with proper command string mappings for all new commands
Sets hash fields with optional expiration and conditional logic:
- **Conditional Options**: `FNX` (fields don't exist), `FXX` (all fields exist)
- **Expiry Options**: `EX` (seconds), `PX` (milliseconds), `EXAT` (Unix timestamp seconds), `PXAT` (Unix timestamp milliseconds), `KEEPTTL`
- …
> NODE:  Valkey 9 support - Add Hash Field Expiration Commands Support

- benchmarks/install_and_test.sh
- benchmarks/utilities/csv_exporter.py
The benchmark tests in Valkey-Glide-CSharp kept breaking due to path differences in how the benchmark results folder location is calculated. See https://github.com/valkey-io/valkey-glide-csharp/pull/43
This Pull Request is linked to issue (#4532 ): 
> Fix benchmark execution for CSharp

- .github/json_matrices/build-matrix.json
- .github/workflows/create-test-matrices/action.yml
- .github/workflows/full-matrix-tests.yml
- .github/workflows/go.yml
- .github/workflows/java.yml
- .github/workflows/node.yml
- .github/workflows/npm-cd.yml
- .github/workflows/python.yml
- .github/workflows/rust.yml
This PR adds the option to run tests on Mac self hosted runners. Scheduled tests are still disabled on self hosted runners until it's stable. It adds an option to choose between running on self hosted vs running on `macos-15` github runners on manual triggers of the tests. 
In addition it fixes the `npm-cd` to avoid running on ephemeral runners, this was previously in the code and was mistakenly deleted in https://github.com/valkey-io/valkey-glide/pull/3930
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/4627
-   [ ] CHANGELOG.md …
> CI: Added self hosted macOS runners

- CHANGELOG.md
- node/src/BaseClient.ts
- node/src/Batch.ts
- node/src/GlideClient.ts
- node/src/GlideClusterClient.ts
- node/tests/GlideClusterClient.test.ts
This PR implements comprehensive multi-database support for both standalone and cluster modes, with special focus on enabling database selection in cluster mode for Valkey 9.0+ servers. The implementation includes client-side validation, server-side database selection.
- **Database Selection**: Added `databaseId` parameter to client configurations for both standalone and cluster modes
- **Cluster Mode Support**: Enables multi-database functionality in cluster mode (requires Valkey 9.0+ with `cluster-databases` configured)
- **Reconnection Persistence**: Database selection persists across reconnections when configured via client options
- **Cross-Language Support**: Implementation spans Rust (glide-core), Node.js, and Java clients
- **BaseClient Configuration**: Added `databaseId` …
> [Backport 2.1] Node: Add Multi-Database Support for Cluster Mode (Valkey 9.0)

- .github/json_matrices/build-matrix.json
- .github/workflows/npm-cd.yml
This PR fixes a previous PR - https://github.com/valkey-io/valkey-glide/pull/4683
The previous PR introduced a new matrix to the build-matrix.json file (for mac self hosted runners), which causes the CD workflows to try to run the macOS ARM jobs on self hosted runners in addition to the github runners, which is unnecessary. This PR disables this, as well as reverts the changed that were made to thenpm-cd workflow in the previous commit.
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/4627
-   [ ] CHANGELOG.md and documentation …
> CD: removed self hosted mac arm runners from required CD platforms #4700

- .github/workflows/pypi-cd.yml
- utils/release-candidate-testing/python/async_rc_test.py
- utils/release-candidate-testing/python/sync_rc_test.py
- utils/release-candidate-testing/python/utils.py
This PR fixes the pypi-cd workflow, following rc releases that failed. It - 
1. makes sure only the async/sync appropriate wheels are uploaded (previously it succeeded in uploading the wheel, but  `twine` mistook other unrelated files as dist file, which failed the command). 
2. raises the job's timeout (takes longer now that sync wheels have to be built too) 
3. Fixes the release tests, since they failed on a `glide_sync not found` error, which was imported in `utils/release-candidate-testing/python/utils.py`. Thus moved the async/sync specific function away from the utils.py, it could be shared between the 2 tests. 
This Pull Request is linked to issue: [#3285](https://github.com/valkey-io/valkey-glide/issues/3285)
-   [ ] …
> Python: fixed pypi-cd workflow, fixed release tests

- python/glide-sync/pyproject.toml
This PR reverts the license format in the sync client's `pyproject.toml` file. This was changed originally because the `licence = { text = "..."} ` format triggers a deprecation warning, but it's still required in python 3.10 and 3.11 so it will be reverted. 
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/4728
> Python Sync: revert license format

- python/glide-async/python/glide/glide_client.py
- python/tests/async_tests/test_async_client.py
- python/tests/test_api_consistency.py
This PR improves error handling for unexpected UDS socket closures. Previously, there were two issues:
1. When a write to the UDS socket failed, the raised exception was directly set on the future instead of raising a ClosingError.
2. When the UDS socket closed, both the reader loop and writer task attempted to set an exception on the same future almost simultaneously. Since the reader loop calls `client.close()` and tries to set exceptions for all pending futures, by the time the second task attempted to do the same, the future was already completed, resulting in an `asyncio.exceptions.InvalidStateError: invalid state`
This PR resolves these issues by:
1. Raising a `ClosingError` when a write to the socket fails.
2. Ensuring an exception is only set on a future if it is not already …
> Python: improve UDS socket error handling

- utils/cluster_manager.py
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4666
> Util: Fix cluster manager flaky function `is_address_already_in_use()`

- .github/workflows/pypi-cd.yml
removed persistent arm runners from test-release job
This is a cherry-pick of https://github.com/valkey-io/valkey-glide/pull/4771
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/4770
> [Backport 2.1] Python CD: updated testing to run on ephemeral runners (#4771)
