valkey-io/valkey-glide

python/python/glide/async_commands/core.py
=> fix SET return type in python

node/README.md
=> fix another reference to the package.

node/tests/SharedTests.ts
=> SharedTests.ts: fix spelling versioString -> versionString.

README.md, node/README.md, python/README.md
Fix typo s/Documenation/Documentation/
=> chore: Fix typo s/Documenation/Documentation/

glide-core/src/socket_listener.rs, logger_core/tests/test_logger.rs
=> chore: Fix multiple typos

python/python/glide/__init__.py
*Issue #, if available:* No associated issue
Expose InfoSection so that it can be consumed by the python client.
=> Expose InfoSection so it can be used by clients

benchmarks/install_and_test.sh
These options are no longer available.
=> Fix benchmark doc.

examples/node/index.ts, examples/node/package.json
=> Fixed node example with the aws namespace

node/README.md
=> Fix node example to include the aws scope

.github/workflows/build-python-wrapper/action.yml, python/requirements.txt
=> Remove unused library from python's requirements

utils/cluster_manager.py
=> Fixed cluster_manager script to allow creating a standalone cluster with a single node

glide-core/src/socket_listener.rs
Not all closing errors happen on client creation.
=> Socket listener: fix identifier for closed reader error.

python/python/glide/async_commands/core.py, python/python/tests/conftest.py
=> Fixed python linters

.gitignore
=> Add class files to gitignore.

glide-core/src/socket_listener.rs, glide-core/tests/test_socket_listener.rs
=> Report error if user sends an empty custom command.

.github/workflows/csharp.yml, benchmarks/csharp/Program.cs, benchmarks/install_and_test.sh
=> C#: Fail CI on warnings.

utils/get_licenses_from_ort.py
This PR is a preparation for the ORT github action.
=> Added a script to parse ORT analyzer results and retrieve the found licenses

utils/get_licenses_from_ort.py
after #912 python tests failure 
=>  fix license script

.vscode/settings.json
=> Set default solution for C#.

.github/workflows/build-node-wrapper/action.yml, .github/workflows/node-create-package-file/action.yml
This PR is preparing the groundwork for the integration of the ORT workflow into GitHub Actions
=> github actions: Moved 'create package.json' step to a dedicated action

java/client/src/main/java/glide/api/models/ClusterValue.java
Documentation updates only: ClusterValue.java updates
=> Java: Update ClusterValue javadocs

java/integTest/src/test/java/glide/cluster/CommandTests.java
Minor updates to CommandTests.java
=> Java: Clean glide.cluster.CommandTests

benchmarks/rust/src/main.rs, glide-core/tests/utilities/mod.rs
replace Vec reference with a slice.
=> Fix new clippy lints.

python/python/tests/conftest.py, python/python/tests/test_async_client.py, python/python/tests/test_redis_modules.py, python/python/tests/test_transaction.py
=> Parameterize Python tests for both RESP2 & RESP3.

node/src/BaseClient.ts, node/tests/RedisClient.test.ts, node/tests/RedisClusterClient.test.ts, node/tests/RedisModules.test.ts, node/tests/SharedTests.ts
=> Parameterize Node tests for both RESP2 & RESP3.

CHANGELOG.md
=> Added release notes for v0.2.0

node/package.json
=> Fixed Node's package.json file (v0.2)

.github/workflows/npm-cd.yml
=> NPM CD: Fixed not failing on already published package

CHANGELOG.md
Followup PRs should include the change in the release notes
=> Added release notes for v0.2.0 (main)

node/package.json
=> Fixed Node's package.json file (main)

CHANGELOG.md
=> fix release note for v0.2.0

.github/workflows/ort.yml
N/A
* Don't run CI on fork repos to avoid PRs like https://github.com/Bit-Quill/glide-for-redis/pull/83
* Update GHA to avoid deprecation warnings (https://github.com/aws/glide-for-redis/actions/runs/7879706500)
=> Fix ORT CI

.github/workflows/csharp.yml, benchmarks/install_and_test.sh
Enabling tests on net8.0 alongside existing net6.0 testing
=> C#: enable net8.0 tests

python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/core.py, python/python/glide/async_commands/standalone_commands.py, python/python/glide/async_commands/transaction.py
=> fix commands doc in python

node/src/BaseClient.ts, node/src/RedisClient.ts, node/src/RedisClusterClient.ts, node/src/Transaction.ts
=> Node: Update documentation.

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
=> Node: added type command.

python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py
=> Python: fix MGET return type

glide-core/src/client/mod.rs, glide-core/tests/test_client.rs, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
Upgraded the dependency, and fixed wrong behavior that was exposed by the upgrade.
=> Upgrade redis-rs dependency.

glide-core/tests/test_client.rs
The test didn't work, because the pipeline wasn't set to be atomic, so the reason for the timeout was that the client waited for more responses.
=> Fix transaction test.

.github/workflows/semgrep.yml
https://github.com/aws/glide-for-redis/issues/995
Integrates semgrep in standalone mode
=> Initial semgrep integration

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StringCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/ClusterTransactionTests.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TestUtilities.java
=> Java: Added Decr and DecrBy to BaseClient and BaseTransaction. (String Commands)

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
=> Node: Added hlen command.

glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, glide-core/tests/test_socket_listener.rs
=> Core: Add support to route by address.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Added Hmget command for BaseClient and BaseTransaction (Hash Commands)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Added Hexists command for BaseClient and BaseTransaction (Hash Commands)

python/python/tests/test_async_client.py
=> Python: remove duplicated line from info test

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Added Lpush, Lpop and LpopCount Commands. (List Commands)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Added Rpush, Rpop and RpopCount Commands. (List Commands) (#107)

node/tests/RedisClient.test.ts, node/tests/RedisClusterClient.test.ts, node/tests/RedisModules.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
=> Node: allow standalone tests to use cluster_manager.py script

csharp/lib/Cargo.toml, glide-core/Cargo.toml, python/Cargo.toml
=> Remove unused dependencies.

CHANGELOG.md, glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
=> Python: adds HSETNX command

csharp/DEVELOPER.md, csharp/README.md
N/A
Fill up developer guide for C# client.
Note: Instructions for glide-core are omitted.
=> Update docs for C# client (#111)

java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java, java/client/src/main/java/glide/managers/ConnectionManager.java, java/client/src/test/java/glide/managers/ConnectionManagerTest.java, java/integTest/src/test/java/glide/cluster/ClientTest.java, java/integTest/src/test/java/glide/standalone/ClientTest.java
=> Java: Added clientName field to configuration. (#117)

node/jest.config.js
=> Node: Added testTimeout config to jest to fix macos timeout failures

node/DEVELOPER.md
https://github.com/aws/glide-for-redis/issues/1059
=> Clarify which versions of npm are workable.

CHANGELOG.md
=> fix changelog changes and features for 0.2.0

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/models/BaseTransaction.java
=> Java: Add non-null tags to missing commands (#123)

java/client/src/main/java/glide/api/commands/StringCommands.java
=> Java: Added examples to documentation for StringCommands. (#120)

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts
=> Node: added Pttl command.

node/rust-client/src/lib.rs
=> Fix node lint.

glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
=> Add zremRangeByRank command in Node.

java/client/src/main/java/glide/api/commands/ListBaseCommands.java
=> Java: Stylistic documentation changes for ListBaseCommands. (#128)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add Lrem command to BaseClient and BaseTransaction. (List commands)

.github/workflows/node.yml, .github/workflows/pypi-cd.yml
Failures:
https://github.com/aws/glide-for-redis/actions/runs/8222099912/job/22483210903?pr=1089
https://github.com/aws/glide-for-redis/actions/runs/8222099900/job/22483210189?pr=1089
=> CI/MacOS: Fixed brew to overwrite existing files while linking to avoid CI failures

utils/get_licenses_from_ort.py
=> Updated approved licenses in ORT util

benchmarks/python/python_benchmark.py
=> Python: Changed benchmark latencies to be in milliseconds

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ConnectionManagementCommands.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/commands/GenericClusterCommands.java, java/client/src/main/java/glide/api/commands/GenericCommands.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementCommands.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/commands/StringCommands.java
=> Java: Updated interface names and documentation for uniformity.

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
=> Node: added hsetnx command.

node/src/BaseClient.ts, python/python/glide/async_commands/core.py
=> fix ZADD , ZADDINCR examples

java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ConnectionManagementCommands.java
=> Java: Added documentation examples to ConnectionManagement group. (#132)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/ZaddOptions.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add ZADD and ZINCR commands. (Sorted Set Commands) (#115)

java/client/src/main/java/glide/api/models/configuration/RequestRoutingConfiguration.java, java/client/src/main/java/glide/managers/CommandManager.java, java/client/src/test/java/glide/managers/CommandManagerTest.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
=> Java: enable routing by node address. (#137)

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
=> Python: adds LINDEX command

java/client/src/main/java/glide/api/commands/ConnectionManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/GenericClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java
=> Java: Minor Documentation Update for Commands With Routes

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Added Zrem and Zcard commands. (Sorted Set Commands)

java/integTest/src/test/java/glide/cluster/CommandTests.java
https://github.com/aws/glide-for-redis/issues/1122
=> Java: Fix flakey test.

csharp/tests/Integration/GetAndSet.cs
N/A
Deactivate a flaky IT until we find why it fails
=> C#: Deactivate flaky IT.

.github/workflows/node.yml
minor improvements to [1132](https://github.com/aws/glide-for-redis/pull/1132)
=> Node: minor improvements to #1132

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
=> Python: adds PERSIST command

glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, python/python/glide/async_commands/redis_modules/json.py
=> Python: modify json module to use custom_command

node/tests/RedisClientInternals.test.ts
This adds a helper function that can take a single command, and check that the right value is passed on the socket as response to the command.
This PR is based over https://github.com/aws/glide-for-redis/pull/1095
=> Node: Simplify writing unit tests for complex commands.

java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementCommands.java
=> Java: Added documentation examples to ServerManagement group. (#131)

node/src/RedisClusterClient.ts, node/tests/SharedTests.ts
=> Node: fix `TIME` response type for cme

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClient.test.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
=> Node: added zrank command.

python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py
=> Minor documentation update in python

python/python/glide/async_commands/core.py
=> fix black error

CHANGELOG.md, node/src/RedisClusterClient.ts, node/tests/RedisClientInternals.test.ts
=> Node: Added periodic checks configuration for RedisClusterClient

.github/workflows/ort.yml
=> Semgrep: Fixes for the ORT action

glide-core/tests/test_client.rs
=> Core: Merge latest updates from amazon-contributing/redis-rs

CHANGELOG.md
Preparation for v0.3.0 release
=> Closes v0.3.0 changes in the CHANGELOG.md file

utils/cluster_manager.py
https://github.com/aws/glide-for-redis/issues/1149
=> Fix semgrep finding for cluster_manager.py

java/benchmarks/src/main/java/glide/benchmarks/clients/glide/GlideAsyncClient.java, java/benchmarks/src/main/java/glide/benchmarks/clients/jedis/JedisClient.java, java/benchmarks/src/main/java/glide/benchmarks/clients/lettuce/LettuceAsyncClient.java
=> Benchmark: Align Java client names with other wrappers.

node/package.json
Ignore hybrid-tests folder in publish
=> ignore hybrid-tests folder in publish

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StringCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
Add [`STRLEN`](https://redis.io/commands/strlen/) to java wrapper
=> Add `STRLEN` command. 

glide-core/THIRD_PARTY_LICENSES_RUST, node/THIRD_PARTY_LICENSES_NODE, python/THIRD_PARTY_LICENSES_PYTHON
=> Updated attribution files

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java
Add [pttl()](https://redis.io/commands/pttl/) command to the Java wrapper
=> Java: Add `PTTL()` command

.github/workflows/install-redis-modules/action.yml, .github/workflows/node.yml, .github/workflows/python.yml, node/tests/RedisModules.test.ts
=> remove redisearch installation from workflow

CHANGELOG.md, python/python/glide/async_commands/redis_modules/json.py, python/python/tests/tests_redis_modules/test_json.py
=> Python: adds JSON.DEL, JSON.FORGET commands

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Added Zscore command. (Sorted Set Commands)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/Script.java, java/client/src/main/java/glide/api/models/commands/ScriptOptions.java, java/client/src/main/java/glide/ffi/resolvers/ScriptResolver.java, java/client/src/main/java/glide/managers/CommandManager.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/src/lib.rs, node/src/BaseClient.ts, python/python/glide/async_commands/core.py
Add the command invokeScript(Script) to the Java wrapper.  
=> Java: add invokeScript to run lua scripts

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add Zrank and Zrankwithscores command. (Sorted Set Commands) (#154)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add hsetnx command. (Hash Command Group) (#162)

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
Adds hash command HKEYS - https://redis.io/commands/hkeys/
=> Python: adds HKEYS command

java/integTest/src/test/java/glide/ConnectionTests.java, java/integTest/src/test/java/glide/ErrorHandlingTests.java, java/integTest/src/test/java/glide/SharedClientTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/cluster/ClusterClientTests.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
N/A
Update how future timeout is handled in IT to make tests a bit more readable
=> Java: Update timeout handling in IT.

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add `sismember` command. (Set Commands Group)

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
=> Python: adds ZREMRANGEBYSCORE command

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
=> Node: added spop and spopCount commands.

node/DEVELOPER.md
The node/DEVELOPER.md file doesn't render properly in one section.  This PR re-formats the section to render properly.  
=> Node: Fix build section for node DEVELOPER.md

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add `lindex` command. (List Command Group)

java/client/src/test/java/glide/api/models/TransactionTests.java
N/A
Simplify developing transaction UT in java client
=> Java: Refactor transaction UT

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/RangeOptions.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add `Zcount` command. (Sorted Set Group)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add `Zremrangebyrank` command. (Sorted Set Group) (#189)

java/build.gradle
=> Java: Bump `spotless` version.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
https://redis.io/docs/latest/commands/sinterstore/
#1277 + #1248 = ~<3~ #1288
=> Java: Add `SINTERSTORE` command.

CHANGELOG.md, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
=> Python: adds APPEND command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
https://redis.io/docs/latest/commands/getrange/
=> Add `GETRANGE` command.

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/zremrangebylex/
=> Python: add ZREMRANGEBYLEX command (#228)

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/linsert/
=> Python: add LINSERT command (#227)

glide-core/src/client/value_conversion.rs
N/A
it was requested in https://github.com/Bit-Quill/glide-for-redis/commit/c2d7b407b29bb1a2806772daa839273e7fbede6e#r141023377
=> Core: Update data convertion for `SMISMEMBER`

csharp/tests/Integration/GetAndSet.cs
Fix C# CI failure on main: https://github.com/aws/glide-for-redis/actions/runs/8773031956/job/24072628798
Fix conflict caused by merging #1265 and #1282 without rebase.
=> C#: Fix the build.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
Description of changes:
https://redis.io/commands/object-refcount/
=> Java: Implement OBJECT REFCOUNT command

java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
N/A
Update IT for `CONFIG REWRITE` to handle both cases as it is done in node test:
https://github.com/aws/glide-for-redis/blob/369aff5f747ee11103d9d1e942d8229ab644edf3/node/tests/SharedTests.ts#L308-L326
=> Java: Fix IT for `CONFIG REWRITE`.

node/.prettierignore
N/A
Prevent `prettier` linter sneaking into crate json files and raise thousands of errors.
This never happens in CI, because CI lint check lives in a separate workflow, but it is very helpful for a developer.
=> Node: Add `.prettierignore`.

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
N/A
https://redis.io/docs/latest/commands/lolwut/
=> Java: `LOLWUT`

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
https://redis.io/docs/latest/commands/sdiff/
Made as combination of #1243 #1248 #1288
=> Java: Add `SDIFF` command.

java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java
N/A
Update javadocs accroding to the new standards
=> Update javadocs for `BRPOP` and `BLPOP`

CHANGELOG.md, glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
=> Python: adds GEOPOS command

python/dev_requirements.txt
=> Python: Upgrade black version

python/dev_requirements.txt
=> Python: Resolving package conflicts

glide-core/src/client/mod.rs
=> Submodules: Pull changes from amazon-contributing/redis-rs

node/src/BaseClient.ts, node/src/Transaction.ts
#1215 
Complete doc update started in https://github.com/aws/glide-for-redis/pull/1227 according to https://github.com/aws/glide-for-redis/issues/1215
=> Node: Update examples in docs.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add command `Touch`. (Generic Command Group)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/hkeys/
=> Java: Add `HKEYS` command.

go/Makefile, go/go.mod, go/go.sum
=> Go: update protobuf version 

.github/workflows/csharp.yml, benchmarks/install_and_test.sh
Allows to change the running framework.
=> C#: Added a dotnet framework flag to the C# benchmark

package.json
N/A
Was added by mistake in #1356
=> Remove file added by mistake.

node/DEVELOPER.md
=> fixed developer.md node v specifation

java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, node/src/BaseClient.ts, node/src/Transaction.ts, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py
N/A
Follow up from https://github.com/aws/glide-for-redis/pull/1239#discussion_r1557959459
=> Update docs for `LPUSHX` and `RPUSHX`

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
https://valkey.io/commands/zdiffstore/
=> Python: add ZDIFFSTORE command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Java: Add command `GEOHASH`

node/tests/RedisClusterClient.test.ts
N/A
Hotfix for #1391 - resolving conflict with #1419.
=> Node: Hotfix for #1391 - resolving conflict with #1419.

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
Added `SETBIT` command to java client. https://redis.io/docs/latest/commands/setbit/
=> Java: Add `SETBIT` command 

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/sdiffstore/
=> Python: add SDIFFSTORE command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/ScoreFilter.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
N/A
https://redis.io/docs/latest/commands/zmpop/
Copy-pasted from BZMPOP
=> Java: Add `ZMPOP` command.

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/PopDirection.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
* Java: Adding command LMPOP
- interface & client implementation
- new map type conversion
---------
=> Java: Adding command `LMPOP` (#292)

CHANGELOG.md
=> arrange changelog to release

python/python/glide/async_commands/core.py, python/python/glide/async_commands/sorted_set.py, python/python/glide/async_commands/transaction.py
=> Python: remove duplication of create_zrange_args function

.github/workflows/npm-cd.yml, .github/workflows/pypi-cd.yml, .github/workflows/start-self-hosted-runner/action.yml
=> Use IAM role to configure aws credentials with GH actions

java/client/src/main/java/glide/api/models/BaseTransaction.java
Moving `append` into a more appropriate position
=> Java: moving the Appends command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
=> Add command `LSET`

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
N/A
https://redis.io/docs/latest/commands/renamenx/
=> Node: Added RENAMENX command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/pfcount/
=> Python: add PFCOUNT command

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
N/A
https://redis.io/docs/latest/commands/sinter/
=> Node: Add `SINTER` command for node

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
* Adding command BLMove
---------
=> Java: Adding command `BLMove`

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/xlen/
=> Python: add XLEN command

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
* Java: Adding command SRandMember
---------
=> Java: Adding command `SRandMember`

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
* Java: Adding command SInterCard
---------
=> Java: Adding command `SInterCard`

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/commands/GenericCommands.java, java/client/src/main/java/glide/api/models/Transaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/StandaloneTransactionTests.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
N/A
https://redis.io/docs/latest/commands/move/
=> Java: add MOVE command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
N/A
https://redis.io/docs/latest/commands/spop/
=> Java: add SPOP command

java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
N/A
https://redis.io/docs/latest/commands/dbsize/
=> Java: add DBSIZE command

java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java
=> Improved bitmap javadocs 

python/python/tests/test_async_client.py
due to failing: https://github.com/aws/glide-for-redis/actions/runs/9534413393/job/26278813710
=> Python: fix OBJECT IDLETIME flaky test

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
=> Python: adds ZINCRBY command

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
https://redis.io/docs/latest/commands/srandmember/
python implementation of srandmember
=> Python: Add command SRandMember

python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/standalone_commands.py
=> Python: refactor publish command to return OK in standalone

java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java
N/A
https://github.com/aws/glide-for-redis/pull/1593#discussion_r1643240553
=> Java: Fix routing for `FLUSHALL` and `FLUSHDB`.

python/python/glide/async_commands/core.py, python/python/glide/config.py, python/python/glide/exceptions.py, python/python/glide/redis_client.py, python/python/tests/test_async_client.py
Added 2 flavors for extracting pubsub messages to python: callback and poll
=> Add callback and peek pubsub api modes

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/ResponseFlags.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java, java/client/src/main/java/glide/api/models/GlideString.java, java/client/src/main/java/glide/api/models/commands/SetOptions.java, java/client/src/main/java/glide/ffi/resolvers/RedisValueResolver.java, java/client/src/main/java/glide/managers/CommandManager.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/src/lib.rs
- Implemented `set(..)` binary version with and without `SetOptions`
- Implemented `getdel` binary version
- Implemented `get` binary version
- Implemented `mget` binary version
- Implemented `hgetall` binary version
=> Add overload methods using`GlideString`

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
Adds the [XACK](https://valkey.io/commands/xack/) command.
=> Java: Add `XACK` stream command

CHANGELOG.md, python/python/glide/__init__.py, python/python/glide/async_commands/core.py, python/python/glide/async_commands/stream.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
N/A
https://redis.io/docs/latest/commands/xrange/
=> Python: add XRANGE command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java, java/integTest/src/test/java/glide/SharedCommandTests.java
Added support for `append` + `smembers` (`GlideString` version)
=> Added support for `append` + `smembers` (`GlideString` version)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java
support bitcount with GlideString
=> support bitcount with GlideString

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/BitmapBaseCommands.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java
support bitop, bitpos and xdel with GlideString
=> support bitop, bitpos and xdel with GlideString

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java
support hincrby, hincrbyfloat, incrby and incrbyfloat with GlideString
=> support hincrby, hincrbyfloat, incrby and incrbyfloat with GlideString

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/HashBaseCommands.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java
support llen, strlen, xlen and hstrlen with GlideString
=> support llen, strlen, xlen and hstrlen with GlideString

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java
support zincrby, zrem, zrank, zscore and zcard with GlideString
=> support zincrby, zrem, zrank, zscore and zcard with GlideString

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/GenericBaseCommands.java, java/client/src/main/java/glide/api/commands/GeospatialIndicesBaseCommands.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java
support geopos, zmscore, persist, rename and renamex with GlideString
=> support geopos, zmscore, persist, rename and renamex with GlideString

glide-core/src/socket_listener.rs, python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/core.py, python/python/glide/async_commands/standalone_commands.py, python/python/glide/config.py, python/python/glide/redis_client.py
addresses comments on PRs:
https://github.com/aws/glide-for-redis/pull/1602
https://github.com/aws/glide-for-redis/pull/1616
=> Pubsub fixups: 1. Logging instead of exceptions on the pending futures due to disconnect notifications. 2. Typos fixes

java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
=> Java: Fix flaky IT.

.github/workflows/ort.yml, utils/get_licenses_from_ort.py
Added Java ORT workflow:
- modified ort.yml to include Java workflow (JDK 11)
- created an empty java/THIRD_PARTY_LICENSES_JAVA file
- updated get_licenses_from_ort script to include Java
=> Added Java ORT workflow

glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/stream/StreamAddOptions.java, java/client/src/main/java/glide/api/models/commands/stream/StreamPendingOptions.java, java/client/src/main/java/glide/api/models/commands/stream/StreamRange.java, java/client/src/main/java/glide/api/models/commands/stream/StreamReadOptions.java, java/client/src/main/java/glide/api/models/commands/stream/StreamTrimOptions.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/examples/src/main/java/module-info.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
Add command [XPENDING](https://redis.io/docs/latest/commands/xpending/)
=> Java: Add XPENDING command

python/python/glide/__init__.py, python/python/glide/async_commands/stream.py
=> Python: fix init file

java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/integTest/src/test/java/glide/SharedCommandTests.java
Fixes and cleanup in documentation for Stream commands
=> Java: Update some Stream docs

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SetBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java
support smismember with GlideString
=> support smismember with GlideString

glide-core/src/client/value_conversion.rs, glide-core/src/protobuf/redis_request.proto, glide-core/src/request_type.rs, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/stream/StreamClaimOptions.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java
https://redis.io/docs/latest/commands/xclaim/
Note: the LASTID argument is undocumented.  After multiple attempts to test it, I was unable to determine the effect of the argument.  Following in Lettuce.io footsteps and removing the option from the API.  
=> Java: Add XCLAIM command

java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/Transaction.java
- With this PR, transaction API for Hash + List commands are binary compatible
- Use leaked ptr approach if required
- Code cleanup
=> - Java transaction: Hash + List commands

glide-core/src/client/value_conversion.rs
=> Core: refactor value_conversions.rs arguments and doc

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/glide/async_commands/transaction.py, python/python/tests/test_async_client.py, python/python/tests/test_transaction.py
=> Python: LPos

java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/integTest/src/test/java/glide/TestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
support functionLoad and functionDelete with GlideString
=> support functionLoad and functionDelete with GlideString

python/python/glide/glide_client.py
Change to use _encode_arg to encode arguments for scrip invocation
Fix _encode_arg to accept Union[str, bytes]
=> Change to use _encode_arg to encode arguments for scrip invocation

java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/RangeOptions.java, java/client/src/main/java/glide/api/models/commands/WeightAggregateOptions.java, java/client/src/main/java/glide/connectors/resources/ThreadPoolResourceAllocator.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java
- Java txn: all SET API are now binary compatible
- Java txn: client API are now binary compatible
- Java txn: config API are now binary compatible
- Java txn: all SORTED SET API are now binary compatible
=> Java: continued work on making txn binary safe

python/python/tests/test_async_client.py
Modified `FUNCTION LIST` test to test byte arguments.
=> Python: Modified `FUNCTION LIST` test to test byte arguments

node/src/BaseClient.ts, node/src/Commands.ts, node/src/GlideClient.ts, node/src/GlideClusterClient.ts, node/src/Transaction.ts
=> Node: change commands links to valkey links

CHANGELOG.md
=> Java/Python: adding changelog for #1768

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java
xpending and xclaim binary version (xautoclaim not implemented in Glide java)
=> xpending and xclaim binary version (xautoclaim not implemented in Glide java)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/client/src/test/java/glide/api/RedisClusterClientTest.java, java/integTest/src/test/java/glide/TestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
support functionStats with GlideString
=> support functionStats with GlideString

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/models/commands/ExpireOptions.java, java/client/src/main/java/glide/api/models/commands/LPosOptions.java, java/client/src/main/java/glide/api/models/commands/SetOptions.java, java/client/src/main/java/glide/api/models/commands/SortBaseOptions.java, java/client/src/main/java/glide/api/models/commands/SortOptionsBinary.java, java/client/src/main/java/glide/api/models/commands/geospatial/GeoAddOptions.java, java/client/src/main/java/glide/api/models/commands/scan/BaseScanOptionsBinary.java
remove using toGlideStringArgs() and use ArgsBuilder instead
=> remove using toGlideStringArgs() and use ArgsBuilder instead

python/python/tests/conftest.py, python/python/tests/test_async_client.py, python/python/tests/test_scan.py, python/python/tests/test_transaction.py, python/python/tests/tests_redis_modules/test_json.py
=> Python: renaming tests clients

glide-core/src/protobuf/redis_request.proto, glide-core/src/socket_listener.rs, python/python/glide/glide_client.py, python/python/tests/test_async_client.py
Created a new protobuf message ScriptInvocationPointers instead of changing the current ScriptInvocation in order to avoid breaking the current implementation and allowing gradual support in all wrappers.
=> Core + Python: Added support in large script requests

go/DEVELOPER.md, python/DEVELOPER.md
=> Update dependency installation and setup instructions for macOS in developer.md

java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/commands/GenericClusterCommands.java, java/client/src/main/java/glide/api/commands/GenericCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
=> randomkey binary support

CHANGELOG.md, examples/python/client_example.py, python/README.md, python/python/glide/__init__.py, python/python/glide/config.py, python/python/tests/conftest.py, python/python/tests/test_async_client.py, python/python/tests/test_config.py, python/python/tests/test_pubsub.py
=> Python: Rename ClusterClientConfiguration to GlideClusterClientConfiguration

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/RedisClusterClient.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
=> fcall bug fix

java/client/src/main/java/glide/api/models/commands/GetExOptions.java
=> Java fix GETEX

CHANGELOG.md, java/integTest/src/test/java/glide/TestUtilities.java, python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/standalone_commands.py, python/python/tests/test_async_client.py, python/python/tests/utils/utils.py
Add [function kill](https://valkey.io/commands/function-kill/) as a Python command
=> Python: add `FUNCTION KILL` command

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/models/Script.java, java/client/src/main/java/glide/managers/CommandManager.java, java/integTest/src/test/java/glide/SharedCommandTests.java
Fixes #1786
Applies changes similar to #1781 in the java client.
=> Java: store pointers in scripts

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java
Support zunion and zunionstore with GlideString
=> Support zunion and zunionstore with GlideString

java/integTest/src/test/java/glide/TestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
related to: https://github.com/aws/glide-for-redis/pull/1656
The function kill tests need to wait for scripts to run and be killed and this involves a little too many moving parts.  Reduced the tests to just the barebones required calls to reduce the change of something getting dropped. 
=> Java: Simplify function kill tests to reduce flakiness

java/client/src/main/java/glide/api/RedisClusterClient.java, java/client/src/main/java/glide/api/models/commands/scan/ScanOptions.java, java/client/src/main/java/glide/api/models/configuration/NodeAddress.java, java/client/src/main/java/glide/connectors/handlers/CallbackDispatcher.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java
N/A
Fix P1 issues reported by spotbugs and a few P2s that are critical (most notably missing break statements in switch cases).
=> Java: Fix critical spotbugs findings

java/client/src/main/java/glide/connectors/handlers/MessageHandler.java, java/client/src/test/java/glide/connectors/handlers/MessageHandlerTests.java
Unit tests for PubSub, particularly MessageHandler
=> Java: Unit tests for PubSub

java/integTest/build.gradle, java/integTest/src/test/java/glide/PubSubTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TestConfiguration.java, java/integTest/src/test/java/glide/TransactionTestUtilities.java, java/integTest/src/test/java/glide/cluster/ClusterClientTests.java, java/integTest/src/test/java/glide/cluster/ClusterTransactionTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
I applied automatic refactoring to things I found.
No code changes - only renames.
=> Java: remove redis references from IT

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/models/PubSubMessage.java, java/client/src/main/java/glide/connectors/handlers/MessageHandler.java, java/client/src/test/java/glide/connectors/handlers/MessageHandlerTests.java, java/client/src/test/java/glide/connectors/handlers/PubSubMessageQueueTests.java, java/integTest/src/test/java/glide/PubSubTests.java
=> Java: async `getPubSubMessage`.

java/client/src/main/java/glide/api/models/GlideString.java
=> Java: Add docs to `GlideString`

java/client/src/main/java/glide/api/RedisClient.java, java/client/src/main/java/glide/api/commands/GenericCommands.java, java/client/src/main/java/glide/api/models/Transaction.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
The SCAN (standalone service) needs GlideString API for returning keys in GlideString format. 
=> Java: add scan standalone (GlideString version)

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/commands/stream/StreamAddOptionsBinary.java, java/client/src/main/java/glide/api/models/commands/stream/StreamReadGroupOptions.java, java/client/src/main/java/glide/api/models/commands/stream/StreamReadOptions.java, java/client/src/main/java/glide/api/models/commands/stream/StreamTrimOptions.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java
support xgroup with GlideString
=> support xgroup, xread and xreadgroup  with GlideString

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java, java/client/src/test/java/glide/api/RedisClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
support mset and msetnx with GlideString
=> support mset and msetnx with GlideString

java/client/src/main/java/glide/api/models/BaseTransaction.java
=> Java transaction: fixed: `zunionstore` & `zinterstore` for binary version

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/models/commands/stream/StreamPendingOptionsBinary.java, java/client/src/main/java/glide/api/models/commands/stream/StreamRange.java, java/client/src/test/java/glide/api/GlideClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java
Uncomment commented integration tests
=> Uncomment commented integration tests

glide-core/src/client/mod.rs, glide-core/src/protobuf/command_request.proto, glide-core/src/socket_listener.rs, java/client/src/main/java/glide/api/models/commands/scan/BaseScanOptions.java, java/client/src/main/java/glide/api/models/commands/scan/ScanOptions.java, java/client/src/main/java/glide/managers/CommandManager.java, python/python/glide/glide_client.py
=> changed cluster scan to bytes

java/DEVELOPER.md, java/benchmarks/src/main/java/glide/benchmarks/clients/Client.java, java/benchmarks/src/main/java/glide/benchmarks/clients/glide/GlideAsyncClient.java, java/benchmarks/src/main/java/glide/benchmarks/clients/jedis/JedisClient.java, java/benchmarks/src/main/java/glide/benchmarks/clients/lettuce/LettuceAsyncClient.java, java/benchmarks/src/main/java/glide/benchmarks/utils/Benchmarking.java, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/models/configuration/BaseClientConfiguration.java, java/client/src/main/java/glide/api/models/configuration/ServerCredentials.java, java/client/src/main/java/glide/ffi/resolvers/GlideValueResolver.java, java/client/src/main/java/glide/managers/BaseResponseResolver.java, java/client/src/main/java/glide/managers/CommandManager.java, java/client/src/main/java/glide/managers/ConnectionManager.java, java/client/src/test/java/glide/ExceptionHandlingTests.java, java/client/src/test/java/glide/api/GlideClientCreateTest.java, java/client/src/test/java/glide/api/GlideClusterClientTest.java, java/client/src/test/java/glide/ffi/FfiTest.java, java/client/src/test/java/glide/managers/ConnectionManagerTest.java, java/integTest/src/test/java/glide/PubSubTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/TestConfiguration.java, java/integTest/src/test/java/glide/TestUtilities.java, java/integTest/src/test/java/glide/cluster/ClusterClientTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java, java/src/lib.rs
=> Java: more renaming and doc fixes

python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/core.py, python/python/glide/async_commands/standalone_commands.py, python/python/glide/async_commands/transaction.py
=> Python: doc fixes

java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/models/GlideString.java, java/client/src/main/java/glide/api/models/commands/RangeOptions.java, java/client/src/main/java/glide/api/models/commands/ZAddOptions.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/client/src/test/java/glide/api/GlideClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java
Add binary support for z* commands in java client
=> Add binary support for z* commands in java client

README.md
=> Documentation: Fixed the main README file

.github/json_matrices/engine-matrix.json, .github/workflows/csharp.yml, .github/workflows/go.yml, .github/workflows/java.yml, .github/workflows/node.yml, .github/workflows/python.yml
Reducing the tests matrix to make the release process faster. SHOULD BE REVERTED TOMORROW.
=> CI: TEMP COMMIT: reduce the tests matrix

.github/workflows/go.yml, .github/workflows/java-cd.yml, .github/workflows/java.yml, .github/workflows/npm-cd.yml, .github/workflows/pypi-cd.yml
This reverts commit 4018de34779230de5f5977e78fbc420205b4d627.
We revert this change as it doesn't handle 'push' events. We will create a new PR soon with full solution
=> Revert "Fix the way we check repo owner on cd workflows (#1898)"

java/README.md
Added notice - Maven is pending
=> Update README.md - Added Maven Notice (publishing is pending)

.github/workflows/java-cd.yml, .github/workflows/npm-cd.yml, .github/workflows/pypi-cd.yml
Shouldn't be pass with the 'v' prefix
=> CD: Fix the descrpition of the release version in workflow_dispatch

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/sdiff/
=> Node: add SDIFF command

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/sinterstore/
=> Node: add SINTERSTORE command

.github/workflows/java.yml
Gradle Wrapper Validation action
https://github.com/gradle/actions/tree/main/wrapper-validation
=> Java: enable Gradle wrapper validation

node/rust-client/src/lib.rs
Add support for push notification in lib.rs on node wrapper
=> Node: Add support for Push operation in lib.rs

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/sdiffstore/
=> Node: add SDIFFSTORE command

.github/workflows/ort.yml, java/.ort.yml, utils/get_licenses_from_ort.py
- Added packages lists as artifact to the ORT tool workflow
- Changed skipped packages to be written to a file and uploaded instead of printing them to the PR contents 
- Fixed Java's analyzer 
- Upgraded ort version
=> ORT tool modifications

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/lset/
=> Node: implement LSET

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/rpushx/
https://valkey.io/commands/lpushx/
=> Node: Add `LPUSHX` and `RPUSHX`

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/sintercard/
=> Node: add SINTERCARD command

CHANGELOG.md, node/src/Commands.ts, node/src/GlideClient.ts, node/src/GlideClusterClient.ts, node/src/Transaction.ts, node/tests/RedisClient.test.ts, node/tests/RedisClusterClient.test.ts
https://valkey.io/commands/lolwut/
=> Node: Add LOLWUT command

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/smismember/
=> Node: add SMISMEMBER command

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/RedisClusterClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/zdiffstore/
=> Node: add ZDIFFSTORE command

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/zmscore/
=> Node: added ZMSCORE command

CHANGELOG.md, node/src/BaseClient.ts
Optional parameters were not included in the javadoc documentation.
=> Update sintercard and xadd docs

node/tests/tsconfig.json
All credits to @avifenesh.
No actual changes for tests. This file tells IDE about tests sub-project configuration, which helps with proper hints and code analysis.
=> Node: Add `tsconfig` for tests.

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
PR typing is dependent on the changes in https://github.com/valkey-io/valkey-glide/pull/2022
[zremrangebylex](https://valkey.io/commands/zremrangebylex/)
=> Node: Add zremrangebylex command

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/getrange/
=> Node: added GETRANGE command

java/integTest/src/test/java/glide/TestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java
If we add more tests, the counter goes over the int range.
=> Java: Fix `config_reset_stat` IT

CHANGELOG.md, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
https://valkey.io/commands/xgroup-createconsumer/
https://valkey.io/commands/xgroup-delconsumer/
Depends on PR #2084
=> Node: Add `XGROUP CREATECONSUMER` and `XGROUP DELCONSUMER` commands

node/src/Commands.ts
=> Node: Remove `LASTID` option from `XCLAIM`

.github/ISSUE_TEMPLATE/bug-report.yml
Update new bug template, it is limited now for 2 languages:
=> Update bug template.

node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts
* Node Commands Added.
**lmpop** node command added for binary api. https://valkey.io/commands/lmpop/
**lpushx** node command added for binary api. https://valkey.io/commands/lpushx/
* Files updated: 4
* Updated file names: SharedTests.ts, Transaction.ts, BaseClient.ts, Command.ts
=> lmpop and lpushx command added

node/src/BaseClient.ts, node/tests/SharedTests.ts
https://github.com/valkey-io/valkey-glide/issues/2120
=> add decoder to scripts

node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/GlideClient.test.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
Command updated: https://valkey.io/commands/hset/
Updated hset command parameter from Record<string, string> to HashDataType | Record<string, GlideString>.
=> hset parameter updated to HashDataType

node/src/BaseClient.ts, node/tests/SharedTests.ts
Command: **hget**(https://valkey.io/commands/hget/)
Changed decoder parameter to decoderOptions.
=> Decoder Options added for hget

node/src/BaseClient.ts, node/tests/SharedTests.ts
Command: hvals(https://valkey.io/commands/hvals/)
Updated hvals decoder parameter to options(DecoderOptions)
=> hvals decoder options updated

.github/workflows/pypi-cd.yml
Address alert https://github.com/valkey-io/valkey-glide/security/dependabot/4 and couple alerts posted [there](https://github.com/valkey-io/valkey-glide/actions/runs/10473956043).
I also fixed indentations with prettier
=> CI: Update pypi workflow

go/api/base_client.go, go/api/commands.go, go/api/response_handlers.go, go/integTest/shared_commands_test.go
- Implementing the GETDEL command
=> Go: Implementing GETDEL command

java/integTest/build.gradle
Removed get server version code from integ test's build.gradle.
=> Remove get server version code

CHANGELOG.md, java/client/src/main/java/glide/api/GlideClient.java, java/client/src/main/java/glide/api/GlideClusterClient.java, java/client/src/main/java/glide/api/commands/ServerManagementClusterCommands.java, java/client/src/main/java/glide/api/commands/ServerManagementCommands.java, java/client/src/main/java/glide/api/models/BaseTransaction.java, java/client/src/main/java/glide/api/models/commands/InfoOptions.java, java/client/src/test/java/glide/api/GlideClientTest.java, java/client/src/test/java/glide/api/GlideClusterClientTest.java, java/client/src/test/java/glide/api/models/TransactionTests.java, java/integTest/src/test/java/glide/TestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/TransactionTests.java
1. Update doc
2. Update API to ease use (see updated docs) - breaking change
=> Java: update `INFO` command

CHANGELOG.md, node/DEVELOPER.md, node/index.ts, node/rust-client/src/lib.rs, node/src/BaseClient.ts, node/src/Commands.ts, node/src/GlideClient.ts, node/src/GlideClusterClient.ts, node/tests/ScanTest.test.ts
Ready to review - memory profiled has been done - using cursor object or standalone consume the exact same amount of memory when setting 10000 keys and scanning them.
Thanks to @liorsve for amazing work!
#1821
=> implementation of cluster scan

node/package.json, node/tests/ScanTest.test.ts
Fixed mistakenly used cluster conf in SA tests.
For safety, changed hard codded key to uuid
removed unnecessary package.
=> fix scan tests

.github/json_matrices/engine-matrix.json, java/integTest/src/test/java/glide/PubSubTests.java
Unsubscribe only to what client was subscribed for to avoid `NOSUB` error introduced by valkey 8.
=> Java: fix pubsub IT for valkey 8

examples/java/src/main/java/glide/examples/ClusterExample.java
=> Java : Fix ExamplesApp

CHANGELOG.md, benchmarks/python/python_benchmark.py, python/python/glide/__init__.py
=> Python: add missing exports

python/INSTALL
=> Python: Remove deprecated INSTALL file

node/DEVELOPER.md, python/DEVELOPER.md
=> Update developer docs

glide-core/src/client/mod.rs
Fixes issue: https://github.com/valkey-io/valkey-glide/issues/1569
=> Wrong routing by GLIDE

CHANGELOG.md, python/python/glide/async_commands/server_modules/json.py, python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): #645
=> Python: adds JSON.CLEAR command

CHANGELOG.md, python/python/glide/__init__.py, python/python/glide/async_commands/server_modules/ft.py, python/python/glide/async_commands/server_modules/ft_constants.py, python/python/glide/async_commands/server_modules/ft_options/ft_create_options.py, python/python/tests/tests_server_modules/test_ft.py
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2429
New pull request to replace this: https://github.com/valkey-io/valkey-glide/pull/2413
New PR created to change the merge branch to release-1.2 instead of main.
=> Python [FT.CREATE] command added(Created for release-1.2 branch)

CHANGELOG.md, python/python/glide/async_commands/server_modules/json.py, python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): #2412 
=> Python: add JSON.NUMINCRBY command

CHANGELOG.md, glide-core/redis-rs/redis/src/cluster_routing.rs
Migrate fix from https://github.com/amazon-contributing/redis-rs/pull/193/files to this repo.
Related issues: #738, #2428, #2429, #2375, #2430, #2412
=> Update routing for commands from server modules.

CHANGELOG.md, python/python/glide/async_commands/server_modules/json.py, python/python/tests/tests_server_modules/test_json.py
=> Python: Adds JSON.NUMMULTBY Command

CHANGELOG.md, python/python/glide/async_commands/server_modules/ft.py, python/python/glide/async_commands/server_modules/ft_options/ft_constants.py, python/python/tests/tests_server_modules/test_ft.py
This Pull Request is linked to issue (URL): #2429
=> Python: Add commands `FT.ALIASADD`, `FT.ALIASDEL`, `FT.ALIASUPDATE`

CHANGELOG.md, glide-core/src/client/value_conversion.rs, java/client/src/main/java/glide/api/commands/servermodules/FT.java, java/client/src/main/java/glide/api/models/commands/FT/FTAggregateOptions.java, java/client/src/main/java/glide/managers/ConnectionManager.java, java/integTest/src/test/java/glide/modules/VectorSearchTests.java
=> Java: `FT.AGGREGATE`.

.github/workflows/python.yml, CHANGELOG.md, python/python/tests/tests_server_modules/search/test_ft_create.py, python/python/tests/tests_server_modules/test_ft.py
Fixes #2432
Similar to #2472 and #2388
=> Fix python CI

CHANGELOG.md, java/client/src/main/java/glide/api/commands/servermodules/Json.java, java/client/src/test/java/glide/api/commands/servermodules/JsonTest.java, java/integTest/build.gradle, java/integTest/src/test/java/glide/modules/JsonTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2430
=> Java: add JSON.DEL and JSON.FORGET

.github/workflows/node.yml, CHANGELOG.md, node/src/server-modules/GlideJson.ts, node/tests/ServerModules.test.ts
=> Node: Add command JSON.DEL and JSON.FORGET

CHANGELOG.md, node/src/server-modules/GlideJson.ts, node/tests/ServerModules.test.ts
=> Node: Add command JSON.TYPE

CHANGELOG.md, java/client/src/main/java/glide/api/commands/servermodules/FT.java, node/src/server-modules/GlideFt.ts, node/src/server-modules/GlideFtOptions.ts, node/tests/ServerModules.test.ts
This Pull Request is linked to issue (URL): #738
=> Node: add `FT.DROPINDEX` command

CHANGELOG.md, java/client/src/main/java/glide/api/commands/servermodules/Json.java, java/integTest/src/test/java/glide/modules/JsonTests.java
=> Java: `JSON.CLEAR`.

.github/workflows/lint-rust/action.yml, .github/workflows/node.yml, .github/workflows/rust.yml, .github/workflows/semgrep.yml
Add GH token where it was expected and remove where it wasn't.
1. Removes following errors from CI:
1. https://github.com/valkey-io/valkey-glide/actions/runs/10941314385/job/30390901801?pr=2330#step:3:326 (missing token)
2. https://github.com/valkey-io/valkey-glide/actions/runs/10945889521/job/30391119685#step:3:283 (unexpected token)
2. ~Add CI trigger for release branches~
=> CI: Minor fixes

CHANGELOG.md, python/python/glide/__init__.py, python/python/glide/async_commands/server_modules/json.py, python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): #2412 
=> Python: Add JSON.ARRINDEX Command

CHANGELOG.md, node/npm/glide/index.ts, node/src/server-modules/GlideJson.ts, node/tests/ServerModules.test.ts
=> Node: Add command JSON.STRLEN and JSON.STRAPPEND

.github/workflows/install-engine/action.yml, .github/workflows/python.yml, .vscode/settings.json, java/integTest/src/test/java/glide/TestConfiguration.java, node/tests/setup.js, python/python/tests/conftest.py, python/python/tests/test_pubsub.py
This pull request includes several changes aimed at improving the workflow configuration, logging levels in tests, and test case refinements. The most important changes include updating conditional checks in GitHub Actions workflows, adjusting logging levels in test setups, and refining test cases for better clarity and functionality.
* [`.github/workflows/install-engine/action.yml`](diffhunk://#diff-572a02db87c14e84d257336a1a25639bca0524f9f03aa687236f35db1aaa3a16L30-R30): Updated conditional checks to use 'aarch64-unknown' instead of 'aarch64' for better accuracy. [[1]](diffhunk://#diff-572a02db87c14e84d257336a1a25639bca0524f9f03aa687236f35db1aaa3a16L30-R30) [[2]](diffhunk://#diff-572a02db87c14e84d257336a1a25639bca0524f9f03aa687236f35db1aaa3a16L39-R39) …
=> fixes for CI

CHANGELOG.md, python/python/glide/__init__.py, python/python/glide/async_commands/server_modules/ft.py, python/python/glide/async_commands/server_modules/ft_options/ft_constants.py, python/python/glide/async_commands/server_modules/ft_options/ft_profile_options.py, python/python/glide/constants.py, python/python/tests/tests_server_modules/search/test_ft_search.py, python/python/tests/tests_server_modules/test_ft.py
This Pull Request is linked to issue (URL): #2429
=> Python: FT.PROFILE command added

node/package.json
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2496
=> Node: specify minimal Node.js version in package.json

go/api/base_client.go, go/utils/transform_utils.go, go/utils/transform_utils_test.go
=> Go: add Concat function

.github/workflows/full-matrix-tests.yml
This Pull Request is linked to issue #2548
=> fixing full testing

node/tests/GlideClusterClient.test.ts
Addressing https://github.com/valkey-io/valkey-glide/actions/runs/11681777117/job/32527635537
This Pull Request is linked to issue #2548
=> Increase timeout for GlideClusterClient tests to 40000ms

.github/workflows/install-shared-dependencies/action.yml, .github/workflows/python.yml
address this issue: https://github.com/valkey-io/valkey-glide/actions/runs/11681777117/job/32527570850
This Pull Request is linked to issue : #2548
=> fix py wrapper build in container test

java/README.md, node/README.md, node/tests/TestUtilities.ts, python/README.md, python/python/tests/conftest.py
=> CI fixes: Set request timeout for CI tests, removed MacOS 12 from documentation 

.github/workflows/python.yml
addressing this failure https://github.com/valkey-io/valkey-glide/actions/runs/11687184494/job/32544769145
This Pull Request is linked to issue #2583 
=> fix missing version

java/client/src/main/java/glide/api/commands/servermodules/FT.java, java/client/src/main/java/glide/api/models/commands/FT/FTAggregateOptions.java, java/integTest/src/test/java/glide/modules/VectorSearchTests.java
1. Rename `Expression` to `Clause` in `FTAggregateOptions`
2. Add missing docs
3. Remove unused data from VSS IT
#2428
=> Java: Update docs for VSS

.github/json_matrices/supported-languages-versions.json, go/Makefile, go/integTest/glide_test_suite_test.go, go/integTest/shared_commands_test.go
=> Go: Merge Go tests fix to release-1.2 branch, disable Go 1.18

python/python/tests/test_async_client.py
This Pull Request is linked to issue (URL): #2617 
=> Python: temporarily disable script kill with allPrimaries routing

.github/json_matrices/supported-languages-versions.json, .github/workflows/full-matrix-tests.yml
This Pull Request is linked to issue #2548
=> fixing full matrix action

node/tests/SharedTests.ts
=> Node: Removed mistakelny pushed 'fit' from CI

CHANGELOG.md, glide-core/src/client/value_conversion.rs, java/client/src/main/java/glide/api/commands/servermodules/FT.java, java/integTest/src/test/java/glide/modules/VectorSearchTests.java
=> Java: `FT._ALIASLIST`.

CHANGELOG.md, node/src/server-modules/GlideJson.ts, node/tests/ServerModules.test.ts
=> Node: Add command JSON.CLEAR

node/tests/GlideClusterClient.test.ts, node/tests/SharedTests.ts
Fix validation of error cases in node clients IT
=> Node: Fix error checks in tests

CHANGELOG.md, node/src/server-modules/GlideFt.ts, node/tests/ServerModules.test.ts
This Pull Request is linked to issue (URL): #2527
=> Node: Add FT._ALIASLIST command

.github/json_matrices/build-matrix.json
This Pull Request is linked to issue #2603 
=> changing macos latest to 14

Makefile, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/ffi/resolvers/StatisticsResolver.java, java/integTest/src/test/java/glide/SharedClientTests.java, java/src/lib.rs, java/src/linked_hashmap.rs
Implements the Java part for this issue: 
https://github.com/valkey-io/valkey-glide/issues/2376
=> Java: added Client API for retrieving internal statistics

CHANGELOG.md, glide-core/redis-rs/redis/src/cluster_routing.rs, python/python/glide/async_commands/server_modules/json_transaction.py, python/python/tests/tests_server_modules/test_json.py
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2683
=> Python: JSON commands in transaction

.github/workflows/ort.yml
Signed-off-by: avifenesh <aviarchi1994@gmail.com>
This Pull Request is linked to issue https://github.com/valkey-io/valkey-glide/issues/2711
=> ORT-external-fork-fix

python/python/glide/__init__.py, python/python/glide/async_commands/server_modules/glide_json.py, python/python/tests/tests_server_modules/test_ft.py, python/python/tests/tests_server_modules/test_json.py
=> Python: rename glide json

CHANGELOG.md, python/python/glide/config.py, python/python/tests/conftest.py, python/python/tests/test_config.py, python/python/tests/test_read_from_strategy.py, python/python/tests/utils/cluster.py
This Pull Request is linked to issue (URL): (https://github.com/valkey-io/valkey-glide/issues/643)
=> Python: add AZAffinity ReadFrom strategy support

python/python/tests/conftest.py, python/python/tests/test_read_from_strategy.py
=> Python: nit fix

CHANGELOG.md
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/643
=> Java: adding changelog for java az support change

python/python/glide/__init__.py
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/pull/2716
=> Python: Add missing export

node/DEVELOPER.md, node/package.json
It was broken by mistake recently.
=> Node: Fix modules CI

CHANGELOG.md
=> [Backport]Update changelog after release

glide-core/redis-rs/redis/src/commands/cluster_scan.rs, glide-core/redis-rs/redis/tests/test_async_cluster_connections_logic.rs, glide-core/redis-rs/redis/tests/test_cluster_async.rs
=> [Backport `main`] Apply linters to submodule (#2783)

.github/workflows/java-cd.yml, .github/workflows/java.yml, CHANGELOG.md, java/DEVELOPER.md, java/client/build.gradle
=> [Backport to `main`] Bump protoc (#2561)

python/python/tests/test_api_export.py
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2335
=> Python: Add API test to check for exported symbols

java/client/src/test/java/glide/ExceptionHandlingTests.java, java/client/src/test/java/glide/connection/ConnectionWithGlideMockTests.java, java/client/src/test/java/glide/ffi/FfiTest.java, java/client/src/test/java/glide/managers/CommandManagerTest.java, java/client/src/test/java/glide/managers/ConnectionManagerTest.java, java/integTest/src/test/java/glide/ErrorHandlingTests.java, java/integTest/src/test/java/glide/SharedClientTests.java, java/integTest/src/test/java/glide/SharedCommandTests.java, java/integTest/src/test/java/glide/cluster/ClusterClientTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, java/integTest/src/test/java/glide/standalone/StandaloneClientTests.java
Make assertion failures from type checks clearer in java IT.
Complete work started in #1078
=> Java: fix type assertions

.github/workflows/java-cd.yml, .github/workflows/java.yml, CHANGELOG.md, java/DEVELOPER.md, java/client/build.gradle
=> [Backport 1.2] Protobuf: bump to 29.1

CHANGELOG.md, go/api/base_client.go, go/api/set_commands.go, go/integTest/shared_commands_test.go
tests based off [Node SUnionStore command](https://github.com/valkey-io/valkey-glide/pull/1549)
=> Go: implement SUnionStore

CHANGELOG.md, go/api/base_client.go, go/api/set_commands.go, go/integTest/shared_commands_test.go
=> Go: add SUnion command

CHANGELOG.md, glide-core/Cargo.toml, glide-core/src/client/mod.rs, glide-core/tests/test_cluster_client.rs
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/1678
-   [X] Tests are added or updated.
-   [X] Commits will be squashed upon merging.
=> Ensure cluster client creation fail when engine is < 7.0 and sharded subscriptions are configured

node/tests/GlideClusterClient.test.ts
Fix AZ affinity ITs appeared after merging #2381 and misuse of `customCommand` API
=> Fix node ITs

CHANGELOG.md, go/api/base_client.go, go/api/sorted_set_commands.go, go/go.mod, go/integTest/shared_commands_test.go
Add the GO wrapper and integration tests for the ZIncrBy command.
This Pull Request is linked to issue https://github.com/valkey-io/valkey-glide/issues/2833
=> GO: Add ZIncrBy Command

CHANGELOG.md, go/api/base_client.go, go/api/commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2832 
=> GO: Add `HINCRBYFLOAT` command

CHANGELOG.md, go/api/base_client.go, go/api/commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2832
=> GO: Add `HINCRBY` command

examples/python/cluster_example.py, examples/python/ft_example.py, examples/python/json_example.py, examples/python/standalone_example.py
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/2663): [#2663]
=> Fixed imported exception names in python examples

.github/pull_request_template.md
=> Update merging guidance in PR template

csharp/DEVELOPER.md, go/DEVELOPER.md
This step is no longer necessary.
=> Remove `git submodule update` from DEVELOPER.md

deny.toml
This Pull Request is linked to issue (URL): [#2238](https://github.com/valkey-io/valkey-glide/issues/2238)
=> Revert #2235 deny.toml changes

.github/workflows/scale-shr-test.yml
In order to facilitate development of self hosted runners scaling solution, there is a need for a empty job that can be triggered manually. This workflow will be removed after the development completes
-   ~[ ] Destination branch is correct - main or release~
=> Add NO-OP worflow for testing of Self Hosted Runners scaling

python/DEVELOPER.md, python/python/glide/async_commands/core.py
I fixed two typos found in the documentation. 
The first assigned two different values to the same key (key1) and then tried to call the BITOP function on key1 and key2, which didn't exist. Fixing this lets users who want to use the example code have a working example that they can try.
The second was a spelling error in the DEVELOPER.md file in python. Fixing this adds more professionalism to the document.
No issue, just fixing minor documentation errors.
-   [ ] Tests are added or updated. (N/A - documentation only)
-   [X] Destination branch is …
=> Fixed minor documentation typos.

CHANGELOG.md, go/api/base_client.go, go/api/stream_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2834 
=> Go: XDel command added

node/src/BaseClient.ts, python/python/glide/config.py
=> removed unnecessary

go/api/base_client.go, go/api/options/stream_options.go, go/api/response_handlers.go, go/api/stream_commands.go, go/integTest/shared_commands_test.go
~Depends on #2882 (contains some code from there)~
This Pull Request is linked to issue (URL): #2881
=> Go: `XREADGROUP`.

go/api/base_client.go, go/api/hash_commands.go, go/api/response_handlers.go, go/api/set_commands.go, go/api/sorted_set_commands.go, go/integTest/shared_commands_test.go, go/integTest/test_utils.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2878
=> Go: update return types & response handlers for scan commands

go/api/base_client.go, go/api/options/stream_options.go, go/api/stream_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2968 
=> Go: `XGROUP CREATE`.

go/api/base_client.go, go/api/stream_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2881
=> Go xack command new

go/api/base_client.go, go/api/hash_commands.go, go/api/options/constants.go, go/api/response_handlers.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2970
=> Go: `HRANDFIELD`.

go/api/base_client.go, go/api/options/stream_options.go, go/api/response_handlers.go, go/api/stream_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2834
=> Go: Add command XClaim

go/api/base_client.go, go/api/command_options.go, go/api/generic_base_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2853
=> GO: Implement Copy Command

go/api/glide_client.go
=> quickfix of changing glideClient to become GlideClient

go/api/base_client.go, go/api/options/constants.go, go/api/options/stream_options.go, go/api/options/zrange_options.go, go/api/response_handlers.go, go/api/stream_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2881, https://github.com/valkey-io/valkey-glide/issues/2969
=> Go: Add command XRange and XRevRange

java/README.md
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3005
=> Java: Add os-maven-plugin example to README

python/pyproject.toml
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/2893)
-   [X] Tests are added or updated.
=> PYTHON: Add Python package description

.github/workflows/scale-shr-test.yml
=> Add ephemeral label for self hosted testing workflow

go/api/base_client.go, go/api/response_handlers.go, go/api/sorted_set_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2971
=> Go: `ZMSCORE`.

.github/json_matrices/build-matrix.json
=> Add ephemeral self hosted runner matrix configuration

.github/workflows/install-engine/action.yml, .github/workflows/scale-shr-test.yml
=> Update python tests workflow with unified SHR/Github runners valkey server building logic

.github/json_matrices/build-matrix.json
-   [X] Tests are added or updated.
=> Enable node tests for ARM

.github/json_matrices/build-matrix.json
-   [X] Tests are added or updated.
=> Enable java tests for ARM

.github/json_matrices/build-matrix.json
=> Enable ARM arch tests for full-matrix only. Use ephemeral EC2 runners.

go/api/base_client.go, go/api/sorted_set_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2972 
=> Go: Add ZDiffStore command

.github/json_matrices/build-matrix.json
=> Move musl ARM builds to ephemeral runners

glide-core/redis-rs/redis/src/cluster_client.rs, glide-core/redis-rs/redis/tests/test_cluster_async.rs, glide-core/src/client/mod.rs, glide-core/src/client/types.rs, glide-core/src/protobuf/connection_request.proto, glide-core/telemetry/Cargo.toml, glide-core/telemetry/src/lib.rs, glide-core/telemetry/src/open_telemetry.rs, glide-core/tests/test_cluster_client.rs, node/src/BaseClient.ts
This Pull Request is linked to issue (URL): [issues-2901](https://github.com/valkey-io/valkey-glide/issues/2901)
=> Core: Open telemetry client config

.github/workflows/node.yml
=> Fixup the test-node-container job. Limit the job to x86_64-unknown-linux-musl target since ARM archs are not supported

go/api/base_client.go, go/api/options/zinter_options.go, go/api/sorted_set_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2972
=> Go: add ZInterStore

.github/workflows/node.yml
=> Fixup test-node-container job to bypass all steps in for non x86_64-unknown-linux-musl targets

.github/workflows/node.yml
=> Fixup test-node-container job to bypass all steps in for non x86_64-unknown-linux-musl targets by checking the condition in each step.

CHANGELOG.md, csharp/.editorconfig, csharp/DEVELOPER.md, csharp/tests/Integration/IntegrationTestBase.cs, csharp/tests/tests.csproj
This Pull Request is linked to issue (URL): [https://github.com/valkey-io/valkey-glide/issues/3015]
=> updating xUnit, adding xUnit analyser rules and guidelines

.github/workflows/node.yml
=> Fixup (again) test-node-container job to bypass also checkout step in for non x86_64-unknown-linux-musl targets.

go/api/base_client.go, go/api/response_handlers.go, go/api/response_types.go, go/api/stream_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/pull/3052
=> [Sync Release 1.3 commit] `XRange` and `XRevRange`

go/api/base_client.go, go/api/sorted_set_commands.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): #2973 
=> Go: `ZRangeStore`

node/DEVELOPER.md, node/npm/glide/tests/ExportedSymbols.test.ts, node/package.json, node/src/BaseClient.ts, node/src/Commands.ts
=> Node: Fix @internal tag

go/Makefile, go/api/base_client.go, go/api/bitmap_commands_test.go, go/api/config.go, go/api/config_test.go, go/api/connection_management_commands_test.go, go/api/example_utils.go, go/api/generic_base_commands_test.go, go/api/generic_commands_test.go, go/api/glide_client.go, go/api/hash_commands_test.go, go/api/hyperloglog_commands_test.go, go/api/list_commands_test.go, go/api/options/zinter_options.go, go/api/server_management_commands_test.go, go/api/set_commands_test.go, go/api/sorted_set_commands.go, go/api/sorted_set_commands_test.go, go/api/stream_commands_test.go, go/api/string_commands_test.go, go/benchmarks/main.go, go/examples/main.go, go/integTest/request_routing_config_test.go, go/integTest/shared_commands_test.go
* Backport documentation example PR from main to release 1.3.
Signed-off-by: Joseph Brinkman <joe.brinkman@improving.com>
#	go/api/base_client.go
This Pull Request is linked to issue ([2828](https://github.com/valkey-io/valkey-glide/issues/2828))
=> [Backport 1.3] Move all documentation examples to separate test files (#3055)

.github/workflows/go-cd.yml, .github/workflows/java-cd.yml, .github/workflows/npm-cd.yml, .github/workflows/pypi-cd.yml
Backport #3122 into release 1.3 branch
=> [Backport `1.3`] Backport #3122 into release 1.3 branch

.github/workflows/install-engine/action.yml
=> Fix removing the Valkey source directory

.github/workflows/ort.yml, go/THIRD_PARTY_LICENSES_GO, java/THIRD_PARTY_LICENSES_JAVA, node/THIRD_PARTY_LICENSES_NODE, python/THIRD_PARTY_LICENSES_PYTHON, utils/get_licenses_from_ort.py
=> Go: ort workflow added

.github/workflows/ort.yml, go/THIRD_PARTY_LICENSES_GO, java/THIRD_PARTY_LICENSES_JAVA, node/THIRD_PARTY_LICENSES_NODE, python/THIRD_PARTY_LICENSES_PYTHON, utils/get_licenses_from_ort.py
This Pull Request is linked to issue (URL): #3150
=> Go: ort workflow added (#3137)

.github/workflows/go-cd.yml
This Pull Request is linked to issue (URL): #3051 
NOTE: All `workflow_dispatch` workflows (i.e.: manually triggered workflows) only takes the version from `main`, hence we have to merge to `main` (instead of `release-1.3`)
=> Go: Add Go CD approval

go/DEVELOPER.md
This Pull Request is linked to issue (URL): #2828 
=> Go: Updated developer guide for docs, examples, naming conventions

go/api/bitmap_commands_test.go, go/api/generic_base_commands_test.go, go/api/hash_commands_test.go, go/api/set_commands_test.go
There were some examples that were not passing when running `make example-test`. 
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/2828)
=> GO: fix broken examples that fail

go/api/base_client.go, go/api/generic_base_commands.go, go/api/generic_base_commands_test.go, go/integTest/shared_commands_test.go
As part of finalizing documentation we needed to ensure that all of our commands are following the same naming conventions.
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/2828)
=> GO: Fix func name casing

go/api/base_client.go, go/api/bitmap_commands_test.go, go/api/server_management_commands_test.go, go/api/sorted_set_commands_test.go, go/api/stream_commands_test.go
This pull request moves a few remaining documentation examples to the appropriate test files. All new Go command PRs will not include examples in the code. 
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/2828)
=> GO: Move remaining comment examples to test files

.github/workflows/npm-cd.yml, CHANGELOG.md
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3157
=> Node: Fix NPM CD tag

go/api/base_client.go, go/api/bitmap_commands_test.go, go/api/connection_management_cluster_commands.go, go/api/connection_management_cluster_commands_test.go, go/api/connection_management_commands_test.go, go/api/generic_base_commands_test.go, go/api/generic_cluster_commands_test.go, go/api/glide_client.go, go/api/glide_cluster_client.go, go/api/hash_commands_test.go, go/api/hyperloglog_commands_test.go, go/api/list_commands_test.go, go/api/server_management_cluster_commands_test.go, go/api/server_management_commands_test.go, go/api/set_commands_test.go, go/api/sorted_set_commands_test.go, go/api/stream_commands_test.go, go/api/string_commands_test.go
This PR is related to #3055 and adds back `GlideClusterClient` examples to files that were missed.
This Pull Request is linked to issue (URL): #2828 
=> Go: Add `GlideClusterClient` examples

.github/workflows/java-cd.yml, java/benchmarks/build.gradle
Fix https://github.com/valkey-io/valkey-glide/actions/runs/13290287324/job/37109551140
Failure was introduced by changes related to shadowing dependencies.
Benchmarking app was trying to recompile GLIDE and failed on signing step instead of trying to get RC from maven.
See working CD on this branch: https://github.com/valkey-io/valkey-glide/actions/runs/13314960843/job/37186861412
=> Java: Fix CD

go/api/base_client.go, go/api/bitmap_commands_test.go, go/api/connection_management_cluster_commands.go, go/api/connection_management_cluster_commands_test.go, go/api/connection_management_commands_test.go, go/api/generic_cluster_commands_test.go, go/api/glide_client.go, go/api/glide_cluster_client.go, go/api/hash_commands_test.go, go/api/hyperloglog_commands_test.go, go/api/list_commands_test.go, go/api/server_management_cluster_commands_test.go, go/api/server_management_commands_test.go, go/api/set_commands_test.go, go/api/sorted_set_commands_test.go, go/api/stream_commands_test.go, go/api/string_commands_test.go
Adding cluster example changes from main to release branch.
This Pull Request is linked to issue (URL): #2828 
=> Go: Add cluster examples to release-1.3

CHANGELOG.md
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/3150)
=> Update changelog for 1.3.0 release

CHANGELOG.md
This Pull Request is linked to issue (https://github.com/valkey-io/valkey-glide/issues/3150)
=> Update changelog for beginning of 1.4 release

README.md
Quick change to general `README`.
This Pull Request is linked to issue (URL): #3150 
=> Update `README` for Go's current status

.vscode/settings.json
=> Add the go project to VSCode's projects.

.github/workflows/go-cd.yml
=> Go/Quick CD fix

.github/workflows/go-cd.yml
Partially revert GHA env mangling made in #3178 and #3183
=> Go: fix CD again

README.md
=> Updated readme to include go

.github/workflows/go-cd.yml, .github/workflows/java-cd.yml, .github/workflows/npm-cd.yml, .github/workflows/pypi-cd.yml
This PR ensures that CD workflows run on a classic, manually managed self hosted runner for ARM configurations
=> Ensure CD workflows run on persistent self hosted runners

node/tests/GlideClusterClient.test.ts
This Pull Request is linked to issue (URL): #2837 #3027 
=> Fix Node AzAffinity Flaky Test

go/Makefile
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3204
~~-   [ ] CHANGELOG.md and documentation files are updated.~~
=> Go: fix modules test

.github/workflows/pypi-cd.yml
=> fix pypi cd

CHANGELOG.md, go/api/base_client.go, go/api/options/zintercard_options.go, go/api/sorted_set_commands.go, go/api/sorted_set_commands_test.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2972
=> Go: Add command ZInterCard

.github/workflows/python.yml, Makefile, python/DEVELOPER.md, python/python/tests/conftest.py
Added `-v` to `pytest` for more information during output.
This Pull Request is linked to issue (URL): 
=> Python: Added verbose test flag for `pytest`

go/.gitignore, go/Makefile, go/api/generic_cluster_commands_test.go, go/api/options/db_size_options.go, go/api/server_management_cluster_commands_test.go, go/benchmarks/main.go
Add licence header check + add missing headers.
=> Go: Add licence header check.

go/Makefile
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3177
=> Go: Remove -race flag on go test

deny.toml
This Pull Request is linked to issue (URL): #3226
CI for all clients fails: https://github.com/valkey-io/valkey-glide/actions/runs/13466704614/job/37633907140#step:3:878
```
error[unmaintained]: *ring* is unmaintained
┌─ /home/runner/work/valkey-glide/valkey-glide/glide-core/Cargo.lock:182:1
│
182 │ ring 0.17.10 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
```
-   [x] Destination branch is correct - main …
=> Suppress CI failure

CHANGELOG.md, go/api/sorted_set_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3233
=> Go: fixing cross slot error in ZINTERCARD examples

go/Makefile
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3177
=> Go: Remove -race flag on go test [release-1.3]

.github/workflows/ort.yml
This Pull Request is linked to issue (URL): #3246
ORT release v46 supports cargo manifest v4. Newer version of ORT requires additional changes.
=> Fix ORT CI.

go/Makefile, go/api/base_client.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3256
Note: This is just a bare minimum support for Intel mac, intended to help developers build their project locally. This is nowhere near a full support of X86 macOS by the Valkey-GLIDE Go binding by any means.
=> Go: X86_64 macOS support for developers

csharp/lib/src/lib.rs, csharp/tests/Integration/IntegrationTestBase.cs
=> C#: Remove `Redis` references.

go/api/base_client.go
Go: Fix doc for `ZPopMinWithOptions`
=> Go: Fix doc for `ZPopMinWithOptions`

.github/json_matrices/supported-languages-versions.json, .github/workflows/go-cd.yml, .github/workflows/go.yml, go/Makefile, node/package.json
---------
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3271
=> Go: Update Go versions used in CI [release-1.3]

.github/workflows/ort.yml, README.md
Add **Known issues** section to include info about `GLIBC` compatiblity issue on linux.
This Pull Request is linked to issue (URL): #3291 #3218
=> Update readme - include compatibility notice

README.md
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3291
=> Doc: add known issues

README.md
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3291
=> Doc: Amend Known Issues section of README [release-1.3]

benchmarks/csharp/Program.cs, csharp/lib/BaseClient.cs, csharp/lib/Commands/IConnectionManagementCommands.cs, csharp/lib/Commands/IStringBaseCommands.cs, csharp/lib/GlideClient.cs, csharp/lib/Internals/Message.cs, csharp/lib/Internals/MessageContainer.cs, csharp/tests/Integration/GetAndSet.cs
Reorganize client classes according to the design:
(silimar to what we have in java and go)
Docs:
for an arg:
This Pull Request is linked to issue (URL): #216
=> C#: Reorganize client structure.

CHANGELOG.md, go/api/base_client.go, go/api/config.go, go/api/config_test.go, go/integTest/glide_test_suite_test.go, go/integTest/readfrom_strategy_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3267
=> Go: Add AzAffinity Support

CHANGELOG.md, go/api/config.go, go/integTest/connection_test.go, go/integTest/glide_test_suite_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2858
=> Go: adding advanced client configs & connectionTimeout

.github/workflows/redis-rs.yml
redis-rs CI workflow wont fail as expected because of piping to tee.
This makes sure the error is returned correctly.
=> Make redis-rs CI workflow fail correclty in case of tests failure

CHANGELOG.md, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/GlideClusterClient.java, java/client/src/main/java/glide/ffi/resolvers/StatisticsResolver.java, java/client/src/main/java/glide/utils/ArrayTransformUtils.java, java/integTest/src/test/java/glide/TestUtilities.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/2839
=> Replacing Hash Maps in response handling with LinkedHashMap

CHANGELOG.md, glide-core/redis-rs/redis/tests/test_cluster_async.rs, glide-core/src/client/mod.rs, glide-core/telemetry/Cargo.toml, glide-core/telemetry/src/open_telemetry.rs
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3278
Publish spans by http and GRPC protocols was tested by local collector and cloudwatch - https://quip-amazon.com/JhYrAkJb60he/How-to-start-a-basic-open-telemetry-collector 
=> Core: OTEL - add http and grpc exporters

java/integTest/src/test/java/glide/cluster/ClusterClientTests.java, java/integTest/src/test/java/glide/cluster/CommandTests.java, java/integTest/src/test/java/glide/standalone/CommandTests.java, node/tests/GlideClient.test.ts, node/tests/TestUtilities.ts
This PR disables flaky tests for the time being. We will work on addressing them one-by-one.
This Pull Request is linked to issue (URL): #2524 #2642 #3057 #3065 #3066
=> Disable Flaky Tests

CHANGELOG.md, go/api/base_client.go, go/api/example_utils.go, go/api/geospacial_commands.go, go/api/geospacial_commands_test.go, go/api/options/constants.go, go/api/options/geoadd_options.go, go/api/options/zadd_options.go, go/integTest/shared_commands_test.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3365
=> Add command GeoAdd and the geospatial command interface

CHANGELOG.md, go/src/lib.rs
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3350
=> Go: fix unsafe precondition violation for slice::from_raw_parts

java/README.md
This Pull Request is linked to issue (URL): #3402 
Updating readme as mentioned in this issue: #3367 
=> Java: Update readme file

CHANGELOG.md, go/api/base_client.go, go/api/geospacial_commands.go, go/api/geospacial_commands_test.go, go/api/response_handlers.go, go/integTest/shared_commands_test.go
=> Go: add command GeoPos

README.md
=> Add Redis 7.1 support to README

go/benchmarks/go.mod, go/benchmarks/go.sum
=> Go: Upgrade go-redis dependency

README.md
Adding links in the README- getting started part to relative contents
=> Update README.md getting started part

examples/scala/build.sbt, examples/scala/src/main/scala/ClusterExample.scala
This Pull Request is linked to issue (URL): fixes #3404
```
$ sbt "runMain ClusterExample"
[info] welcome to sbt 1.10.1 (Ubuntu Java 17.0.14)
[info] loading project definition from /mnt/c/GitHub/babushka/examples/scala/project
[info] loading settings for project root from build.sbt ...
[info] set current project to example (in build file:/mnt/c/GitHub/babushka/examples/scala/)
[info] compiling 2 Scala sources to /mnt/c/GitHub/babushka/examples/scala/target/scala-3.3.3/classes ...
[info] running ClusterExample
2025-03-31T22:25:13.800477Z  INFO logger_core: Connection configuration -
Addresses: localhost:7000
TLS mode: No TLS
Cluster mode
Read from Replica mode: Only primary
database ID: 0
Protocol: RESP3
2025-03-31T22:25:13.807326Z  INFO redis::cluster_async: Connected to initial nodes: …
```
=> Fix scala example.

CHANGELOG.md, go/api/base_client.go, go/api/glide_cluster_client.go, go/api/options/lcs_options.go, go/api/string_commands.go, go/api/string_commands_test.go, go/integTest/shared_commands_test.go
GO:  Implement Lcs command with options
**Issue link**
This Pull Request is linked to issue : #3476
=> GO: Implement Lcs command with options

go/Makefile
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3508
~-   [ ] CHANGELOG.md and documentation files are updated.~
=> Go: Fix Rust static binary size

java/integTest/src/test/java/glide/cluster/CommandTests.java
Temporarily disable some of the flaky tests until resolved.
=> Java: Disable Flaky Tests

python/Cargo.toml, python/src/lib.rs
This Pull Request is linked to issue ([#3535](https://github.com/valkey-io/valkey-glide/issues/3535))
=> [Backport to release 1.3.2] Bump pyo3 version to ^0.24

node/src/server-modules/GlideJson.ts
Fix documentation for GlideJson.get method to include client parameter
This Pull Request is linked to issue #3512 
=> Fix documentation for GlideJson.get method (#3380)

CHANGELOG.md, node/npm/glide/index.ts, node/src/BaseClient.ts, node/src/Commands.ts, node/src/Transaction.ts, node/tests/SharedTests.ts, node/tests/TestUtilities.ts
---------
This Pull Request is linked to issue #3512 
=> Node: Enable +/-inf as score for ZADD (#3370)

go/api/config.go
This Pull Request is linked to issue https://github.com/valkey-io/valkey-glide/issues/3550
=> Go: fix documentation address typo

CHANGELOG.md, python/python/glide/async_commands/core.py, python/python/tests/test_async_client.py
This Pull Request is linked to issue #3554 
=> Python: Add equality check to ExpirySet

java/integTest/src/test/java/glide/SharedCommandTests.java
due to the failings https://github.com/valkey-io/valkey-glide/actions/runs/14345704221/attempts/2
=> Java: add delay to ensure debug sleep completion

.gitignore, docs/build-docs.sh, docs/markdown/index.md, docs/markdown/python/base_client.md, docs/markdown/python/base_transaction.md, docs/markdown/python/cluster_commands.md, docs/markdown/python/cluster_transaction.md, docs/markdown/python/config.md, docs/markdown/python/core.md, docs/markdown/python/exceptions.md, docs/markdown/python/glide_client.md, docs/markdown/python/glide_cluster_client.md, docs/markdown/python/index.md, docs/markdown/python/standalone_command.md, docs/markdown/python/standalone_transaction.md, docs/mkdocs.yml, node/build-docs, node/package.json, node/typedoc.json
This Pull Request is linked to issue (#2725 , #2377)
This PR adds infrastructure for a future workflow that would deploy to valkey-glide's github pages.
The website would be built and deployed using mkdocs, and at first will include only python+node docs.
The python docs are generated directly using the `mkdocstrings` plugin for mkdocs, while for node, first we generate the markdown files using `typedoc`, and then mkdocs is rendering them. 
-   [x] Create …
=> Added docs folder and infrastructure for mkdocs website

java/integTest/src/test/java/glide/SharedClientTests.java, java/integTest/src/test/java/glide/cluster/ClusterClientTests.java
This is a new PR that replaces the old one due to signing issues. This PR fixes these two flaky tests in the Java client.
This Pull Request is linked to issue (URL): #3557 #3057 
=> Java: Fix `send_and_receive_large_values` and `test_update_connection_password_acl_user`

node/npm/glide/index.ts
Fixes an issue where a dependency in `package.json` was not being found correctly.
This Pull Request is linked to issue (URL): #3425 
=> Node: Fix `ExportedSymbols.test.ts` Missing Dependency

go/integTest/shared_commands_test.go
Fixing FP number comparison in tests to avoid floating point impresision
https://github.com/valkey-io/valkey-glide/actions/runs/14287916122/job/40045340769#step:7:928 (failed 4/24)
```
=== NAME  TestGlideTestSuite/TestGeoSearchStore
shared_commands_test.go:10042: 
Error Trace:	/home/ubuntu/actions-runner/_work/valkey-glide/valkey-glide/go/integTest/shared_commands_test.go:10042
/home/ubuntu/actions-runner/_work/valkey-glide/valkey-glide/go/integTest/glide_test_suite_test.go:339
Error:      	Not equal: 
expected: map[string]float64{"Catania":56.4412578701582, "Palermo":190.44242984775784, "edge1":279.7404521356343, "edge2":279.7403417843143}
actual  : map[string]float64{"Catania":56.44125787015819, "Palermo":190.44242984775792, "edge1":279.7404521356344, "edge2":279.7403417843142}
Diff: …
```
=> Go: fix geo tests.

CHANGELOG.md, go/api/function_command_results.go, go/api/glide_client.go, go/api/glide_cluster_client.go, go/api/response_handlers.go, go/api/scripting_and_function_cluster_commands.go, go/api/scripting_and_function_commands_test.go, go/api/scripting_and_function_standalone_commands.go, go/integTest/cluster_commands_test.go, go/integTest/standalone_commands_test.go
=> Add command FUNCTION STATS

java/integTest/src/test/java/glide/cluster/CommandTests.java
Adds a case where the checked field could be 0.
This Pull Request is linked to issue (URL): 
=> Java: Fix Flaky `config_reset_stat`

python/DEVELOPER.md
As part of the transition to `mkdocs`, we should not fully remove `sphinx` yet but put notes about the transition. Once `mkdocs` fully works, we can remove `sphinx` completely from the project.
This Pull Request is linked to issue (URL): #3582 
=> Python: Updated `DEVELOPER.md` with notes on `mkdocs`

java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java
=> Java: update doc for FUNC STAT under cluster mode

node/src/GlideClusterClient.ts
=> Node: Update FUNCTION STATS doc under cluster mode

node/README.md
This Pull Request is adding an installation part in the readme of node.js. 
=> add an installation part in the readme

README.md, node/README.md, python/README.md
This Pull Request is linked to issue (#556 )
=> Updates READMEs with docs site

CHANGELOG.md, go/api/base_client.go, go/api/glide_cluster_client.go, go/api/scripting_and_function_base_commands.go, go/api/scripting_and_function_cluster_commands.go, go/api/scripting_and_function_commands_test.go, go/integTest/cluster_commands_test.go, go/integTest/standalone_commands_test.go, go/integTest/test_utils.go
=> Go: Add command FUNCTION KILL

ffi/src/lib.rs, go/api/glide_cluster_client.go
This Pull Request is linked to issue (#3408)
=> Fix duplicate funcs

.github/workflows/build-python-wrapper/action.yml, .github/workflows/pypi-cd.yml, .github/workflows/python.yml, Makefile, ffi/Cargo.toml, python/.flake8, python/Cargo.toml, python/DEVELOPER.md, python/dev.py, python/dev_requirements.txt, python/pyproject.toml, python/tests/test_transaction.py
This PR introduces a unified dev.py CLI utility to streamline common developer tasks such as building, testing, linting, and generating protobuf files.
•	New dev.py script in python/ that replaces manual steps and Makefile logic
•	Support for:
•	build: Build sync/async Python clients (with --mode and --no-cache options)
•	test: Run test suite (with support for additional pytest args via --args)
•	lint: Run all Python linters (black, isort, flake8, mypy)
•	protobuf: Regenerate .proto files into .py and .pyi files
•	Reduces duplication across developer workflows
•	Ensures consistent environment setup and tooling execution
•	Makes test and linter execution easier and extensible (e.g. --args passthrough)
`python dev.py build --client async --mode release`
`python dev.py test --args …
=> Python: Added dev.py script to manage the python development workflows

CHANGELOG.md, go/api/base_client.go, go/api/glide_cluster_client.go, go/api/scripting_and_function_base_commands.go, go/api/scripting_and_function_cluster_commands.go, go/api/scripting_and_function_commands_test.go, go/integTest/cluster_commands_test.go, go/integTest/standalone_commands_test.go, go/integTest/test_utils.go
Adding the script kill command to the Go client.
This Pull Request is linked to issue (URL): #3481 
=> Go: Add `SCRIPT KILL`

.github/workflows/mkdocs-deploy.yml, docs/build-docs.sh, docs/markdown/python/glide_client.md, docs/markdown/python/glide_cluster_client.md, docs/markdown/style.css, docs/mkdocs.yml
This Pull Request is linked to issue: #3619 
This PR changes - 
1. Removes duplication of installing dependencies.
2. Adds the `BaseClient` docs in python under the `GlideClient` and `GlideClusterClient` so that they won't appear empty.
3. Changes color to the valkey shade of purple.
4. Changed "client" in the node nav to "client and commands" - so that it would be more symmetric to the python nav. and also because it's weird that "Transaction" doc is under "client".
The current look -  
-   [x] Destination …
=> Fixes to mkdocs site

node/src/BaseClient.ts
This Pull Request is linked to issue (URL): Fixes https://github.com/valkey-io/valkey-glide/issues/3681
=> Node: Fix `get` command example with Bytes decoder

CHANGELOG.md, go/api/base_client.go, go/api/function_command_results.go, go/api/glide_cluster_client.go, go/api/options/constants.go, go/api/response_handlers.go, go/api/scripting_and_function_base_commands.go, go/api/scripting_and_function_cluster_commands.go, go/api/scripting_and_function_commands_test.go, go/integTest/cluster_commands_test.go, go/integTest/standalone_commands_test.go
=> Go: Add Function List

.github/workflows/rust.yml, CHANGELOG.md, csharp/rust/src/ffi.rs, glide-core/redis-rs/redis/tests/test_cluster_async.rs, glide-core/src/client/mod.rs, glide-core/src/client/types.rs, glide-core/src/protobuf/connection_request.proto, glide-core/src/socket_listener.rs, glide-core/telemetry/Cargo.toml, glide-core/telemetry/src/lib.rs, glide-core/telemetry/src/metrics_exporter_file.rs, glide-core/telemetry/src/open_telemetry.rs, glide-core/telemetry/src/span_exporter_file.rs, glide-core/tests/test_cluster_client.rs, node/src/BaseClient.ts
This Pull Request is linked to issue (URL): [[#2902 ](https://github.com/valkey-io/valkey-glide/issues/2902)]
This PR added:
* Support to OpenTelemetry metrics in Core
* support to export metrics to local file
* tests
* changed the Otel object to more generally name: Signals which contain traces (spans) and metrics
* Some tests commented until we will change the OTEL to be a global configs
* This PR will be merge to a side branch until all the feature will be done
* This PR checked also with an external collector and cloudwatch
-   [x] CHANGELOG.md and documentation …
=> Core: OpenTelemetry metrics infrastructure

csharp/tests/Valkey.Glide.IntegrationTests/SharedClientTests.cs, csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/216
=> C#: Activate and fix disabled tests

docs/markdown/python/base_batch.md, docs/markdown/python/base_transaction.md, docs/markdown/python/cluster_batch.md, docs/markdown/python/cluster_transaction.md, docs/markdown/python/standalone_batch.md, docs/markdown/python/standalone_transaction.md, docs/mkdocs.yml, python/python/glide/async_commands/batch.py, python/python/glide/async_commands/cluster_commands.py
=> Python: fix mkdocs for batches

python/python/glide/async_commands/batch.py
=> Python: fix see section in batches

go/api/glide_client.go, go/api/glide_cluster_client.go
This Pull Request is linked to issue (#3769)
=> fix: add pubsub interfaces to glideclient and glideclusterclient

go/integTest/cluster_commands_test.go, go/integTest/glide_test_suite_test.go, go/integTest/standalone_commands_test.go, go/integTest/test_utils.go
=> Go: Add Function Kill Tests

.github/workflows/full-matrix-tests.yml
1. Run C# client tests on cron
2. Change defaults for checkboxes for manual run
=> Update full matrix CI

glide-core/THIRD_PARTY_LICENSES_RUST, java/THIRD_PARTY_LICENSES_JAVA, node/THIRD_PARTY_LICENSES_NODE, python/THIRD_PARTY_LICENSES_PYTHON
Reverts valkey-io/valkey-glide#3743
=> Revert "Updated attribution files for commit ce64e95b9e1fd2338ba785ebe05806dd1739fc81"

glide-core/THIRD_PARTY_LICENSES_RUST, java/THIRD_PARTY_LICENSES_JAVA, node/THIRD_PARTY_LICENSES_NODE, python/THIRD_PARTY_LICENSES_PYTHON
Reverts valkey-io/valkey-glide#3728
=> Revert "Updated attribution files for commit cc7eab291a9bfbf06008acfec104d21dc051645e"

node/THIRD_PARTY_LICENSES_NODE
Reverts valkey-io/valkey-glide#3699
=> Revert "Updated attribution files for commit 00d6545447bea205de0be264acc26026444cb33a"

glide-core/THIRD_PARTY_LICENSES_RUST
Reverts valkey-io/valkey-glide#3686
=> Revert "Updated attribution files for commit 2cbd215cb8dacf005550b4faf85dcee3bd93737f"

glide-core/THIRD_PARTY_LICENSES_RUST, java/THIRD_PARTY_LICENSES_JAVA, node/THIRD_PARTY_LICENSES_NODE, python/THIRD_PARTY_LICENSES_PYTHON
Reverts valkey-io/valkey-glide#3644
=> Revert "Updated attribution files for commit b6aa2e7eac7141774be2d5e40c5ab24c059bb7c2"

python/THIRD_PARTY_LICENSES_PYTHON
Reverts valkey-io/valkey-glide#3632
=> Revert "Updated attribution files for commit 4db99014ad6eab752ed8d4670e406525435b8c15"

glide-core/THIRD_PARTY_LICENSES_RUST, java/THIRD_PARTY_LICENSES_JAVA, node/THIRD_PARTY_LICENSES_NODE, python/THIRD_PARTY_LICENSES_PYTHON
Reverts valkey-io/valkey-glide#3590
=> Revert "Updated attribution files for commit 811033bc335abe377e107fbecdac70b79f3aafef"

CONTRIBUTING.md, README.md, cpp/README.md, csharp/DEVELOPER.md, docs/README.md, go/DEVELOPER.md, java/DEVELOPER.md, node/README.md, python/DEVELOPER.md, python/README.md
This pull request introduces extensive updates to the documentation across multiple files, focusing on improving clarity, enhancing community engagement, and updating project details. Key changes include rebranding the introductory sections, emphasizing the project's benefits, and adding consistent "Community Support and Feedback" sections to encourage user interaction.
* Updated introductory sections in `README.md` files for `python`, `node`, and `cpp` to rebrand the project as "Welcome to Valkey GLIDE!" and highlight features like reliability, performance, and community support. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R26) [[2]](diffhunk://#diff-c2d0c4dfb387f68c2d25ae9490c0d27c131da431e3ca6b32a1ad659c4668ceb3R1-R14) …
=> Add welcome and community sections to documentation files

go/api/base_client.go, go/api/glide_client.go, go/api/glide_cluster_client.go, go/integTest/glide_test_suite_test.go, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/commands/ListBaseCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsClusterCommands.java, java/client/src/main/java/glide/api/commands/ScriptingAndFunctionsCommands.java, java/client/src/main/java/glide/api/commands/SortedSetBaseCommands.java, java/client/src/main/java/glide/api/commands/StreamBaseCommands.java, java/client/src/main/java/glide/api/commands/StringBaseCommands.java, java/client/src/main/java/glide/api/models/BaseBatch.java, java/client/src/main/java/glide/api/models/configuration/RequestRoutingConfiguration.java, node/src/BaseClient.ts, node/src/Batch.ts, node/src/GlideClient.ts, node/src/GlideClusterClient.ts, python/python/glide/async_commands/batch.py, python/python/glide/async_commands/cluster_commands.py, python/python/glide/async_commands/core.py, python/python/glide/async_commands/standalone_commands.py, python/python/glide/routes.py
This PR addresses the discovered inconsistencies of documentation between clients.
=> Fix Inconsistencies in Documentation

CHANGELOG.md, go/api/connection_management_cluster_commands.go, go/api/connection_management_cluster_commands_test.go, go/api/glide_cluster_client.go, go/api/options/echo_options.go, go/integTest/cluster_commands_test.go
This PR addresses some user pain with `EchoWithOptions`.
This Pull Request is linked to issue (URL): #3801 
=> Go: Update `EchoWithOptions`

.github/workflows/pypi-cd.yml, python/python/glide/glide_client.py
This Pull Request is linked to issue https://github.com/valkey-io/valkey-glide/issues/3553
This PR is a cherry pick of - #3839 - backport from `release-1.3` branch.
=> added pypy support to pypi-cd workflow

csharp/rust/src/ffi.rs, glide-core/redis-rs/redis/src/cluster_client.rs, glide-core/redis-rs/redis/tests/test_cluster_async.rs, glide-core/src/client/types.rs, glide-core/src/protobuf/connection_request.proto, glide-core/tests/test_cluster_client.rs
Due to the move to a global configuration, unnecessary configurations were removed 
This Pull Request is linked to issue (URL): (https://github.com/valkey-io/valkey-glide/issues/3631)
=> Core: unnecessary configurations were removed

glide-core/redis-rs/redis/tests/support/util.rs, glide-core/redis-rs/redis/tests/test_cluster_pipeline.rs
=> Core: add retryConnectionError test and rename test_pipline.rs

go/api/base_client.go, go/integTest/pubsub_commands_test.go
Simple PR to fix some noticed spacing and indentation issues.
=> Go: Make spacing and indentation consistent in docs

.github/workflows/ort.yml, utils/get_licenses_from_ort.py
=> Configure ORT to fail the workflow if unapproved packages are found.

python/python/glide/async_commands/batch.py
This Pull Request is linked to issue (URL): [3546](https://github.com/valkey-io/valkey-glide/issues/3546)
=> Python- Fix Transaction Deprecation Message

node/rust-client/src/lib.rs
This Pull Request is linked to issue (URL): (https://github.com/valkey-io/valkey-glide/issues/3829)
=> Node: use the exiting life time if exit

python/python/glide/commands/sync_commands/cluster_commands.py, python/python/glide/commands/sync_commands/standalone_commands.py, python/python/glide/routes.py, python/python/glide/sync/glide_client.py, python/tests/test_sync_client.py
This Pull Request is linked to issue: #3494
Added routing functionality. 
Wanted to use existing tests and there isn't a good one for the info command that tests all scenarios , so added: 
1. Added the `test_echo` test so that there would be one test for both standalone and cluster (required adding the echo command implementations too).
2. Added some of theTestClusterRoutes class tests to test all types of routing.
-   [x] Create merge commit if merging …
=> Add routing to sync client

CHANGELOG.md, java/client/src/main/java/glide/api/BaseClient.java, java/client/src/main/java/glide/api/models/BaseBatch.java, java/client/src/main/java/glide/api/models/commands/RestoreOptions.java, java/client/src/test/java/glide/api/models/BatchTests.java
This Pull Request is linked to issue (URL): #3858 
=> Java: Add toArgs() to restore batch command

CHANGELOG.md, java/client/src/main/java/glide/api/models/commands/RestoreOptions.java, java/client/src/test/java/glide/api/GlideClientTest.java, java/integTest/src/test/java/glide/SharedCommandTests.java
This Pull Request is linked to issue (URL): #3858
=> Java: Add error restore command

.github/workflows/mkdocs-deploy.yml, docs/README.md, docs/markdown/python/base_batch.md, docs/markdown/python/cluster_batch.md, docs/markdown/python/cluster_transaction.md, docs/markdown/python/standalone_batch.md, docs/markdown/python/standalone_transaction.md, docs/mkdocs.yml
Issue: #3882 
This is a cherry-pick of #3913 
In order to trigger the site build+deployment from this branch after its merged.
---------
=> Docs: fixed mkdocs workflow trigger, fixed transaction/batch sections

go/api/config.go, go/api/config_test.go, go/api/glide_cluster_client.go
This Pull Request is linked to issue (URL): #473
=> Go: move BackoffStrategy configuration to BaseConfiguration

go/integTest/shared_commands_test.go
This Pull Request is linked to issue (#3707)
=> Use short key for testing ObjectEncoding

glide-core/redis-rs/redis/tests/test_cluster_async.rs
added head of the line blocking test for refresh slot (https://github.com/valkey-io/valkey-glide/pull/3926)
=> [Cherry-pick from main] Added head of the line blocking test for refresh slot (#3926)

glide-core/Cargo.toml, glide-core/telemetry/Cargo.toml
Signed-off-by: Avi Fenesh <aviarchi1994@gmail.com>
Cleanup cargo machete findings, and bump or remove minors of depepndencies 
=> cleanup rust dep

node/README.md, node/src/Commands.ts, python/python/glide/config.py
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3981
=> Documentation: Set clarification on SET command usage in documentation

python/.flake8, python/DEVELOPER.md, python/dev.py, python/docs/conf.py, python/pyproject.toml, python/python/glide/glide_client.py, python/python/glide/shared/commands/async_commands/cluster_commands.py, python/python/glide/shared/commands/async_commands/core.py, python/python/glide/shared/commands/async_commands/standalone_commands.py, python/python/glide/shared/commands/batch.py, python/python/glide/shared/commands/sync_commands/cluster_commands.py, python/python/glide/shared/commands/sync_commands/core.py, python/python/glide/shared/commands/sync_commands/standalone_commands.py, python/python/glide/shared/config.py, python/python/glide/shared/constants.py, python/python/glide/shared/exceptions.py, python/python/glide/shared/routes.py, python/python/glide/sync/glide_client.py, python/tests/test_config.py, python/tests/test_proto_coded.py
This PR continue to move shared files in the python client into the shared folder.
Rebased over #4015 
=> Python/Sync: Move protobuf folder into the shared folder

go/integTest/batch_test.go
Adding hyperloglog batch tests (only look at `batch_test.go`)
=> Go: Hyperloglog Batch Tests

go/integTest/batch_test.go
Adding Generic Base Commands Batch Tests
=> Go: Add Generic Base Batch Tests

go/integTest/batch_test.go
Adding Hash Batch Tests (only look at `batch_test.go`
=> Go: Add Hash Commands to Batch Test

go/integTest/batch_test.go
=> Go: Add String Batch Tests

go/integTest/batch_test.go, go/pipeline/base_batch.go
Adding set commands batch tests
=> Go: Add Set Commands Batch Tests

go/integTest/batch_test.go
Adding tests for PubSub Batch (only look at `batch_test.go`)
=> Go: PubSub Batch Tests

go/integTest/batch_test.go, go/pipeline/base_batch.go
=> Go: Add Sorted Set Batch Tests

go/integTest/batch_test.go, go/pipeline/base_batch.go
Adding function commands batch tests. 
=> Go: Function Commands Batch Tests

glide-core/telemetry/src/open_telemetry.rs
The OnceLock approach is perfect for counter use case because:
* Initialize once: Counter is created during OpenTelemetry setup
* Use many times: Multiple threads can increment without locks
* Thread-safe: Built-in synchronization guarantees
* High performance: No mutex overhead on the hot path
This is a significant improvement over the ```Mutex<Option<T>>``` pattern for shared, initialize-once data structures
-   [ ] Create merge commit if merging release …
=> Core: change otel metrics mutex to OnceLock approach

java/client/src/main/java/glide/api/OpenTelemetry.java, java/integTest/src/test/java/glide/OpenTelemetryTests.java
This Pull Request is linked to issue (URL): (https://github.com/valkey-io/valkey-glide/issues/4063)
=> Java: add check for sample percentage range

go/base_client.go, go/integTest/glide_test_suite_test.go, go/integTest/opentelemetry_test.go, go/opentelemetry.go
Addressing followup comments on the main PR: https://github.com/valkey-io/valkey-glide/pull/3932
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/3531
=> Go: OTel doc update

go/integTest/batch_test.go, go/integTest/cluster_commands_test.go
Fixing flaky tests in Go full matrix tests. 
Full matrix run: https://github.com/valkey-io/valkey-glide/actions/runs/15430188502
This Pull Request is linked to issue (URL): #4074 
=> Go: Fix Full Matrix Tests

CHANGELOG.md, go/base_client.go, go/integTest/batch_test.go, go/integTest/shared_commands_test.go, go/internal/interfaces/stream_commands.go, go/models/stream_command_results.go, go/pipeline/base_batch.go, go/response_handlers.go, go/stream_commands_test.go
=> Go: XRead and XReadGroup response update

go/opentelemetry.go
=> Go: free endpoint cstrings in otel config

CHANGELOG.md, go/connection_management_cluster_commands_test.go, go/connection_management_commands_test.go, go/glide_client.go, go/glide_cluster_client.go, go/integTest/batch_test.go, go/integTest/cluster_commands_test.go, go/integTest/standalone_commands_test.go, go/internal/interfaces/connection_management_cluster_commands.go, go/internal/interfaces/connection_management_commands.go, go/response_handlers.go
We need to account for the case where no client name was set (in which we should return null)
This Pull Request is linked to issue (URL): #4087 
=> Go: Fix `ClientGetName` and `ClientSetName`

CHANGELOG.md, go/base_client.go, go/integTest/batch_test.go, go/integTest/shared_commands_test.go, go/internal/interfaces/list_commands.go, go/internal/interfaces/sorted_set_commands.go, go/list_commands_test.go, go/options/stream_options.go, go/pipeline/base_batch.go, go/sorted_set_commands_test.go
Change type to `time.Duration` to make it clearer and readable.
This Pull Request is linked to issue (URL): #4007 
Signed-off-by: Edward Liang <edward.liang@improving.com>
=> Go: Change Blocking Commands to use `time.Duration`

glide-core/Cargo.toml, glide-core/redis-rs/redis/Cargo.toml, glide-core/redis-rs/redis/src/aio/connection.rs, glide-core/redis-rs/redis/src/aio/mod.rs, glide-core/redis-rs/redis/src/aio/tokio.rs, glide-core/redis-rs/redis/src/client.rs, glide-core/redis-rs/redis/src/cluster.rs, glide-core/redis-rs/redis/src/cluster_client.rs, glide-core/redis-rs/redis/src/connection.rs, glide-core/redis-rs/redis/src/lib.rs, glide-core/redis-rs/redis/src/types.rs, glide-core/redis-rs/redis/tests/support/cluster.rs, glide-core/redis-rs/redis/tests/support/mod.rs, glide-core/redis-rs/redis/tests/test_async.rs, glide-core/redis-rs/redis/tests/test_cluster.rs, glide-core/redis-rs/redis/tests/test_cluster_async.rs
The goal is to clean the code, validating nothing was hurt shows:
No size difference, slightly improved performance.
Before:
After:
This Pull Request is linked to issue #2710 
=> Remove unused tls crates

python/tests/test_opentelemetry.py
This PR fixes the python full matrix tests that failed mostly on open telemetry tests.
Successful run (on a side branch) - https://github.com/valkey-io/valkey-glide/actions/runs/15518287639/job/43688116325
=> Python: fix open telemetry tests

go/config/config_test.go, go/integTest/shared_commands_test.go
Fix failing test.
This Pull Request is linked to issue #4031
=> Fix build issue: resolve assertions

node/tsconfig.json
=> Update tsconfig.json: change "target" and "lib" from "ES2021" to "ES2025" to support Array.at() method.

.github/workflows/go-cd.yml
Fix broken FFI path in CD
This Pull Request is linked to issue (#4148)
=> fix: resolve broken ffi path

.github/workflows/go-cd.yml
Fix Linux artifact build in the CD pipeline.
This Pull Request is linked to issue (#4148 )
=> Broken FFI artifact on Linux builds

go/integTest/batch_test.go
Some tests have not been added yet in the main batch tests PR because of complexity. This PR will add the rest of it and complete the batch test suite.
Review only the last commit.
Wait for #4104 to be merged first
=> Go: Add Rest of Batch Tests

CHANGELOG.md, go/stream_commands_test.go
=> Go: XInfoStream example fix

CHANGELOG.md, go/base_client.go, go/integTest/batch_test.go, go/integTest/shared_commands_test.go, go/internal/interfaces/sorted_set_commands.go, go/internal/interfaces/stream_commands.go, go/options/zunion_options.go, go/sorted_set_commands_test.go, go/stream_commands_test.go
In these commands, we should require that options be provided.
This Pull Request is linked to issue (URL): closes #4124
=> Go: Remove Pointers for Options Args

.github/workflows/go-cd.yml
=> Go: fix CD

go/README.md, go/config/config.go
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4070
Updated the header section of Go README with the much better writing from README of python and node, also fixed naming inconsistency in both documentation and comments.
=> Go: Update README

node/src/BaseClient.ts
=> Node: fix examples

go/base_client.go
One part of the docs wasn't fixed. This PR fixes it.
This Pull Request is linked to issue (URL): #4070
=> Go: Fix `LInsert` `insertPosition` Docs

glide-core/Cargo.toml, glide-core/redis-rs/redis/Cargo.toml, glide-core/redis-rs/redis/src/connection.rs, glide-core/tests/utilities/mod.rs, utils/get_licenses_from_ort.py
Added commit
* Update TLS configuration to use aws-lc-rs crypto provider and improve error handling
* Update approved licenses and remove obsolete package from manual approval list
This Pull Request is linked to issue (URL):
=> Backport Release 2.0 Commit Into Main

go/config/doc.go, go/constants/constants.go, go/integTest/doc.go, go/models/doc.go, go/options/doc.go, go/options/zintercard_options.go, go/options/zunion_options.go, go/pipeline/doc.go
This PR adds package comments to the files to be picked up by `pkgsite`.
This Pull Request is linked to issue (URL): closes #4237
=> Go: Add Package Comments

README.md
This pr add a hyperlink to ioredis migraion guide in the readme
=> Add ioredis migration guide to readme

.github/workflows/codeql.yml, csharp/tests/Valkey.Glide.IntegrationTests/TestConfiguration.cs
Reverts valkey-io/valkey-glide#4287
=> Revert "Fix CodeQL to run only on relevant file changes with path filtering"

csharp/sources/Valkey.Glide/BaseClient.SetCommands.cs, csharp/sources/Valkey.Glide/Commands/ISetCommands.cs, csharp/sources/Valkey.Glide/Internals/Request.SetCommands.cs
We don't support command flags so we should throw an exception when a user tries to add it
This Pull Request is linked to issue (URL): #4221
=> C#: Add Set Commands Command Flag Exception

benchmarks/csharp/csharp_benchmark.csproj
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/security/dependabot/7
=> C#: Bump StackExchange.Redis version used in benchmarks

ffi/Cargo.toml
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4473
=> support cdylib crate-type in ffi package

README.md
=> Add migration guides links to the readme

.github/workflows/codeql.yml
As CodeQL caching issue is blocking our PR daily, remove all cache from CodeQL temporarily.
=> CI: Temporarily remove CodeQL cache

java/client/src/main/java/module-info.java, java/client/src/main/java/redis/clients/jedis/Jedis.java, java/client/src/main/java/redis/clients/jedis/args/ListDirection.java, java/client/src/main/java/redis/clients/jedis/args/ListPosition.java, java/client/src/main/java/redis/clients/jedis/params/LPosParams.java, java/integTest/src/test/java/compatibility/jedis/JedisTest.java
This Pull Request is linked to issue (URL): #4333 
=> Java: Add list commands for Jedis compatibility layer

java/integTest/src/test/java/glide/TestUtilities.java, java/integTest/src/test/java/glide/cluster/CommandTests.java
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4574
=> Java: Fix flaky test config_reset_stat

python/tests/test_api_consistency.py
NOTE: this is rebased on top of the script addition, to be merged only after https://github.com/valkey-io/valkey-glide/pull/4593.
This PR fixes the `test_api_consistency` test by including the function signatures from the rust defined types in the async python client (the functions in async python's `lib.rs` file, present also in the `glide.pyi` stub file).
This Pull Request is linked to issue: https://github.com/valkey-io/valkey-glide/issues/3500
-   [x] …
=> Python: fix consistency test

.github/json_matrices/build-matrix.json, .github/workflows/create-test-matrices/action.yml, .github/workflows/full-matrix-tests.yml, .github/workflows/go.yml, .github/workflows/java.yml, .github/workflows/node.yml, .github/workflows/npm-cd.yml, .github/workflows/python.yml, .github/workflows/rust.yml
This is 2 cherry-pick of these 2 related PRs - https://github.com/valkey-io/valkey-glide/pull/4683, https://github.com/valkey-io/valkey-glide/pull/4702
=> [Backport 2.1] CI/CD: Added self hosted macOS ARM runners

.github/workflows/go-cd.yml
This change was introduced in go musl support PR, seems like it was not functional.
=> Revert go upload step change

.github/workflows/go-cd.yml
=> CD: Fix Go musl CD issue

.github/workflows/npm-cd.yml
=> CD: Fix Node CD delete artifact issue 2nd try

python/glide-sync/pyproject.toml
This is a cherry-pick of https://github.com/valkey-io/valkey-glide/pull/4731
=> [Backport 2.1] Python Sync: revert license format

.github/workflows/java-cd.yml, java/jedis-compatibility/build.gradle
This Pull Request is linked to issue (URL): #4333
=> Java: Fix Jedis compatibility layer valkey-glide dependency

node/src/BaseClient.ts, node/tests/AuthTest.test.ts
This pull request is adding the iam configuration and `refreshIamToken` method into the node wrapper
This Pull Request is linked to issue [4498](https://github.com/valkey-io/valkey-glide/issues/4498)
=> Node: Adding Iam auth config and refreshIamToken method

ffi/src/lib.rs, glide-core/src/client/value_conversion.rs, logger_core/src/lib.rs
This Pull Request is linked to issue (#4756)
=> [Backport to 2.1] Resolve Rust lint issues

java/client/build.gradle, java/integTest/build.gradle
Fix for CI build on MUSL
This Pull Request is linked to issue [4813](https://github.com/valkey-io/valkey-glide/issues/4813)
=> Fix for CI build on MUSL

CHANGELOG.md, docs/markdown/lua-scripts-guide.md, docs/markdown/python/lua-scripts-guide.md
This Pull Request is linked to issue ([URL]): [[Task] Wiki: Add documentation to how to use Lua scripts with Glide](https://github.com/valkey-io/valkey-glide/issues/3387)
=> Add documentation to how to use Lua scripts with Glide

.github/workflows/install-engine/action.yml
This Pull Request is linked to issue (URL): https://github.com/valkey-io/valkey-glide/issues/4847
=> CI: Fix Valkey Server mismatch on self-hosted persistent runner

python/glide-shared/glide_shared/config.py, python/tests/test_config.py
=> Python: add refresh topology from initial nodes config
